### ISSUE TITLE
Bump minimum OpenTelemetry version to support type checks

### ISSUE THREAD

**Issue by plamut** [googleapis/python-bigquery#1038]
See the following comment for details: https://github.com/googleapis/python-bigquery/pull/1036#discussion_r739787329

If confirmed, we should bump to at least `opentelemetry-*==1.1.0`, and adjust our OpenTelemetry logic to the changes in the library API.

**Comment by tswast** [comment]
Good discovery. Bummer there were breaking changes.

Looks like Spanner has already updated, so we'll need this for compatibility with them as well. https://github.com/googleapis/python-spanner/pull/358

**Comment by plamut** [comment]
I see they bumped it to `>= 1.1.0`, thus we should probably just do the same.

**Comment by tswast** [comment]
Switching to type bug, since I believe our client will break if installed in the same environment as a Spanner client (and opentelemetry is installed)
