### ISSUE TITLE
Remove workarounds for the BQ Storage API issue with small result sets

### ISSUE THREAD

**Issue by plamut** [googleapis/python-bigquery#106]
Context: https://github.com/googleapis/python-bigquery/pull/55#discussion_r423382586

The BigQuery Storage API has an issue with fetching small result sets, thus the BigQuery library implements a fallback to `tabledata.list` API. Since the fix for that issue on the backend will be rolled out soon, the fallback will not be necessary anymore and should be removed.

**Comment by emkornfield** [comment]
@plamut  FWIW, the fix has finished rolling out on the backend.

**Comment by plamut** [comment]
@emkornfield Oh, that's great! Thanks for the heads-up!
