### ISSUE TITLE
Support Authorized Dataset

### ISSUE THREAD

**Issue by yongjiaw** [googleapis/python-bigquery#1064]
https://github.com/googleapis/python-bigquery/blob/705205430527f4c736fa4ad94b58e8cbb625fc11/google/cloud/bigquery/dataset.py#L134-L144

Not sure about the reason to have restricted entities here.
We need to use authorized dataset, and got ValueError.
![image](https://user-images.githubusercontent.com/8292918/142061667-88ba7356-4737-42ac-822f-d1e2043fc509.png)

**Comment by tswast** [comment]
> Not sure about the reason to have restricted entities here.

I agree that the client-side validation may be more trouble than its worth.

**Comment by tswast** [comment]
@yongjiaw I'm not seeing "dataset" listed here: https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets#Dataset.FIELDS.access Is this a new / preview feature?

**Comment by yongjiaw** [comment]
Not sure about the status of this feature, it's probably relatively new.
This is the only workaround to solves the problem of hitting the limit of 2500 authorized views per dataset.
https://cloud.google.com/bigquery/docs/authorized-datasets
https://cloud.google.com/bigquery/quotas#dataset_limits

**Comment by tswast** [comment]
Thanks @yongjiaw I've filed an issue 206825216 to our docs team to address the missing REST API docs.

@steffnay I think we want to remove the client-side validation of entity types and replace them with some enum values in https://github.com/googleapis/python-bigquery/blob/main/google/cloud/bigquery/enums.py for the folks that want some helpers to avoid typos.

**Comment by tswast** [comment]
This will be included in the next release, which is planned for January 4. We've paused releases in the meantime out of caution towards introducing changes around the holidays.
