### ISSUE TITLE
`schema_from_json` docs and samples

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#1069]
The [`schema_from_json`](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.client.Client.html#google.cloud.bigquery.client.Client.schema_from_json) method is useful for loading a BigQuery schema file into the Python objects expected by our client library. There are several opportunities for Python code samples in the [Using a BigQuery JSON schema file](https://cloud.google.com/bigquery/docs/schemas#using_a_json_schema_file) section of the docs describing that format:

* You can write an existing table schema to a local file by entering the following ~command~ [Python code] (`schema_to_json` sample) -- `bigquery_schema_file_from_table`
* The following ~command~ [Python code] loads data into a table using the schema definition in a JSON file -- `bigquery_load_with_schema_file`
* The following ~command~ [Python code] creates an empty table in an existing dataset using the schema definition in a JSON file -- `bigquery_create_table_with_schema_file`

**Comment by tswast** [comment]
In addition, I think `schema_from_json` is missing a return type based on what I'm seeing in the docs.

**Comment by tswast** [comment]
@loferris Potential task for once you've finished the code samples at https://github.com/googleapis/python-bigquery/pull/778

**Comment by meredithslota** [comment]
With the merging of #1436 and #1439 I think this is fixed, but wanted to validate that the missing return type for `schema_from_json` is also fixed before closing. cc: @tswast

**Comment by tswast** [comment]
@leahecole fixed the missing return type in https://github.com/googleapis/python-bigquery/pull/1582/files

Makes sense to me to close.
