### ISSUE TITLE
/usr/bin/python3: No module named model.recommendation_model_launcher_keras

### ISSUE THREAD

**Issue by anujraghuvanshi** [googleapis/python-bigquery#1092]
I am directly browsing the code on Google Codelab with their defined code but am not able to run the code block mentioned for training the model.

It's saying - /usr/bin/python3: No module named model.recommendation_model_launcher_keras

I am not getting any solution from anywhere.
![image](https://user-images.githubusercontent.com/22232709/146998219-ddc95354-0ce6-4ebf-b5c3-bd065dc9c98b.png)

Here's the Google Colab Link which includes Repo information also - https://colab.research.google.com/github/FirebaseExtended/codelab-contentrecommendation-android/blob/master/Firebase_ML_on_device_recommentations.ipynb#scrollTo=3gPKz5InxEbF

Repo used for running the code - https://github.com/tensorflow/examples

Is this any version problem or some missing or changed dependencies?

**Comment by tswast** [comment]
I believe this issue should be filed at https://github.com/FirebaseExtended/codelab-contentrecommendation-android where the example code you are running is from not this repository.

**Comment by tswast** [comment]
@gkaldev FYI

I don't appear to be able to transfer this issue across orgs, so closing.

**Comment by anujraghuvanshi** [comment]
Ohh, I see.

But somehow I was able to get it fixed. But I ran into another issue which seems to be an issue with python and TensorFlow - 

When I am executing the command given below for a dataset of 62400 records, then it's giving the issue. I have checked from [StackOverflow](https://stackoverflow.com/questions/59864408/tensorflowyour-input-ran-out-of-data) also but I not got the solution for me to run it - 

```python
!python -m model.recommendation_model_launcher_keras \
  --run_mode "train_and_eval" \
  --encoder_type "cnn" \
  --training_data_filepattern "data/examples/train_movielens_1m.tfrecord" \
  --testing_data_filepattern "data/examples/test_movielens_1m.tfrecord" \
  --model_dir "model/model_dir" \
  --params_path "model/sample_config.json"\
  --batch_size 100 \
  --learning_rate 0.1 \
  --steps_per_epoch 624 \
  --num_epochs 1 \
  --gradient_clip_norm 1.0 \
  --max_history_length 10
```

And I am getting this issue every time, no matter what flags I am trying, I am always getting this issue -

```
2021-12-23 05:57:59.251240: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
WARNING:tensorflow:Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches (in this case, 624 batches). You may need to use the repeat() function when building your dataset.
W1223 05:58:03.226532 139730008385408 data_adapter.py:1240] Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches (in this case, 624 batches). You may need to use the repeat() function when building your dataset.
Traceback (most recent call last):
```

I am not sure if it's a correct place to ask here but It will be appreciable if you assist me here on what's I am doing wrong here...

**Comment by tswast** [comment]
@anujraghuvanshi I'm unable to help with issues that aren't to do with the Python BigQuery client libraries here. Please file in a more appropriate location.
