### ISSUE TITLE
Is there any way to get the number of rows actually loaded, but not the total count for a table.

### ISSUE THREAD

**Issue by zhongdai** [googleapis/python-bigquery#1128]
Here is an [example](https://github.com/googleapis/python-bigquery/blob/main/samples/load_table_file.py), the code snippet is
```python
    # make a call of loadjob and use .result() to wait until it competes

    table = client.get_table(table_id)  # Make an API request.
    print(
        "Loaded {} rows and {} columns to {}".format(
            table.num_rows, len(table.schema), table_id
        )
    )
```

After the load job completed, it calls `get_table` to get the `num_rows`, and prints it. It works if we do a fresh load to an empty table, but when we load a file (or files) to an existing table by using `APPEND` mode, that number of rows is not the actually loaded count.

My workaround is, `get_table()` twice and calculate the difference between two counts. I am wondering is there any better approach to get the actually loaded rows (it is like the `affected rows` in other DBMS).

**Comment by mehul1811** [comment]
I am facing the same issue when appending the results of a query to an existing table using the QUERY job.

**Comment by chalmerlowe** [comment]
Based on staffing and project priorities, this item will not be worked.
