### ISSUE TITLE
Reading query table.list_rows based on start_index and max_results not working.

### ISSUE THREAD

**Issue by yantrikskaran** [googleapis/python-bigquery#113]
I am using python google.cloud.bigquery.client library.

Scenario: 
I have a query which is supposed to return 2M records. Due to another issue I am facing - https://github.com/googleapis/python-bigquery/issues/112#issuecomment-630632655

I thought of using of start_index and max_results on table.list_rows method on temp table of query results.
Rererence - 
https://cloud.google.com/bigquery/docs/paging-results#paging_through_query_results

I create a list of start_index and started multiple thread to read 1000000 records from the start_index. 

What I notice is that it is fetching same records more than once.

**Comment by HemangChothani** [comment]
@yantrikskaran This is the duplicate issue of https://github.com/googleapis/python-bigquery/issues/4 and it's already resolved in https://github.com/googleapis/python-bigquery/pull/27, so please wait for a new release, for now you can verify or use the master branch https://github.com/googleapis/python-bigquery therefore closing this issue.

**Comment by yantrikskaran** [comment]
> @yantrikskaran This is the duplicate issue of #4 and it's already resolved in #27, so please wait for a new release, for now you can verify or use the master branch https://github.com/googleapis/python-bigquery therefore closing this issue.

@HemangChothani Thanks a lot for pointing out. Any ETA for next release?

**Comment by HemangChothani** [comment]
@yantrikskaran I am not sure about, @plamut do you have any idea about next release?

**Comment by plamut** [comment]
@HemangChothani @yantrikskaran Pushed this forward just yesterday. There are a few things to check (as @shollyman told), but generally speaking there's an agreement that enough fixes have accumulated since the last release and it's time to make a new one.

**Comment by yantrikskaran** [comment]
> @HemangChothani @yantrikskaran Pushed this forward just yesterday. There are a few things to check (as @shollyman told), but generally speaking there's an agreement that enough fixes have accumulated since the last release and it's time to make a new one.

Looks like we are nearing a release. That s Great News.
