### ISSUE TITLE
Unable to load special characters from local storage from csv files

### ISSUE THREAD

**Issue by satheesh121** [googleapis/python-bigquery#1143]
How to load csv file from local storage into a temp table in bigquery that has special characters. can you please give any suggestions

**Comment by tswast** [comment]
I need more information to debug this. An example of the code you are using and ideally a small data file that can duplicate the problem would be much appreciated.

By special characters, do you mean unicode characters?

Are you able to load this file with the `bq` CLI or the web interface?

**Comment by satheesh121** [comment]
yes i was unable to load few unicode characters
