### ISSUE TITLE
BigQuery: Checking `streaming_buffer` results in KeyError

### ISSUE THREAD

**Issue by darwinyip** [googleapis/python-bigquery#116]
#### Environment details
1. Python version and virtual environment information: 3.7
2. google-cloud-bigquery version: 1.24.0

#### Steps to reproduce
Trying to access the field `streaming_buffer` gives an error when `streamingBuffer` is not present in the response because of how the `__init__` is defined:

```python
self.estimated_bytes = int(resource["estimatedBytes"])
self.estimated_rows = int(resource["estimatedRows"])
```

#### Example code
```python
client = bigquery.Client(project="project")
bq_table = self.client.get_table("dataset.table")
while bq_table.streaming_buffer.estimated_rows != 0:
    sleep(60)  # sleep for a bit
```

#### Stack trace
```
File "/usr/local/lib/python3.6/site-packages/google/cloud/bigquery/table.py", line 779, in streaming_buffer
    return StreamingBuffer(sb)
  File "/usr/local/lib/python3.6/site-packages/google/cloud/bigquery/table.py", line 1142, in __init__
    self.estimated_bytes = int(resource["estimatedBytes"])
KeyError: 'estimatedBytes'
```

**Comment by plamut** [comment]
@darwinyip This appears to have been fixed in https://github.com/googleapis/python-bigquery/commit/645f0fdb35ee0e81ee70f7459e796a42a1f03210 shortly after the `1.24.0` release, and will be included in the next release.

If possible, can you try the development version of BigQuery? With it, the issue should not be reproducible anymore.

**Comment by darwinyip** [comment]
@plamut Thanks, looks like that will fix it. Any ETA on when the next release will come out?

**Comment by plamut** [comment]
@darwinyip This is an unofficial answer, but there are planes to release the new version "in the near future", as quite a few fixes and improvements have accumulated since the least release. I do not have any exact dates yet, though.

**Comment by plamut** [comment]
@darwinyip FYI, a new version of the library has been released.

Could you please confirm that it indeed fixes the problem and that we can close this issue? Thanks!

**Comment by darwinyip** [comment]
Looks good
