### ISSUE TITLE
Dataset management operations in europe region are unreliable

### ISSUE THREAD

**Issue by evil-shrike** [googleapis/python-bigquery#1161]
My task is check for existence of a dataset and make sure it's located in a proper region. If not then recreate it. I'm experiencing very bizarre behavior of BigQuery when different methods behave inconsistently. I understand that the eventually consistence but there should be a way to write reliable software using eventually consistent systems. With BQ it's quite difficult. I've simplified my use-case to very simple code (below). The workflow is quite simple: check for existence, delete, create.
Why not delete w/o checking? Because in my case I compare location of existing dataset and need to delete a dataset only if it's in a wrong location.

Code to reproduce:
```python
from google.cloud import bigquery
import google.auth

SCOPES = [
    'https://www.googleapis.com/auth/cloud-platform',
    'https://www.googleapis.com/auth/bigquery',
    'https://www.googleapis.com/auth/bigquery.readonly',
]
project_id = 'gmc-dsa-segy'
dataset_id = 'test'
dataset_location = 'europe'
fully_qualified_dataset_id = project_id + '.' + dataset_id

credentials, project = google.auth.default(scopes=SCOPES)
client = bigquery.Client(project=project_id, credentials=credentials)

# check existence
try:
  dataset = client.get_dataset(fully_qualified_dataset_id)
  print(f'Found: {dataset.full_dataset_id} (location: {dataset.location})')
except BaseException as e:
  print(f'Dataset not found: {e}')

# delete
try:
  client.delete_dataset(fully_qualified_dataset_id, True)
  print('Dataset was deleted')
except BaseException as e:
  print(f'Failed to delete dataset: {e}')

# create
try:
  dataset = bigquery.Dataset(fully_qualified_dataset_id)
  dataset.location = dataset_location
  client.create_dataset(dataset)
  print(f'Dataset was created')
except BaseException as e:
  print(f'Failed to create dataset: {e}')
```

output of several runs

* 1st run (the dataset 'test' doesn't exist):
```
Dataset not found: 404 GET https://bigquery.googleapis.com/bigquery/v2/projects/gmc-dsa-segy/data
sets/test?prettyPrint=false: Not found: Dataset gmc-dsa-segy:test
Failed to delete dataset: 404 DELETE https://bigquery.googleapis.com/bigquery/v2/projects/gmc-dsa
-segy/datasets/test?deleteContents=true&prettyPrint=false: Not found: Dataset gmc-dsa-segy:test
Dataset was created
```
* 2nd run (immediate):
```
Dataset not found: 404 GET https://bigquery.googleapis.com/bigquery/v2/projects/gmc-dsa-segy/data
sets/test?prettyPrint=false: Not found: Dataset gmc-dsa-segy:test
Failed to delete dataset: 404 DELETE https://bigquery.googleapis.com/bigquery/v2/projects/gmc-dsa
-segy/datasets/test?deleteContents=true&prettyPrint=false: Not found: Dataset gmc-dsa-segy:test
Failed to create dataset: 409 POST https://bigquery.googleapis.com/bigquery/v2/projects/gmc-dsa-s
egy/datasets?prettyPrint=false: Already Exists: Dataset gmc-dsa-segy:test
```
The dataset exists (as it prevents creating yet another one with the same name) but can't be
deleted or checked for existence.
* 3rd run (after 2 minutes) 
```
Found: gmc-dsa-segy:test (location: EU)
Failed to delete dataset: 404 DELETE https://bigquery.googleapis.com/bigquery/v2/projects/gmc-dsa
-segy/datasets/test?deleteContents=true&prettyPrint=false: Not found: Dataset gmc-dsa-segy:test
Failed to create dataset: 409 POST https://bigquery.googleapis.com/bigquery/v2/projects/gmc-dsa-s
egy/datasets?prettyPrint=false: Already Exists: Dataset gmc-dsa-segy:test
```
Now the dataset found (via get_dataset) but can't be deleted
* 4th run (after 3 minutes) 16:25
```
Found: gmc-dsa-segy:test (location: EU)
Dataset was deleted
Dataset was created
```
After several minutes it starts working as intended.

If I change dataset_location='us' and run from scratch the result will be different. There's still the eventually consistence but it works much more reliable.
On 2nd run (immediate):
```
Dataset not found: 404 GET https://bigquery.googleapis.com/bigquery/v2/projects/gmc-dsa-segy/da
sets/test?prettyPrint=false: Not found: Dataset gmc-dsa-segy:test
Dataset was deleted
Dataset was created
```
and on 3rd (immediate):
```
Found: gmc-dsa-segy:test (location: US)
Dataset was deleted
Dataset was created
```

So it's a matter of seconds.

#### Environment details
  - Python version: 3.9.7
  - `google-cloud-bigquery` version: 2.26.0

PS> I guess the issue has nothing to do with the Python client indeed, but let's start from here, I'm not sure where to create issues for BigQuery server-side.

**Comment by meredithslota** [comment]
The internal issue is getting routed appropriately, so assigned this issue to myself to keep an eye on it. :)

**Comment by meredithslota** [comment]
Internal issue is still not fixed.

**Comment by meredithslota** [comment]
Updating to a bug accordingly based on internal investigation.

**Comment by chalmerlowe** [comment]
Closing this external bug based on the existence of an internal bug investigation. It appears that this issue is affected by more than just the Python client libraries (ie is likely affected by other components in the Bigquery stack).

Internal Bug tracker number: 223167348

**Comment by tswast** [comment]
FYI: according to internal issue 223167348,

> we expect that the bug [related to inconsistency when recreating a dataset with a different location from before] should be already fixed.
