### ISSUE TITLE
Add Sample function to list all BigQuery Datasets and Tables for a Project and return the results as a Dataframe

### ISSUE THREAD

**Issue by cedarwood-insights** [googleapis/python-bigquery#1218]
Hello.

I wish to make a small contribution to the python-bigquery sample code library. 

I've put together a simple function that will list all the dataset_ids and table_ids for a project, then return the results in a Pandas dataframe.

Essentially it takes snippets from the existing sample code [list_datasets.py](https://github.com/googleapis/python-bigquery/blob/234a4ffa1860b2c9e585e55f099a1780d26e3a85/samples/list_datasets.py) and [list_tables.py](https://github.com/googleapis/python-bigquery/blob/234a4ffa1860b2c9e585e55f099a1780d26e3a85/samples/list_tables.py) then adds code to load the results in a dataframe.

Happy to submit the draft code for review.

Kind regards
Mike

**Comment by cedarwood-insights** [comment]
Hello again.

I have just submitted a PR (1223) with the sample code and an associated test script for review.

The code has been tested locally using Nox. It tested successfully against Python versions 3-6, 3-7, 3-8, 3-9 and 3-10.

Here's some info about the test environment setup used:

### requirements.txt
db-dtypes==1.0.0
google-cloud-bigquery-storage==2.13.1
google-auth-oauthlib==0.5.1
grpcio==1.44.0
ipython===7.0.1; python_version == '3.6'
ipython===7.31.1; python_version == '3.7'
ipython===8.0.1; python_version == '3.8'
ipython==8.2.0; python_version >= '3.9'
pandas==1.0.0; python_version == '3.6'
pandas===1.3.5; python_version == '3.7'
pandas==1.4.2; python_version >= '3.8'
pyarrow==3.0.0; python_version == '3.6'
pyarrow==7.0.0; python_version >= '3.7'
pytz==2022.1
typing-extensions==4.1.1
google-cloud-bigquery==3.0.1

### requirements-test.txt
google-cloud-testutils==1.3.1
pytest==7.0.1; python_version == '3.6'
pytest==7.1.1; python_version >= '3.7'
mock==4.0.3

### conftest.py
The original source file used for this is here in the bigquery repo: [conftest.py](https://github.com/googleapis/python-bigquery/blob/main/samples/tests/conftest.py).

In my copy of this file I modified the order of loading the modules so that it would pass the lint checks. The modified order used was:

import datetime
from typing import Iterator
import uuid

import google.auth
from google.cloud import bigquery

import mock
import pytest

### Test Results
nox > Running session readmegen
nox > Session readmegen skipped: This session had no parameters available..
nox > Ran multiple sessions:
nox > * lint: success
nox > * blacken: success
nox > * py-3.6: success
nox > * py-3.7: success
nox > * py-3.8: success
nox > * py-3.9: success
nox > * py-3.10: success
nox > * readmegen: skipped

Hope this helps?

Kind regards
Mike

**Comment by meredithslota** [comment]
Linking issue to PR: https://github.com/googleapis/python-bigquery/pull/1223
