### ISSUE TITLE
BigQuery time_partitioning and partial schema not working

### ISSUE THREAD

**Issue by tpcgold** [googleapis/python-bigquery#122]
The BigQuery library seems to have a problem Creating a Timestamp Partitioned Table:
https://cloud.google.com/bigquery/docs/creating-column-partitions
With the combination of a Partial defined Schema:
https://cloud.google.com/bigquery/docs/pandas-gbq-migration

In the below example load_table_from_json is used but the problem also occurs when using load_table_from_dataframe.

The Table will always be created but without Partition! 

#### Environment details
1.BigQuery: General
2. OS independent
3. Python 3.8
4. google-cloud-bigquery 1.24.0

#### Code example

```python
client = bigquery.Client()

schema = [
    bigquery.SchemaField("timestamp", "TIMESTAMP"),
]

table_ref = bigquery.TableReference.from_string('.'.join([project, dataset, table_id]))
table = bigquery.Table(table_ref, schema=schema)
#table.time_partitioning = bigquery.TimePartitioning(
#    type_=bigquery.TimePartitioningType.DAY,
#    field="timestamp",  # name of column to use for partitioning
#)

job_config = bigquery.LoadJobConfig(schema=schema)
job_config.autodetect = True
job_config.schema_update_options = bigquery.job.SchemaUpdateOption.ALLOW_FIELD_ADDITION
job_config.time_partitioning = bigquery.TimePartitioning(
    type_=bigquery.TimePartitioningType.DAY,
    field="timestamp",  # name of column to use for partitioning
)

job_config.source_format = bigquery.SourceFormat.NEWLINE_DELIMITED_JSON
job_config.create_disposition = 'CREATE_IF_NEEDED'
job_config.write_disposition = 'WRITE_APPEND'
job = client.load_table_from_json(json.loads(json_str), table, job_config)
```

**Comment by plamut** [comment]
@tpcgold Just a sanity check, are you sure that `job_config` argument is passed to the method correctly?

Looking at the [source](https://github.com/googleapis/python-bigquery/blob/9d43d2073dc88140ae69e6778551d140430e410d/google/cloud/bigquery/client.py#L1872-L1882), the third argument is an optional `num_retries`, and `job_config` passed in as a positional argument gets bound to _that_.

Does the same problem occur if `job_config` is instead passed as a keyword argument?

```py
job = client.load_table_from_json(json.loads(json_str), table, job_config=job_config)
```

**Comment by tpcgold** [comment]
Thank you @plamut 
somehow didn't notice it  (-.-)

**Comment by plamut** [comment]
Great then, and no worries! :)
