### ISSUE TITLE
Error when using bigquery package with celery package

### ISSUE THREAD

**Issue by jung0han** [googleapis/python-bigquery#1230]
#### Environment details

  - OS type and version:ubuntu
  - Python version: Python 3.10.1
  - pip version: pip 22.0.4
  - `google-cloud-bigquery` version: 3.0.1
  - `celery`version: 5.2.6

#### Steps to reproduce

  1. If I run celery as multiprocessing and call the to_dataframe() on the worker, it stops working.
      but run celery as single thread, it works fine.
    - multi thread cmd : celery -A app.worker worker
    - single thread cmd : celery -A app.worker worker -P sole
  2. And If I call the result() function instead of the to_dataframe() and print the data, the result is output normally.

#### Code example

```python
celery_task = Celery(
    "app",
    broker="redis://127.0.0.1:6379/0",
    backend="redis://127.0.0.1:6379/0",
)

bq_client = bigquery.Client()

@celery_task.task()
def set_tracking():
    sql = "SELECT 1"
    df = bq_client.query(sql).to_dataframe()
```
```python
# It works.
def set_tracking():
    sql = "SELECT 1"
    results = bq_client.query(sql).result()
    for result in results:
        print(result)
# [2022-04-24 20:03:58,826: WARNING/ForkPoolWorker-6] Row((1,), {'f0_': 0})
```
#### Stack trace
celery closes without outputting any errors.

In order to minimize the time to receive data when using bigquery, the celery package is used to provide the service in the form of a background task.

However, there is no problem when receiving Big Query data in a single thread, but an error occurs only in multi-thread operation.

For debugging, there is no log output and the celery service just crashes, so it is difficult to solve it alone.

I would like to ask if there is a case where an error may occur when calling the to_dataframe() of the BigQuery package in multi-thread.

Thanks!

**Comment by jung0han** [comment]
I'll share what I've been debugging so far.

When the to_arror_iterable method is executed inside the to_arrow function,
an error 'Iterator has already started' occurs and the operation stops.

```python
# google/cloud/bigquery/table.py 1712 row
    def to_arrow(
        self,
        progress_bar_type: str = None,
        bqstorage_client: "bigquery_storage.BigQueryReadClient" = None,
        create_bqstorage_client: bool = True,
    ) -> "pyarrow.Table":
...
        if pyarrow is None:
            raise ValueError(_NO_PYARROW_ERROR)

        self._maybe_warn_max_results(bqstorage_client)

        if not self._validate_bqstorage(bqstorage_client, create_bqstorage_client):
            create_bqstorage_client = False
            bqstorage_client = None

        owns_bqstorage_client = False
        if not bqstorage_client and create_bqstorage_client:
            bqstorage_client = self.client._ensure_bqstorage_client()
            owns_bqstorage_client = bqstorage_client is not None

        try:
            progress_bar = get_progress_bar(
                progress_bar_type, "Downloading", self.total_rows, "rows"
            )

            record_batches = []
            # Error : 'Iterator has already started', <google.cloud.bigquery.table.RowIterator object at 0x7fdcee241690>
            for record_batch in self.to_arrow_iterable(
                bqstorage_client=bqstorage_client
            ):
...
```

**Comment by YAR0N** [comment]
Hi @jung0han! Were you able to solve your issue?

I am running into the same problem. The initial solution for me was to run `solo` as well. However, this causes connection problems with Redis on long-running tasks

**Comment by jung0han** [comment]
Hello @YAR0N.
I haven't been able to solve it yet, so I'm using the same `solo` option.

The expected solution is to implement a similar behavior directly without using the `to_dataframe()` method, but I don't think it will be easy.

**Comment by chalmerlowe** [comment]
Due to time commitments and workload, marking this as will not fix.
