### ISSUE TITLE
Improve code typing for a better coding experience

### ISSUE THREAD

**Issue by shenoy-anurag** [googleapis/python-bigquery#124]
I began working with Google's BigQuery product a week ago and since I use python, I installed this client library. Having used it to manage my data, run queries etc, I have realised that the library lacks proper typing for it's functions to allow IDEs to properly display the returned object's properties and methods.

I feel that adding typing hints to all the functions would help newbies like myself to find what they need and access the properties mentioned in the documentation for objects like QueryJob.

I'm raising this feature request to get feedback on whether this is a good idea.

Before:
![Screenshot from 2020-06-09 18-40-12](https://user-images.githubusercontent.com/19914954/84151534-27980a00-aa81-11ea-8699-39fe285ec155.png)

After (Adding typing to query() in client.py):
![Screenshot from 2020-06-09 18-40-29](https://user-images.githubusercontent.com/19914954/84151555-2f57ae80-aa81-11ea-841e-1cbbbfbb7478.png)

Edit:
Let me know if this issue is only affecting me as I'm using the PyCharm IDE or whether this is affecting others.
I know the doc strings are present in all the functions, but I feel signature typing hints would help a great deal.

**Comment by shenoy-anurag** [comment]
As mentioned by contributor plamut, adding these typing hints would cause a syntax error in python 2.x so this feature cannot be added until support for python 2 is dropped.
https://github.com/googleapis/python-bigquery/pull/125#issuecomment-641472593

**Comment by Kludex** [comment]
Can we reopen this now?
