### ISSUE TITLE
from google.cloud import bigquery ModuleNotFoundError: No module named ‘google’ 

### ISSUE THREAD

**Issue by yvoshchin** [googleapis/python-bigquery#1257]
I already ran pip install --upgrade google-cloud-bigquery

Not sure if this is some m1/python compatibility issue. Works on x86 fine.

When running my app I'm getting:

Traceback (most recent call last):
  File “./vlapp”, line 8, in <module>
    from google.cloud import bigquery
ModuleNotFoundError: No module named ‘google’

Additional details below:

Python 3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type “help”, “copyright”, “credits” or “license” for more information.
>>> from google.cloud import bigquery
Traceback (most recent call last):
  File “<stdin>“, line 1, in <module>
  File “/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/google/cloud/bigquery/__init__.py”, line 35, in <module>
    from google.cloud.bigquery.client import Client
  File “/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/google/cloud/bigquery/client.py”, line 59, in <module>
    from google.cloud.bigquery_storage_v1.services.big_query_read.client import (
  File “/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/google/cloud/bigquery_storage_v1/__init__.py”, line 25, in <module>
    from google.cloud.bigquery_storage_v1 import client
  File “/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/google/cloud/bigquery_storage_v1/client.py”, line 24, in <module>
    import google.api_core.gapic_v1.method
  File “/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/google/api_core/gapic_v1/__init__.py”, line 16, in <module>
    from google.api_core.gapic_v1 import config
  File “/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/google/api_core/gapic_v1/config.py”, line 23, in <module>
    import grpc
  File “/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/grpc/__init__.py”, line 22, in <module>
    from grpc import _compression
  File “/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/grpc/_compression.py”, line 15, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so, 0x0002): tried: ‘/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so’ (mach-o file, but is an incompatible architecture (have ‘x86_64’, need ‘arm64e’))
>>>

**Comment by parthea** [comment]
Hi @yvoshchin,

This issue is described in https://github.com/grpc/grpc/issues/28387.

[This comment](https://github.com/grpc/grpc/issues/28387#issuecomment-1016166913) has a workaround for installing the package from source (ignoring the wheel, which is not compatible). I also found a similar workaround [here](https://github.com/googleapis/python-secret-manager/issues/288#issuecomment-1096820989).

Since this issue is for the grpcio package specifically, I'm going to close this issue in favor of tracking there.
