### ISSUE TITLE
M1 Macbook import from google.cloud import bigquery ModuleNotFoundError: No module named ‘google’ 

### ISSUE THREAD

**Issue by adrian9122** [googleapis/python-bigquery#1260]
Hi there,

Still seeing this error on M1 Macbook for the big query SDK.
```

Traceback (most recent call last):
File “./vlapp”, line 8, in <module>
 from google.cloud import bigquery
ModuleNotFoundError: No module named ‘google’
```

But when I run pip show google-cloud-bigquery the library is set up correctly.

Already tried these troubleshooting steps without success
-This issue is described in https://github.com/grpc/grpc/issues/28387.
<img width="1288" alt="image (67)" src="https://user-images.githubusercontent.com/34860198/170284652-9a163bdc-6fd5-4663-b080-1c996e625c2b.png">

-https://github.com/grpc/grpc/issues/28387#issuecomment-1016166913 has a workaround for installing the package from source (ignoring the wheel, which is not compatible). I also found a similar workaround https://github.com/googleapis/python-secret-manager/issues/288#issuecomment-1096820989.

Have attached snippets of CLI commands as well. Can we have someone assist with a permanent fix for this, as we are unable to proceed with our workflow due to this bug?

<img width="1288" alt="image (67)" src="https://user-images.githubusercontent.com/34860198/170285038-493a9ffb-5604-445f-8435-e59cb7fc642a.png">
<img width="506" alt="image (66)" src="https://user-images.githubusercontent.com/34860198/170285055-a833ea85-6736-477f-92e2-8f5b82570485.png">
![image (65)](https://user-images.githubusercontent.com/34860198/170285064-ab77339f-61de-47b6-8cbc-93a082bc5869.png)

**Comment by meredithslota** [comment]
Thank you for filing this — I'm consolidating this will the similar issue here (https://github.com/googleapis/python-bigquery/issues/1262) so we can track and resolve together. Will escalate internally for a fix.

**Comment by meredithslota** [comment]
See https://github.com/googleapis/python-bigquery/issues/1262 for updates.
