### ISSUE TITLE
Table variable correction in browse_table_data.py

### ISSUE THREAD

**Issue by adhiggs** [googleapis/python-bigquery#1286]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-bigquery/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Steps to reproduce

Table variable needs to be updated in "# Print row data in tabular format."

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by adhiggs** [comment]
Addressed by pull request 1287.

**Comment by meredithslota** [comment]
https://github.com/googleapis/python-bigquery/pull/1287
