### ISSUE TITLE
query.to_dataframe erroe

### ISSUE THREAD

**Issue by beninzhao** [googleapis/python-bigquery#1291]
json.loads(db_connection.query(dest_number_sum_sql, job_config=job_config).to_dataframe().to_json(orient='records'))
If the result of the query is empty, to_dataframe will report an error
ERROR - Expecting property name enclosed in double quotes: line 1 column 3 (char 2)

**Comment by aribray** [comment]
Hi, thanks for opening this issue. I'm not able to replicate that error; the error message itself is related to `json.loads()`, which accepts only double quotes for json properties. I would check to make sure that your `dest_number_sum_sql` value is formatted correctly.
