### ISSUE TITLE
dbapi cursor "with" functionality

### ISSUE THREAD

**Issue by elzacho28** [googleapis/python-bigquery#1293]
I am implementing a universal database connector for an app and would like the ability to create cursors using the standard "with" functionality i.e.: 
``` 
with dbapi.cursor(connection) as cur:
        cur.execute(query)
```

currently this comes back with an error missing __enter__ attribute. I'm sure you all are plenty busy but wasn't sure why this feature hadn't been implemented or if I was missing something maybe. thanks in advance

**Comment by chalmerlowe** [comment]
I appreciate this suggestion. Thank you.
Adding the appropriate attributes (enter/exit) to the cursor to enable it to be used in conjunction with the context manager protocol as embodied by the with keyword could be very useful. Flagging this for consideration and triage.

**Comment by chalmerlowe** [comment]
Due to workload, personpower, and priorities, closing this request.
