### ISSUE TITLE
Releases failing (missing from GitHub)

### ISSUE THREAD

**Issue by thclark** [googleapis/python-bigquery#1297]
The latest published release is 2.34.x as shown [here](https://github.com/googleapis/python-bigquery/releases), which at the time of writing looks like this:

![Screenshot 2022-07-21 at 13 27 36](https://user-images.githubusercontent.com/7223170/180213383-e5ecabcb-a71e-4719-bb27-608ca8d5580e.png)

So, the obvious thing to do is to install `>=2.34.0,<3`.

I've just found out (because I googled for the lib and ended up on the pypi page) that there are many more recent releases. At the time of writing the latest is 3.2.0:

![Screenshot 2022-07-21 at 13 22 11](https://user-images.githubusercontent.com/7223170/180213271-8a5adacd-10ec-45e4-b8e3-f6f24b122a04.png)

I guess something went wrong on the release process but it would be helpful if the releases were fixed to show latest correctly.

**Comment by meredithslota** [comment]
Hi @thclark — I can see how that's confusing. It's "latest" as in "most recent", which is accurate — on June 9th we released two patches to older versions (2.34.4 and 1.28.2, respectively). But on June 6th, we released the "newest" version, which is 3.2.0. If you click into the releases, you can see them all: https://github.com/googleapis/python-bigquery/releases I hope this helps!
