### ISSUE TITLE
BigQuery: Add columns during table creation and import

### ISSUE THREAD

**Issue by sinistersparrow** [googleapis/python-bigquery#13]
I am asking for a feature request.
During loading of a bigquery table from CSV data,  I wish to add columns based on either a default answer or filename (from the csv)

consider this example:

```py
# from google.cloud import bigquery
# client = bigquery.Client()
# dataset_id = 'my_dataset'

dataset_ref = client.dataset(dataset_id)
job_config = bigquery.LoadJobConfig()
job_config.schema = [
    bigquery.SchemaField("name", "STRING"),
    bigquery.SchemaField("post_abbr", "STRING"),
]
job_config.skip_leading_rows = 1
# The source format defaults to CSV, so the line below is optional.
job_config.source_format = bigquery.SourceFormat.CSV
uri = "gs://cloud-samples-data/bigquery/us-states/us-states.csv"

load_job = client.load_table_from_uri(
    uri, dataset_ref.table("us_states"), job_config=job_config
)  # API request
print("Starting job {}".format(load_job.job_id))

load_job.result()  # Waits for table load to complete.
print("Job finished.")

destination_table = client.get_table(dataset_ref.table("us_states"))
print("Loaded {} rows.".format(destination_table.num_rows))
```

if we could add to job_config.schema a parameter (default answer), that could add to the template, and allow us to customize entry, that would be great.

for example:
```py
job_config.schema = [
    bigquery.SchemaField("name", "STRING"),
    bigquery.SchemaField("post_abbr", "STRING"),
    bigquery.SchemaField("filename", "STRING", var_filename),
    bigquery.SchemaField("Process_DT", "DATETIME", '2019-01-01 00:00:00')
]
```
by adding the last two fields, they are NOT required by CSV.

Optional addon:  any default parameter can override a CSV import field.

Thanks.

**Comment by JamesTheTerry** [comment]
I'm not sure if this would be possible, as the API doesn't appear to have an option like this which allows for additional fields to be fed it based on some variable.

https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#tablefieldschema

That being said, I would appreciate it if it could.

**Comment by tswast** [comment]
There is an option in the API to add fields to a table from a load job:

https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#JobConfigurationQuery.FIELDS.schema_update_options

This is exposed in Python as [`LoadJobConfig.schema_update_options`](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.job.LoadJobConfig.html#google.cloud.bigquery.job.LoadJobConfig.schema_update_options)

I believe this request is to actually do some schema autodetection based on the CSV contents, though?

**Comment by shollyman** [comment]
1) As tswast mentioned you can use the `ALLOW_FIELD_ADDITION` schema update option to evolve the schema in response to additional columns present in loaded data.

2) If the goal is to amend the schema explicitly, this needs to be by altering the schema and updating the table metadata as an independent operation.

3) Other permutations of this seem to imply the API service itself needs to be augmented, not the library.  If this is the case, please file a request against the BigQuery public issue tracker or via your established support channels: https://cloud.google.com/bigquery/docs/getting-support

I'm going to go ahead and close out this issue against the python library itself given the options outlined above.
