### ISSUE TITLE
to_dataframe_iterable / to_arrow_iterable memory leak

### ISSUE THREAD

**Issue by tocab** [googleapis/python-bigquery#1333]
#### Environment details

  - OS type and version: Ubuntu 18.04
  - Python version: 3.8.10
  - pip version: 22.1.2
  - `google-cloud-bigquery` version: 2.34.4

#### Code example

```
df_iterable = queryjob.result().to_dataframe_iterable(BigQueryReadClient())
for df in df_iterable:
   time.sleep(30)
```

Hi everyone, I have a problem with the bigquery method `to_dataframe_iterable()`. When I run it on a big table that, the memory increases constantly until the download of the whole table is done. This especially happens when I have a time consuming processing of every part table, indicated by `time.sleep(30)` in my example.

During the `time.sleep`, you can see in the memory and network usage of your system that the download continues, what makes sense because threading and a queue is used in the background, especially this part of the backend code is interesting:

```
    with concurrent.futures.ThreadPoolExecutor(max_workers=total_streams) as pool:
        try:
            # Manually submit jobs and wait for download to complete rather
            # than using pool.map because pool.map continues running in the
            # background even if there is an exception on the main thread.
            # See: https://github.com/googleapis/google-cloud-python/pull/7698
            not_done = [
                pool.submit(
                    _download_table_bqstorage_stream,
                    download_state,
                    bqstorage_client,
                    session,
                    stream,
                    worker_queue,
                    page_to_item,
                )
                for stream in session.streams
            ]

            while not_done:
                # Don't block on the worker threads. For performance reasons,
                # we want to block on the queue's get method, instead. This
                # prevents the queue from filling up, because the main thread
                # has smaller gaps in time between calls to the queue's get
                # method. For a detailed explaination, see:
                # https://friendliness.dev/2019/06/18/python-nowait/
                done, not_done = _nowait(not_done)
                for future in done:
                    # Call result() on any finished threads to raise any
                    # exceptions encountered.
                    future.result()

                try:
                    frame = worker_queue.get(timeout=_PROGRESS_INTERVAL)
                    yield frame
                except queue.Empty:  # pragma: NO COVER
                    continue

            # Return any remaining values after the workers finished.
            while True:  # pragma: NO COVER
                try:
                    frame = worker_queue.get_nowait()
                    yield frame
                except queue.Empty:  # pragma: NO COVER
                    break
        finally:
            # No need for a lock because reading/replacing a variable is
            # defined to be an atomic operation in the Python language
            # definition (enforced by the global interpreter lock).
            download_state.done = True

            # Shutdown all background threads, now that they should know to
            # exit early.
            pool.shutdown(wait=True)
```
A worker queue is used to store the dataframes temporarily that are returned by the streams. The problem that I see here is that the queue is not cleaned up after the `worker_queue.get(timeout=_PROGRESS_INTERVAL)` statement. The python docs suggest to have a queue.task_done() statement when it is run in threads: [https://docs.python.org/3.7/library/queue.html#queue.Queue.task_done](https://docs.python.org/3.7/library/queue.html#queue.Queue.task_done)
When I put the `task_done()` statement after every get in the method above, the memory leak is solved.

Would it be possible to integrate that? I can also look into adding it and open up a PR, if there are no objections.

**Comment by quassy** [comment]
Have you tried setting the `max_queue_size=1` (or even 0) like so? Make sure you are using Storage API also:
```py
df_iterable = queryjob.result().to_dataframe_iterable(BigQueryReadClient(), max_queue_size=1)
for df in df_iterable:
    time.sleep(30)
```

From docstring:
> max_queue_size – The maximum number of result pages to hold in the internal queue when streaming query results over the BigQuery Storage API. Ignored if Storage API is not used. By default, the max queue size is set to the number of BQ Storage streams created by the server. If ``max_queue_size`` is :data:`None`, the queue size is infinite. .. versionadded:: 2.14.0

**Comment by chalmerlowe** [comment]
Closing, will not fix.

**Comment by Ark-kun** [comment]
@chalmerlowe Why won't you fix it? It still leaks gigabytes and crashes. 

```py
        bqstorage_client = client._ensure_bqstorage_client()
        written_rows = 0
        with parquet.ParquetWriter(where=output_path, schema=arrow_schema) as writer:
            for batch in job.result().to_arrow_iterable(
                bqstorage_client=bqstorage_client,
                max_queue_size=1,
                max_stream_count=1,
            ):
                writer.write_batch(batch)
                written_rows += batch.num_rows
                print(f"{written_rows}/{result.total_rows}")
```

![Image](https://github.com/user-attachments/assets/8df18d91-ec61-43d3-93c5-328a9e2f5826)

**Comment by chalmerlowe** [comment]
@Ark-kun I appreciate this feedback.

I am the maintainer of this library and numerous others within Google. For good or for bad, it is me and one other person.

There are too many open issues (both publically here on github and privately in an internal google tracker) across all our open repos for us to address them all.

Even the task of trying to troubleshoot each and every one of them to determine which ones are still relevant is not possible.

As maintainers, we are tasked with:

* modernizing the library so that it is easier to maintain and update, which will free us up to handle more of the issues (i.e. evolve the library holistically, not just a function here, function there)
* adding new features so that users can access the latest capabilities of BigQuery
* fixing bugs
* improving documentation
* and more, lots more

The last time anyone commented on this was December 2022. That is, until now. Had I not closed this, I would not have seen your comment and would not have this additional information to help inform how we prioritize this versus our other work.
