### ISSUE TITLE
Pass tracing headers through bigquery into cloud functions/cloud run.

### ISSUE THREAD

**Issue by andaag** [googleapis/python-bigquery#1341]
**Is your feature request related to a problem? Please describe.**
Currently your opentracing setup is *lovely*, but we've recently started using cloud functions triggered by bigquery, and these can be hard to track down the performance of. Any chance you can pass the tracing headers through somehow?

 **Describe the solution you'd like**
Opentracing of a bigquery -> cloud function just works with normal header parsing.

 **Describe alternatives you've considered**
1. Monkeypatching your requestId generation here https://github.com/googleapis/python-bigquery/blob/76d88fbb1316317a61fa1a63c101bc6f42f23af8/google/cloud/bigquery/_job_helpers.py#L238 and parsing it out from https://cloud.google.com/bigquery/docs/reference/standard-sql/remote-functions#input_format
2. Add it to our actual sql, which seems hacky.

**Comment by shollyman** [comment]
I'm still unclear what the desired state is here.

In a BQ remote UDF scenario, the BQ service calls the cloud function (possibly many times, if there's lots of input rows and it needs to paginate).  The BQ client library isn't directly responsible for processing that incoming request (that's user code).  I'm also pretty sure that BQ doesn't set a usable remote span context that you can propagate.

You seem to be indicating that your remote UDF (triggered by running a query) is itself running a subquery per paged request?.  That feels like an antipattern, but if the goal is to set the job ID based on the incoming request that can be done without special opentracing manipulation.  Simply set the job ID when constructing the query job.

I'm likely misunderstanding things here, so feel free to clarify.

**Comment by chalmerlowe** [comment]
Due to limitations on time and workload, marking this as will not work.
