### ISSUE TITLE
Convert BigQuery schema to AVRO

### ISSUE THREAD

**Issue by danisanza** [googleapis/python-bigquery#1350]
Hi, 
I would like to know what would be the best approach to convert a BigQueryTable schema into an AVRO schema.
Thanks in advance and kind regards, Daniel

**Comment by esciara** [comment]
The apache beam library has a tool for that. Here is a link to the version to date : [bigquery_tools.get_avro_schema_from_table_schema](https://beam.apache.org/releases/pydoc/2.41.0/apache_beam.io.gcp.bigquery_tools.html#apache_beam.io.gcp.bigquery_tools.get_avro_schema_from_table_schema).

**Comment by PMcGloin** [comment]
**To parse an existing BQ schema from BQ connection into AVRO format in Python:**

from google.cloud import bigquery

CLIENT = bigquery.Client()

destination_table = <dataset_id> + "." + <table_name>
bq_table = CLIENT.get_table(destination_table)
#print(bq_table.schema)
generated_schema = [{'name': column.name, 'type': column.field_type} for column in bq_table.schema]

**Comment by PMcGloin** [comment]
@chalmerlowe Hi sorry I didn't even mean for that to post I thought it would save as an edit

I was having trouble with .to_gbq where it suddenly went from accepting ISO datetime strings in YYYY-MM-DDThh:mm:ss.ss format but managed to remedy the issue by converting them to datetime64[ns] types
