### ISSUE TITLE
BigQuery: Converting query results to dataframe fails to convert date columns

### ISSUE THREAD

**Issue by darwinyip** [googleapis/python-bigquery#136]
#### Environment details

```
google-api-python-client==1.9.3
google-cloud-bigquery==1.25.0
pyarrow==0.17.1
```

#### Steps to reproduce

  1. Issuing a select statement that returns a date column and converting the results to dataframe fails to convert the date column and leaves it as string

#### Code example

```python
select = "select DATE(date) as dt from [project:dataset.table]"
client = bigquery.Client()
job_config = bigquery.QueryJobConfig(use_legacy_sql=True)
select_job = client.query(select, job_config=job_config)
select_job.result()
df = select_job.to_dataframe()
df.dtypes

# dt    object
```

**Comment by HemangChothani** [comment]
@darwinyip Could you try to set the dtypes argument to to_dataframe. We don't have any logic to convert from the API response types to pandas dtypes unless the dtypes argument is specified.

Example:
    
     expected_dtype = {cloumn_name:dtype}    # e.x: dtype = 'datetime64[ns]'
     df = select_job.to_dataframe(dtypes=expected_dtype)
    
     df.dtypes["column_name"].name   #check dtype of cloumn


The duplicate issue of https://github.com/googleapis/python-bigquery/issues/11

**Comment by darwinyip** [comment]
Manually setting the dtype works but it's not a very friendly user experience.

**Comment by HemangChothani** [comment]
@darwinyip  Could you please comment on issue https://github.com/googleapis/python-bigquery/issues/11 as this is the duplicate issue and discussion is going on that thread so you can get better and faster reply, I have already linked and mentioned your comment there so closing this issue.
