### ISSUE TITLE
bug: Missing attribute: WKTReader

### ISSUE THREAD

**Issue by chalmerlowe** [googleapis/python-bigquery#1364]
An issue that appears to be in this library popped up while running a test in a related bigquery library.

```
.nox/prerelease/lib/python3.8/site-packages/google/cloud/bigquery/table.py:46: in <module>
    _read_wkt = shapely.geos.WKTReader(shapely.geos.lgeos).read
E   AttributeError: module 'shapely.geos' has no attribute 'WKTReader'
```

Based on a quick review, it appears that `shapely.geos` no longer has a `WKTReader` class and it appears that the `WKTReader` class has been removed from the library entirely and they might be relying on a function elsewhere in the codebase. If I had to wager a guess, I might look at the [from_wkt method in io.py](https://github.com/shapely/shapely/blob/e941610b0f748999aa1b6bb3ad3ec5eb6e20bc4e/shapely/io.py#L224).

#### Environment details

N/A

#### Steps to reproduce

N/A

#### Code example

N/A

#### Stack trace
```
nox > py.test --quiet --junitxml=prerelease_unit_3.8_sponge_log.xml tests/unit
ImportError while loading conftest '/tmpfs/src/github/python-bigquery-sqlalchemy/tests/unit/conftest.py'.
tests/unit/conftest.py:28: in <module>
    from . import fauxdbi
tests/unit/fauxdbi.py:29: in <module>
    import google.cloud.bigquery.schema
.nox/prerelease/lib/python3.8/site-packages/google/cloud/bigquery/__init__.py:35: in <module>
    from google.cloud.bigquery.client import Client
.nox/prerelease/lib/python3.8/site-packages/google/cloud/bigquery/client.py:63: in <module>
    from google.cloud.bigquery import _job_helpers
.nox/prerelease/lib/python3.8/site-packages/google/cloud/bigquery/_job_helpers.py:24: in <module>
    from google.cloud.bigquery import job
.nox/prerelease/lib/python3.8/site-packages/google/cloud/bigquery/job/__init__.py:27: in <module>
    from google.cloud.bigquery.job.copy_ import CopyJob
.nox/prerelease/lib/python3.8/site-packages/google/cloud/bigquery/job/copy_.py:21: in <module>
    from google.cloud.bigquery.table import TableReference
.nox/prerelease/lib/python3.8/site-packages/google/cloud/bigquery/table.py:46: in <module>
    _read_wkt = shapely.geos.WKTReader(shapely.geos.lgeos).read
E   AttributeError: module 'shapely.geos' has no attribute 'WKTReader'
```

**Comment by tparkerNYT** [comment]
I am still experiencing this issue with `from google.cloud import aiplatform` and `from vertexai import preview`. I am using the latest version of shapely.

**Comment by tomaxberg** [comment]
Try reinstall packages bs4, docarray, tiktoken, and streamlit. This worked for me.

**Comment by chalmerlowe** [comment]
@tparkerNYT

In looking at your tracebacks, they show line 46 in the file `google/cloud/bigquery/table.py` as:

`_read_wkt = shapely.geos.WKTReader(shapely.geos.lgeos).read`

Starting in version 3.3.6 of `python-bigquery`, code was inserted that began to refer to objects in `shapely` by their current nomenclature instead of referencing `WKTReader`.

If you upgrade your version of `python-bigquery`, it should fix this issue.

Gonna leave this issue closed and close out the related one in the `pubsub` library
