### ISSUE TITLE
Error occurred when executing sql

### ISSUE THREAD

**Issue by zsdyx** [googleapis/python-bigquery#1366]
#### Environment details

OS : Mac Pro 15
Python version:  Python 3.10.4
pip version: pip 22.1.2
 google-cloud-bigquery version: Version: 3.3.2

#### Code example

```python
query = """
            SELECT last_modified_time FROM `@project_id.@dataset_id.INFORMATION_SCHEMA.PARTITIONS`
            WHERE table_name LIKE '@table_name%'
            ORDER BY last_modified_time DESC limit 1
        """

        job_config = bigquery.QueryJobConfig(
            query_parameters=[
                bigquery.ScalarQueryParameter(
                    "project_id", "STRING", self.params.project_id),
                bigquery.ScalarQueryParameter(
                    "dataset_id", "STRING", self.params.dataset_id),
                bigquery.ScalarQueryParameter(
                    "table_name", "STRING", self.params.table_name)
            ]
        )
```

#### Stack trace
```
ERROR 2022-09-26 08:19:55,451 bigquery.py:43 : unknown exception query=SELECT last_modified_time FROM `@project_id.@dataset_id.INFORMATION_SCHEMA.PARTITIONS`WHERE table_name LIKE "@table_name%" ORDER BY last_modified_time DESC limit 1 err=400 Invalid project ID '@project_id'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by meredithslota** [comment]
Copying out the error message here for convenience: 

`ERROR 2022-09-26 08:19:55,451 bigquery.py:43 : unknown exception query=SELECT last_modified_time FROM `@project_id.@dataset_id.INFORMATION_SCHEMA.PARTITIONS`WHERE table_name LIKE "@table_name%" ORDER BY last_modified_time DESC limit 1 err=400 Invalid project ID '@project_id'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.
`

**Comment by shollyman** [comment]
This is a subtlety of what can be parameterized.  Parameterizing a table identifier is not allowed.  See https://cloud.google.com/bigquery/docs/parameterized-queries includes the caveat:

> Parameters cannot be used as substitutes for identifiers, column names, table names, or other parts of the query.

Your other option here is to use something like `EXECUTE IMMEDIATE` to build the query string indirectly and run it:
https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language#execute_immediate

Closing as this is not a library issue, but a documented constraint of the service itself.
