### ISSUE TITLE
Can not run google.cloud library on Mac M1 (mach-o, but wrong architecture)

### ISSUE THREAD

**Issue by thuantv-vp** [googleapis/python-bigquery#1373]
I run command line to import google cloud library on Mac M1 but it can not import this library.

Command line: "from google.cloud import bigquery"

I have already install library base on instruction of following link:

https://cloud.google.com/bigquery/docs/reference/libraries#client-libraries-install-python

And google try many way to fix this bug but can not.

pip install --no-binary :all: grpcio --ignore-installed
pip install --no-binary :all: grpcio-tools --ignore-installed

pip install grpcio==1.47.0

pip install grpcio==1.49.1

I read on Github and see that this bug is fixed on Google cloud bigquery for Mac M1, but actually it is not fixed.

I also brought another Mac M1 Machine from My friend and the issue is same.

It mean that every Mac M1 user can not import Google library on Local Machine for coding.

Python version 3.10.6

**Comment by meredithslota** [comment]
Thanks for filing this — we had believed this to be fixed (previous issues: #1260 and #1262). Can you share which version of the BigQuery client library you're using?

**Comment by minkichoe** [comment]
```sh
export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1
export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1
pip install grpcio
pip install google-cloud-bigquery
```

https://stackoverflow.com/questions/66640705/how-can-i-install-grpcio-on-an-apple-m1-silicon-laptop

**Comment by alvarowolfx** [comment]
We've tested on an M1 Mac with the provided installation instructions and it was successfully installed using up-to-date versions of `google-cloud-bigquery` and `grpcio`.  We'll close this issue for now.

```
pip install --upgrade google-cloud-bigquery
```

**Comment by andrew-dang-badal-io** [comment]
@alvarowolfx I am running into an error installing the google-cloud-bigquery library on an Mac M1. Could you please advise on how to resolve this issue?
