### ISSUE TITLE
Invalid version specification in setup.py

### ISSUE THREAD

**Issue by mamo3gr** [googleapis/python-bigquery#1402]
The version specification of pyarrow seems not to fulfill [PEP 440 (Version Identification and Dependency Specification)](https://peps.python.org/pep-0440/). I think it's a typo.

https://github.com/googleapis/python-bigquery/blob/929276949244f704688837dfca35cb7dacd44623/setup.py#L54

Due to this designation, some tools (e.g. [Poetry](https://python-poetry.org/)) detect it and fail when installing and/or locking packages.

**Comment by meredithslota** [comment]
Fixed in https://github.com/googleapis/python-bigquery/pull/1403. Thanks!
