### ISSUE TITLE
Support Pythons <4

### ISSUE THREAD

**Issue by cpcloud** [googleapis/python-bigquery#1412]
I'd like to be able to allow python <4 in ibis, but as of this PR (https://github.com/ibis-project/ibis/pull/4797) I cannot due to this library's `<3.11` pin.

**Comment by chalmerlowe** [comment]
@cpcloud 
Been speaking with @tswast about removing the pinned upper bound.
I don't see any problem with doing so. Let me take a look at the PR and see what we can arrange.
