### ISSUE TITLE
[bigquery magic command] syntax error when --params containts value 0

### ISSUE THREAD

**Issue by sugiyama34** [googleapis/python-bigquery#1418]
I'm using bigquery magic command `%%bigquery` in Colaboratory.
And I face the error as in the title.

Here are the details.

#### Environment details

  - OS type and version: Google Colaboratory
  - Python version: Python 3.7.15
  - pip version: pip 21.1.3 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)
  - `google-cloud-bigquery` version: 
    - Name: google-cloud-bigquery
    - Version: 3.3.6
    - Summary: Google BigQuery API client library
    - Home-page: https://github.com/googleapis/python-bigquery
    - Author: Google LLC
    - Author-email: [googleapis-packages@google.com](mailto:googleapis-packages@google.com)
    - License: Apache 2.0
    - Location: /usr/local/lib/python3.7/dist-packages
    - Requires: grpcio, google-cloud-bigquery-storage, packaging, pyarrow, requests, python-dateutil, google-cloud-core, google-api-core, protobuf, google-resumable-media, proto-plus
    - Required-by: pandas-gbq

#### Steps to reproduce

  1. Run bigquery magic command with `params` containing value 0

#### Code example

```python
from google.colab import auth
auth.authenticate_user()

params = {
    'hoge': 0,
}
```

↓ Next cell

```python
%%bigquery df_name --project PROJECT_NAME --params $params
select * from `PROJECT_NAME.DATASET_NAME.TABLE_NAME`
```

#### Stack trace
```
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File ["<ipython-input-12-8225e9e9eb24>"](https://localhost:8080/#), line 1, in <module>
    get_ipython().run_cell_magic('bigquery', "df_name --project PROJECT_NAME --params {'hoge': 0}", 'select * from `PROJECT_NAME.DATASET_NAME.TABLE_NAME`\n')

  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2359, in run_cell_magic
    result = fn(*args, **kwargs)

  File "/usr/local/lib/python3.7/dist-packages/google/cloud/bigquery/magics/magics.py", line 532, in _cell_magic
    raise rebranded_error from exc

  File "<string>", line unknown
SyntaxError: --params is not a correctly formatted JSON string or a JSON serializable dictionary
```

Note:
The line starts with the following sentences are re-written (esp. "PROJECT_NAME" etc)
```  File ["<ipython-input-12-8225e9e9eb24>"].....```

**Comment by gveltri** [comment]
@galz10 This solution seems incomplete--how do we pass variables to the bigquery cell magic without tripping up this syntax error? In your solution, you copied the value of the param into the cell magic line, but the purpose of the parameter is to not have to repeatedly copy the same lines of code to multiple cells.

**Comment by marvindao2024** [comment]
Hi. I'm encountering the same issue. What if we have a very long params? Also it was working for me then adding 2 more key,value pairs into it broke it

**Comment by andresbolsiyo** [comment]
I am facing the same issue. QueryParamsParseError: Expected token type LCURL, but found @paramsvar at position 44.
%%bigquery results --project bolsiyoanalytics --params @paramsvar
