### ISSUE TITLE
Support for Dataflow SQL

### ISSUE THREAD

**Issue by yiga2** [googleapis/python-bigquery#142]
I understand the Dataflow SDK is maintained elsewhere but "`Dataflow SQL`" is supported through BigQuery console/UI so this makes it hybrid hence my question here. 

I would love to query pubsub, save and export results directly from the same "bigquery engine" library. Any chance this will happen ?

Today, paradoxically, what is convenient interactively requires much more effort programmatically: learn `Apache Beam` SDK, provision DF server and start a bq stream job, kill all when done, and then only query in `BigQuery`.

**Comment by plamut** [comment]
@yiga2 I will check with the Product and the plans for Q3. (cc: @shollyman )

**Comment by shollyman** [comment]
We don't currently have plans to support this kind of interaction pattern from the bigquery library, but as both products continue to evolve and mature such a thing may make more sense.

The next closest thing I could suggest is to take a look at some of the published [dataflow templates](https://github.com/GoogleCloudPlatform/DataflowTemplates).  They do the heavily lifting of integrating disparate sources and sinks, and then simplify them down to parameterized invocations.  That said, the templates are largely based on the java SDKs so this may be of limited value for you.

**Comment by yiga2** [comment]
Closing this as not planned for yet - ideally, at some point, I would love through a client library, the UI console or the `bq` CLI to query pubsub, create tables, materialized views,... all from one single SQL script. Today this requires addressing each separately.
