### ISSUE TITLE
BQ: New transient errors to retry

### ISSUE THREAD

**Issue by yan-hic** [googleapis/python-bigquery#1428]
With the addition of BigQuery remote functions, please consider adding 2 more use cases of retriable transient errors in
https://github.com/googleapis/google-cloud-python/blob/56accfae54b2accdc5ccbe1d8ac0242210b3e811/bigquery/google/cloud/bigquery/retry.py#L19-L21

See details  [here ](https://issuetracker.google.com/issues/257110112)(+ BQ engineering team to catch other/new errors)

**Comment by chalmerlowe** [comment]
Due to limitations on staffing and workload, closing as will not fix.
