### ISSUE TITLE
Allow/relax upper bound on `packaging` dependency

### ISSUE THREAD

**Issue by miketheman** [googleapis/python-bigquery#1435]
The current requirement on `packaging` is pinned:
https://github.com/googleapis/python-bigquery/blob/e1aa9218ad22f85c9a6cab8b61d013779376a582/setup.py#L43

With the [release of `packaging` 22.0](https://github.com/pypa/packaging/releases/tag/22.0), clients using the current release of this project cannot update and benefit from the released version (which removes the last dependency of pyparsing).

The upper boundary was pinned in https://github.com/googleapis/python-bigquery/pull/1263 - my suggestion would be to remove said upper boundary and release a new version of the library, so that clients have the flexibility to update packages with fewer conflicts.

**Comment by tswast** [comment]
@parthea @chalmerlowe @aribray Thoughts on this one? Seems like the `packaging` dependency matches our criteria in go/python-client-dependency-management#removing-some-upper-bounds, though perhaps we'd want to make sure we install a prerelease/nightly/git version of the package to catch issues early?

**Comment by parthea** [comment]
@tswast Could we drop `packaging` instead? We're no longer using it in other repositories

**Comment by tswast** [comment]
No, we cannot. We use it to compare versions of optional dependencies in this package.

**Comment by parthea** [comment]
If we want to keep the dependency on packaging then I think it's ok to remove the upper bound. I'd recommend trying to remove packaging as a dependency altogether since it's trivial to achieve the same behaviour with our own logic. In other words, we could write code to extract the versions with tests to confirm the behavior. WDYT?

**Comment by di** [comment]
This seems to be resolved by #1440 and the recent 3.4.2, should it be closed?
