### ISSUE TITLE
from google.cloud import bigquery ModuleNotFoundError: No module named ‘db_dtypes’ 

### ISSUE THREAD

**Issue by CaioSouzaVoltz** [googleapis/python-bigquery#1437]
I already ran pip install --upgrade google-cloud-bigquery

When running my app I'm getting:

Traceback (most recent call last):
from google.cloud import bigquery
ModuleNotFoundError: No module named ‘ db_dtypes’

Additional details below:
current_bq_orders_df = client.query(current_bq_orders).to_dataframe()
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/google/cloud/bigquery/_pandas_helpers.py in <module>
     35 try:
---> 36     import db_dtypes  # type: ignore
     37 

ModuleNotFoundError: No module named 'db_dtypes'

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
/tmp/ipykernel_159/3901186559.py in <module>
     10 client = bigquery.Client(credentials=credentials)
     11 
---> 12 current_bq_orders_df = client.query(current_bq_orders).to_dataframe()

/opt/conda/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py in to_dataframe(self, bqstorage_client, dtypes, progress_bar_type, create_bqstorage_client, max_results, geography_as_object)
   1687             progress_bar_type=progress_bar_type,
   1688             create_bqstorage_client=create_bqstorage_client,
-> 1689             geography_as_object=geography_as_object,
   1690         )
   1691 

/opt/conda/lib/python3.7/site-packages/google/cloud/bigquery/table.py in to_dataframe(self, bqstorage_client, dtypes, progress_bar_type, create_bqstorage_client, geography_as_object)
   1964 
   1965         """
-> 1966         _pandas_helpers.verify_pandas_imports()
   1967 
   1968         if geography_as_object and shapely is None:

/opt/conda/lib/python3.7/site-packages/google/cloud/bigquery/_pandas_helpers.py in verify_pandas_imports()
    983         raise ValueError(_NO_PANDAS_ERROR) from pandas_import_exception
    984     if db_dtypes is None:
--> 985         raise ValueError(_NO_DB_TYPES_ERROR) from db_dtypes_import_exception

ValueError: Please install the 'db-dtypes' package to use this function.

**Comment by tswast** [comment]
Thanks for the report! `pip install db-dtypes` (also available via `conda/mamba`) should resolve your issue. We require this package when pandas is also used.

**Comment by tswast** [comment]
To install all optional dependencies, try: `pip install --upgrade 'google-cloud-bigquery[all]'`.

**Comment by CaioSouzaVoltz** [comment]
Hello, thanks for your help! But it still doesn't work, the problem I have is when I schedule it to run it presents this error, I have some other ETLs that use practically the same code and they do not present these errors. Wh

**Comment by rehmjohannes** [comment]
Hi all, did you find a way to manage it? I also got error messages while using the code below within a scheduled Jupyter notebook running on GCP: 

Code: 
client = bigquery.Client(credentials=credentials)
query = """ ... """
job = client.query(query)
df = job.to_dataframe()

Error:
ModuleNotFoundError: No module named 'db_dtypes'
ValueError: Please install the 'db-dtypes' package to use this function.

I have tried to pip install db_dtypes and all different versions of google-cloud-bigquery without any positive result. 

Thanks for your help

**Comment by tswast** [comment]
@rehmjohannes What are you using to schedule your Jupyter notebooks?

**Comment by barbarbay** [comment]
Hi, I had the same error and installing db-dtypes did not help. However, what did help was changing pandas version. Specifically, I switched from pandas==1.4.0 to pandas==1.2.4.

**Comment by meredithslota** [comment]
@barbarbay If there's a conflict with pandas versions, please file an issue here: https://github.com/googleapis/python-db-dtypes-pandas/issues I'm going to close this as it seems like the original issue was resolved in https://github.com/googleapis/python-bigquery/issues/1437#issuecomment-1372154225 Thanks!
