### ISSUE TITLE
Missing return types in some methods on cloud.google.com documentation

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#1438]
Note that `schema_from_json` returns a list of SchemaField objects, but there's no indication of that here: https://cloud.google.com/python/docs/reference/bigquery/latest/google.cloud.bigquery.client.Client#google_cloud_bigquery_client_Client_schema_to_json

**Comment by leahecole** [comment]
Just a note with some investigation - it does seem like these are generated from the docstrings via Cloud RAD and I did see a few methods where there was info in the docstring that doesn't seem to have been published to the docs. I'm looking into a republish now
