### ISSUE TITLE
Please add tests for the BigQuery v1 branch

### ISSUE THREAD

**Issue by parthea** [googleapis/python-bigquery#1443]
There is an issue reported that `google-api-core` version 2.11 breaks compatibility with the `google-cloud-bigquery` v1 branch. See https://github.com/googleapis/python-api-core/issues/477 . Creating an issue to enable tests for the v1 branch if possible.

**Comment by tswast** [comment]
What does this involve? Pointing Kokoro at the `v1` branch from google3? Will flakeybot monitor?

**Comment by meredithslota** [comment]
Question: how long do we need to maintain the v1 branch? cc: @brijk7
