### ISSUE TITLE
Grant access to bigquery table sample code

### ISSUE THREAD

**Issue by nonokangwei** [googleapis/python-bigquery#1449]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
in https://cloud.google.com/bigquery/docs/control-access-to-resources-iam#grant_access_to_a_table_or_view, there has no sample code for python to grant access on table or view
 **Describe the solution you'd like**
give the grant access on table or view python simple code
 **Describe alternatives you've considered**
customer need do coding by complex documentation.
 **Additional context**
n/a

**Comment by meredithslota** [comment]
There are code samples for granting view access here: https://cloud.google.com/bigquery/docs/samples/bigquery-grant-view-access and this is integrated into our documentation on this page: https://cloud.google.com/bigquery/docs/authorized-views but I agree it's missing on the page you linked. A companion sample on revoking access to a dataset is here: https://cloud.google.com/bigquery/docs/samples/bigquery-revoke-dataset-access and is integrated into the docs here: https://cloud.google.com/bigquery/docs/control-access-to-resources-iam Granting access to a dataset is also covered on that page and has a Python sample.
