### ISSUE TITLE
Experiencing low performance in google-cloud-bigquery to_dataframe method

### ISSUE THREAD

**Issue by icaroncruz** [googleapis/python-bigquery#1492]
Hello.

I'm using Vertex AI Workbench Managed Notebook that has recently been upgraded to the latest version (M104 Release - based on this documentation: https://cloud.google.com/vertex-ai/docs/release-notes). After the upgrade, I've experienced low performance when executing the bigquery's to_dataframe() method in my jupyterlab environment. 

`df = client.query(query).to_dataframe()`

I've performed 2 tests with the same database query (almost 3 Gb of data).
google-cloud-bigquery version 3.4.2 -> Wall time 56 min
![image](https://user-images.githubusercontent.com/110697106/218157875-554b2a02-02c0-47a9-b139-2dbd02611184.png)
google-cloud-bigquery version 3.3.1 -> Wall time 29 sec
![image](https://user-images.githubusercontent.com/110697106/218157924-44b218b5-138c-4994-be02-f255b6d0ac0b.png)

There's a huge difference in the wall time between those two versions. Version 3.3.1 is not the previous version from 3.4.2, but I chose this one because it was the version I was sure the performance was ok.

#### Environment details

  - OS type and version: `Vertex AI Workbench Managed Notebook (M104 Release)`
  - Python version: `3.7.12`
  - pip version: `22.3.1`
  - `google-cloud-bigquery` version: `3.4.2`

#### Steps to reproduce

  1. Check wall time with a query on a relatively large table (1 Gb +) using the BQ's to_dataframe() method on version 3.4.2
  2. Install google-cloud-bigquery version 3.3.1 
  3. Check wall time with a query on a relatively large table (1 Gb +) using the BQ's to_dataframe() method on version 3.3.1

#### Code example

```python
# example
query = "<some query on relatively large table (1 Gb +)>"
df = client.query(query).to_dataframe()
```

Thanks!

**Comment by tswast** [comment]
Note: the conda-forge package for google-cloud-bigquery has all extras installed by default. There you need to use google-cloud-bigquery-core to avoid these extras.

**Comment by icaroncruz** [comment]
Thank you Tim. 
Installing the "extras" solved the problem.
The only thing is that bigquery's package upgrade to version 3.4.2 was part of Vertex AI Workbench Managed Notebook M104 release upgrade, so I suppose those extra packages should have been installed along with the workbench upgrade.
I supposed I'd have to open a request specificly to Vertex AI team in order to have that addressed on new releases of Managed Notebooks

**Comment by dylanvanw** [comment]
For someone that found this issue looking for a solution for the same problem but when the above solution did not work...

In my case I had performance issues too when I mistakenly create a notebook instance in a different region than bigquery was located. This also caused low performance.

**Comment by chalmerlowe** [comment]
I am gonna close this issue as the workaround provided by Tim appears to have solved the original posted problem.

@dylanvanw If you are still having the same problem, please open a new ticket and provide details as requested in the Issue Ticket.
