### ISSUE TITLE
Syntax changes documentation

### ISSUE THREAD

**Issue by michelle-carou** [googleapis/python-bigquery#1498]
Not sure where to put this, but I want to comment that I spent days trying to figure out why I can't save my bigquery output to df. It's because of this [change](https://github.com/googlecolab/colabtools/issues/3248) in magic command syntax which was undocumented, can't find it anywhere online.

Is there any proper documentation of updates so that users like me are aware and know what the right syntax to use should be?

**Comment by meredithslota** [comment]
Hi @michelle-carou — thanks for filing an issue. As you noted, the Colaboratory Team upgraded the underlying BigQuery library they use (google-cloud-bigquery from 1.21.0 to 3.3.5). That large of an upgrade encompassed two sets of major version bumps and a number of breaking changes. You can find all the changes related to `magic` by searching our release notes here: https://github.com/googleapis/python-bigquery/releases?q=magic&expanded=true and you can review ALL the differences by comparing between those versions here: https://github.com/googleapis/python-bigquery/compare/v1.21.0...v3.3.5. You can also follow the official release notes here: https://cloud.google.com/bigquery/docs/release-notes (look for the "Libraries" tag) although that includes release notes across multiple BigQuery clients, not just this one — those notes include the release notes that are published in this repo, so if you are concerned with this library specifically, it may be more efficient to look through our releases here: https://github.com/googleapis/python-bigquery/releases Thanks!
