### ISSUE TITLE
Use compression in LoadJobConfig

### ISSUE THREAD

**Issue by omerda123** [googleapis/python-bigquery#1499]
I updated bigquery python client from version 1.27.2 to 2.34.3.
I used SNAPPY compression for LoadJobs and after the upgrade I'm getting this error message:
`Property compression is unknown for <class 'google.cloud.bigquery.job.load.LoadJobConfig'>`
according to this doc: https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#JobConfigurationLoad compression is supported.
Can I get some clarification here? There is any kind of compression? it's not longer supported? Didn't find any release notes / changelogs 

Thanks!

**Comment by skudrow-figure** [comment]
Had the same issue. Ended up not specifying the compression at all and it successfully loaded my json.gz file

**Comment by meredithslota** [comment]
The last change here was, I think, https://github.com/googleapis/python-bigquery/pull/361 which refactored but didn't remove compression support (and the previous paths are still supported, as far as I know though I haven't investigated it deeply yet). This was in November 2020, which would have roughly corresponded to v2.3.0 — and any future versions. 

SNAPPY compression is supported for Avro files only. Can you share an example of how you're using this?

https://github.com/googleapis/python-bigquery/blob/main/google/cloud/bigquery/enums.py for reference.
