### ISSUE TITLE
job_config.autodetect = True masks/ignores job_config.ignore_unknown_values = False

### ISSUE THREAD

**Issue by tpcgold** [googleapis/python-bigquery#1517]
### Issue:
`job_config.autodetect = True` does actually mask or ignore the setting of ` job_config.ignore_unknown_values`. This leads to the issue that **no error is triggered** when new / more fields are uploaded than defined in the schema. 
As soon as one is using `job_config.autodetect = False`  everything works as expected and an error is thrown on new/non-matching fields.

### System:
OS type and version: Windows 11
Python version: 3.10
pip version: 23.0.1
google-cloud-bigquery version: 3.6.0

### Steps to reproduce:
Create table
Upload dataframe or json (doesn't matter) with new field
and use the job config:

```
bqschema = client.get_table(table).schema
job_config = bigquery.LoadJobConfig(schema=bqschema)
job_config.autodetect = True
job_config.ignore_unknown_values = False
```

**Comment by shollyman** [comment]
This isn't really a behavior controlled by the library, but a behavior of the service itself.  The python library is really only propagating the values specified into the request in this instance, and there's not a lot we can do.

One of the options in https://cloud.google.com/bigquery/docs/getting-support such as customer care or the public issue tracker may be a better avenue for requesting a different set of behaviors from the service that more closely maps to your requirements.
