### ISSUE TITLE
[Bug?] Japanese character "、" is converted to comma "," when using `load_table_from_uri` function.

### ISSUE THREAD

**Issue by Z-zia** [googleapis/python-bigquery#1532]
#### Environment details

  - execution environment: CloudFunctions
  - pip version: `23.0.1`
  - `google-cloud-bigquery` version: latest as of 2023-3-25

#### Overview

I was trying to batch-import CSV files into BigQuery with the `bigquery.SourceFormat.CSV` setting and noticed one comma too many in certain data.  
I couldn't determine whether the problem was on the BigQuery side or the python-bigquery side, so I asked this question here.  

#### Steps to reproduce

  1. Upload CSV files to GCS
  2. Executed by CloudScheduler

#### Code example

```python
import os
from google.cloud import bigquery, storage

def get_table_name(blob, prefix):
  # omitting

def example_function(request):
  # debug
  project_id = os.environ['PROJECT_ID']
  dataset_id = os.environ['DATASET_ID']
  bucket_name = os.environ['BUCKET_NAME']
  prefix = 'test-prefix/'

  storage_client = storage.Client()
  bucket = storage_client.get_bucket(bucket_name)

  bigquery_client = bigquery.Client(project=project_id)
  dataset_ref = bigquery_client.dataset(dataset_id)

  blobs = bucket.list_blobs(prefix=prefix)
  for blob in blobs:
    if not blob.name.endswith('.csv'):
      continue
    table_name = get_table_name(blob, prefix)
    table_ref = dataset_ref.table(table_name)

    job_config = bigquery.LoadJobConfig()
    job_config.source_format = bigquery.SourceFormat.CSV
    job_config.field_delimiter = ','
    job_config.quote_character = '"'
    job_config.encoding = 'UTF-8'
    job_config.null_marker = ""
    job_config.skip_leading_rows = 1
    job_config.allow_quoted_newlines = True
    job_config.autodetect = True

    job = bigquery_client.load_table_from_uri(
      f"gs://{bucket_name}/{blob.name}", table_ref, job_config=job_config
    )
    job.result()
```

#### Stack trace

Raw CSV data (excerpt)  
`,,7月下旬提出日は一、二時間延ばすことも可能です?‍♀️,123,`  
  
Behavior on import (imaginary) `、` -> `,`  
`,,7月下旬提出日は一,二時間延ばすことも可能です?‍♀️,123,`  
  
Because there is one comma too many, the value is set in an unintended column, resulting in an error.  
  
in CloudFunctions log  
```
<JOB-NAME>vdp942vrfzqs Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request rv = self.dispatch_request() File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/layers/google.python.pip/pip/lib/python3.10/site-packages/functions_framework/__init__.py", line 99, in view_func return function(request._get_current_object()) File "/workspace/main.py", line 62, in <Function-NAME> job.result() File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py", line 728, in result return super(_AsyncJob, self).result(timeout=timeout, **kwargs) File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/api_core/future/polling.py", line 261, in result raise self._exception google.api_core.exceptions.BadRequest: 400 Provided Schema does not match Table <Project-NAME>:<Dataset>.<Table-NAME>. Field <INT-COLUMN> has changed type from INTEGER to STRING
```

**Comment by Z-zia** [comment]
I don't know if this is related, but the same thing happens with the spreadsheets.

![image](https://user-images.githubusercontent.com/58901619/227641602-c9f7fb1c-28f1-43fa-8437-84fc1a883387.png)
![image](https://user-images.githubusercontent.com/58901619/227642200-04fbd73f-bca6-492f-9bbb-999f4f2ccf5e.png)

**Comment by shollyman** [comment]
At a quick glance I don't see anything that implicates the library; you're running load jobs on CSV files already present in Cloud Storage, which precludes the library doing any kind of file processing.  Almost everything here is behavior within the service itself.

I'd recommend exploring one of the [support options]https://cloud.google.com/bigquery/docs/getting-support) for this one.  It will likely be useful if you can provide an example file that demonstrates this issue.
