### ISSUE TITLE
BigLake External Tables

### ISSUE THREAD

**Issue by AdeelK93** [googleapis/python-bigquery#1539]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
It would be neat to support [BigLake external table creation](https://cloud.google.com/bigquery/docs/create-cloud-storage-table-biglake) via this library
 **Describe the solution you'd like**
Support the `with connection` and additional options, maybe as a part of `bigquery.ExternalConfig` options
 **Describe alternatives you've considered**
Could always write DDL, that's fine, but the python interface in the rest of the library is easier to work with
 **Additional context**
N/A

**Comment by meredithslota** [comment]
The Python client library for BigLake is available here: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-bigquery-biglake but I've noted the feature request to be able to do it from this library.

**Comment by AdeelK93** [comment]
Hi @meredithslota, where can I find documentation on what that package does? I tried clicking a few links in there, couldn't find anything resembling documentation/guides/code samples

**Comment by meredithslota** [comment]
Client library documentation: https://cloud.google.com/python/docs/reference/biglake/latest (linked from library README)
Code samples: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-bigquery-biglake/samples/generated_samples (in sub-folder with the library code, but not linked from README, we should probably make this easier to find, oops)
Product-level documentation: [https://cloud.google.com/bigquery/docs/iceberg-tables#create-using-biglake-metastore (somewhat limited as this is a new product in preview, but expanding)](https://cloud.google.com/bigquery/docs/biglake-intro)

**Comment by AdeelK93** [comment]
Hi Meredith, thanks for sharing those links. I can't figure out how to create a biglake table in python using those. The first one just tells you how to use pip, the second one has a ton of what looks like procedurally generated code but no commentary or explanations, and the third one makes no reference to any python code.

**Comment by meredithslota** [comment]
Sorry, I linked to the parent of the library documentation — for creating tables, here's the specific page: https://cloud.google.com/python/docs/reference/biglake/latest/google.cloud.bigquery.biglake_v1.types.CreateTableRequest

**Comment by Guaytiew** [comment]
> Sorry, I linked to the parent of the library documentation — for creating tables, here's the specific page: https://cloud.google.com/python/docs/reference/biglake/latest/google.cloud.bigquery.biglake_v1.types.CreateTableRequest

please help I can't found any other samples 
I used table_id from bigquery's my table info 
create_table_request = bigquery_biglake_v1.CreateTableRequest(
        parent="projects/dudledood-sql-project-1/locations/us/catalogs/iceberg_catalog/databases/iceberg_warehouse",
        table_id="dudledood-sql-project-1.mosquito.config",
      )
      
but what's wrong with my table_id, why I got the errors: 
google.api_core.exceptions.InvalidArgument: 400 Table ID "dudledood-sql-project-1.mosquito.config" is invalid; Table ID should only contain unicode chars in category L (letter), M (mark), N (number), Pc (connector, including underscore), Pd (dash), Zs (space).
