### ISSUE TITLE
.to_geodataframe() method is not working for bq client query

### ISSUE THREAD

**Issue by OlegPryp** [googleapis/python-bigquery#1544]
I am trying to use . to_geodataframe() method for the geo data frame return from the big query query. Although the geopandas installed, i can't get the geodataframe directly from the query. 
The workaround is to get query response as pandas data frame and then convert it, but it is expected for the .to_geodataframe() to work.

![image](https://user-images.githubusercontent.com/84762973/229966890-2236cf22-4969-45b8-a509-27693a9425cc.png)

#### Environment details

  - OS type and version: Managed VM in Vertex AI. Juppyter environment
  - Python version: `python --version` 3.7.12
  - pip version: `pip --version` 23.0.1
  - `google-cloud-bigquery` version: `pip show google-cloud-bigquery` 3.5.0

#### Steps to reproduce

  1. pip install and activate bigquery and geopandas and pandas
  2. read the table from the bigquery and use the  .to_geodataframe() method

#### Code example

```python
import geopandas as gpd
from google.cloud import bigquery
import pandas as pd
import geopandas as gpd
sql_query='select * from `my_table_in_my_project`
df = bigquery.Client().query(sql_query).to_geodataframe()
```
I am recieving this error:
![image](https://user-images.githubusercontent.com/84762973/229968072-dfdce366-093b-4f38-b0a9-b78c450a40a1.png)

```
I  think this link has the same issue
https://stackoverflow.com/questions/70928172/bigquery-cannot-find-geopandas

```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by meredithslota** [comment]
If the error is that the geopandas library is not installed, I recommend following the steps in the Stackoverflow post, or the instructions here: https://geopandas.org/en/stable/getting_started/install.html and ensuring that all your libraries are installed in the right location.

**Comment by chalmerlowe** [comment]
Gonna close this as will not fix. A solution has been suggested by Meredith and no additional comments have surfaced.
