### ISSUE TITLE
Expose remote functions options as first class properties

### ISSUE THREAD

**Issue by shobsi** [googleapis/python-bigquery#1552]
Right now if I want to access spec details for a bigquery remote function I have to use the hidden properties, e.g.

```python
        routines = bq_client.list_routines(f"{gcp_project_id}.{bq_dataset}")
        for routine in routines:
            rf_options = routine._properties.get("remoteFunctionOptions")
            if rf_options:
                http_endpoint = rf_options.get("endpoint")
                bq_connection = rf_options.get("connection")
```

which is not ideal and takes a bit of figuring out. It would be nice to have it exposed via first class properties, which can be used like

```python
        routines = bq_client.list_routines(f"{gcp_project_id}.{bq_dataset}")
        for routine in routines:
            rf_options = routine.remote_function_options
            if rf_options:
                http_endpoint = rf_options.endpoint
                bq_connection = rf_options.connection
```

**Comment by tswast** [comment]
This could be a really good starter project for my apprentices.

**Comment by tswast** [comment]
For reference, see the REST API description here: https://cloud.google.com/bigquery/docs/reference/rest/v2/routines#Routine.FIELDS.remote_function_options

**Comment by shollyman** [comment]
This was added as part of https://github.com/googleapis/python-bigquery/pull/1558 but the work was tracked on an internal issue.  Closing this external issue, apologies for missing it initially.
