### ISSUE TITLE
load_table_from_json() fails to marshal date/datetime objects

### ISSUE THREAD

**Issue by darwinyip** [googleapis/python-bigquery#156]
#### Environment details
  - Python version: 3.7
  - `google-cloud-bigquery` version: 1.25.0

#### Steps to reproduce

  1. Have dict with date/datetime field
  2. Insert it via `load_table_from_json()`

#### Code example

```python
from datetime import datetime

from google.cloud import bigquery
from google.cloud.bigquery import LoadJobConfig

table_name = 'data.foo'

data = [{
    'id': 1,
    'dt': datetime(year=2020, month=7, day=6, hour=5, minute=4, second=3)
}]

client = bigquery.Client()
config = LoadJobConfig()
config.autodetect = True
job = client.load_table_from_json(data, table_name, job_config=config)
job.result()

```

#### Stack trace
```
TypeError: Object of type datetime is not JSON serializable
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by HemangChothani** [comment]
@darwinyip Yes, it's not possible to pass date/datetime object because 'load_table_from_json' method directly convert data into `string` format so you need to pass date/datetime in a string format.  

example:

    data = [{                              
        'id': 1,                           
        'dt': "2008-09-10T04:05:22.123456Z"
    }]

**Comment by darwinyip** [comment]
Thanks @HemangChothani. Will bq's autodetect understand this is a Timestamp or will I need to pass in the schema?

**Comment by darwinyip** [comment]
Just tried and it did autodetect.
