### ISSUE TITLE
FR to return view derived metadata (referenced tables, datasets, etc)

### ISSUE THREAD

**Issue by marcinpz** [googleapis/python-bigquery#1561]
I am working on cloud function (in Python) that auto-authorizes updated BigQuery views.
Currently it seems there is no easy way to do that.
To authorize view in Python function currently I have to:
1. Obtain source tables datasets for the updated view (I have to parse view SQL or get this data from `INFORMATION_SCHEMA.VIEWS`)
2. Authorize the view in these source datasets.

It was nice if this functionality was already there in the library. I am thinking about functions like:
- `View.get_source_tables()-> List[Table]`
- `View.get_datasets()->List[DataSet]`
- `View.authorize_in_source_datasets() -> None`

So could you please add that functionality to this library?

**Comment by marcinpz** [comment]
https://issuetracker.google.com/issues/280974633

**Comment by shollyman** [comment]
Thanks for requesting this.  I'll go ahead and close out this (library) request for now.  If/when the functionality is exposed as part of the service, we'll pick it up then.
