### ISSUE TITLE
load_table_from_dataframe column values loaded as null to BQ if column name has spaces in it 

### ISSUE THREAD

**Issue by osmanamjad** [googleapis/python-bigquery#1566]
#### Environment details

  - OS type and version: Linux
  - Python version: 3.10.10
  - pip version: 22.3.1
  - `google-cloud-bigquery` version: 3.10.0

#### Steps to reproduce

  1. Create a Pandas dataframe with a column name that has a space in it. 
  2. Call `load_table_from_dataframe` on the pandas dataframe.
  3. Resulting BQ table does not have values for the column whose name had a space in it. 

#### Code example

```python
import pandas as pd
from google.cloud import bigquery

# Initialize a pandas DataFrame (Step 1)
data = {'Full Name': ['John', 'Alice', 'Bob'],
        'Age': [25, 30, 35],
        'City': ['New York', 'London', 'Paris']}
df = pd.DataFrame(data)

# Create a BigQuery client
client = bigquery.Client()

# Define the BigQuery dataset and table
dataset_id = 'your_dataset_id'
table_id = 'your_table_id'

# Load the DataFrame into BigQuery table (Step 2)
job_config = bigquery.LoadJobConfig()
job = client.load_table_from_dataframe(df, f"{dataset_id}.{table_id}", job_config=job_config)
job.result()  # Wait for the job to complete
```

The issue is specifically when the job config's source_format is not specified to CSV. I understand this means the source_format defaults to Parquet which does not support having spaces in column names. However, this is not obvious from the user's perspective so I am wondering if there should be some error if a column name has a space in it (or any other characters that are not supported).

**Comment by tswast** [comment]
Since spaces in column names are a new feature https://cloud.google.com/bigquery/docs/release-notes#March_22_2023 I'll mark this as a feature request.

Do we know if this is a limitation of the parquet format or the BigQuery parquet loader?
