### ISSUE TITLE
feat: add type hints to methods

### ISSUE THREAD

**Issue by darwinyip** [googleapis/python-bigquery#157]
Having typings in the library would help and saw that there is a PR opened for that. However, the documentation is somewhat lacking.

It is hard to tell what the methods return and are all the parameters while looking at the docs https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.client.Client.html

For example, in the tutorial: what is the difference between these 2 table objects created?
```
table = bigquery.Table(table_id, schema=schema)
table = client.create_table(table)  # Make an API request.
```

**Comment by HemangChothani** [comment]
@darwinyip Description of the following statements:

     table = bigquery.Table(table_id, schema=schema)   
    # This statement creates a table class object locally which you need pass to `create_table` method to create your table 

    table = client.create_table(table)
    # This statement sent a request to the server to create a table in BigQuery database and return the table object with it's properties and information

    Example:
    table.created   # it gives the datetime of table creation
    table.etag  # gives the Etag of table
    table.num_rows  # gives the number of rows in table
    table.full_table_id  # full id of table including project and dataset.

**Comment by HemangChothani** [comment]
@darwinyip Did above explanation helped you?

**Comment by darwinyip** [comment]
@HemangChothani Yes it did. Thank you. However main issue I am raising is the lack of documentation around it.

**Comment by HemangChothani** [comment]
@darwinyip Is you concern related to type hints,  types to method params

**Comment by HemangChothani** [comment]
Should i mention return type of all the public methods of all the classes?
