### ISSUE TITLE
`bq cp dataset1.table_name  dataset2.table_name`

### ISSUE THREAD

**Issue by gomrinal** [googleapis/python-bigquery#1575]
Sometimes, this command throws an error while copying. It looks like a permission issue but the error usually says 404 and this error
[BigQuery error in cp operation: Error processing job: Unexpected](https://stackoverflow.com/questions/28625548/bigquery-error-in-cp-operation-error-processing-job-unexpected-please-try-aga)

**Comment by gomrinal** [comment]
Looks like this issue arises when datasets are present in different regions. For example,

if copying from `US` to `us-central-1` or vice-versa. In this case, copying of dataset is from multi-regional to regional.

However, It looks like for copying datasets from one region to another. One needs to use `BQ Data transfer service`

**Comment by meredithslota** [comment]
I came across this: https://medium.com/google-cloud/how-to-copy-a-bigquery-dataset-from-one-region-to-another-8388d74da2ac that matches what you describe. Here's the official documentation on copying a dataset using BigQuery DTS: https://cloud.google.com/bigquery/docs/managing-datasets#copy_a_dataset

**Comment by meredithslota** [comment]
Regardless, the `bq` command is re: the BigQuery CLI, not this library, so closing this out. https://cloud.google.com/bigquery/docs/reference/bq-cli-reference
