### ISSUE TITLE
Include a hint that the user might need to supply a `location` if query retry fails with 404 to get the job after a `Conflict`

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#1584]
In https://github.com/googleapis/python-bigquery/blob/6efdce13cc3b25d37d22a856f2308daed569e637/google/cloud/bigquery/_job_helpers.py#L100 if we get a 404 error, then we are potentially in a situation where the user started a query but we failed to get the response, so we don't know what location it started in.

We can't really help the user in this case because retrying the query could mean inserting duplicate rows or worse, but we can help them for next time by asking them to supply an explicit location when running queries so that we can fetch the job metadata if this happens again.

**Comment by tswast** [comment]
To clarify, I suggest adding a separate except clause for `NotFound` *before* we catch the `GoogleAPIError` here:

https://github.com/googleapis/python-bigquery/blob/6efdce13cc3b25d37d22a856f2308daed569e637/google/cloud/bigquery/_job_helpers.py#L107

The body of that `except` clause should raise a [`NotFound` error](https://googleapis.dev/python/google-api-core/latest/exceptions.html#google.api_core.exceptions.NotFound) with an additional message encouraging the developer to explicitly add a `location` when they call `query`.

Something like the following:

```python
except NotFound as exc:
    raise NotFound(
        """The call to query() successfully created a job, but we couldn't get the job metadata. 
        It's possible this job was created in a different region/location. 
        Try setting the `location` parameter when calling `query()` so that the client library can fetch the job metadata.
        """
    ) from exc
```

**Comment by tswast** [comment]
I would also propose we update all of our code samples where we call `query` to explicitly include a `location` parameter because of this problem. The client library can't properly recover from a dropped `jobs.insert` response if we don't know the location the job was supposed to be in.

**Comment by meredithslota** [comment]
> Alternatively, per internal issue 285136859 comment 65, maybe we can extract the location from the conflict error?

I do not think we should try to parse the error message — that would likely be too fragile. I added more thoughts on the internal issue.

**Comment by meredithslota** [comment]
I'll note that our current approach in other libraries is to do _less_ custom error handling, instead preferring to rely on backend errors passed through, and to remove custom error handling as those backend errors become more actionable (work in progress). Is there an option to handle this better in the `python-api-core` library instead of customizing it here?

**Comment by chalmerlowe** [comment]
As per the discussion in internal issue 285136859 we should not be managing this particular issue at the client level. The issue (and associated warning) should be handled upstream.
