### ISSUE TITLE
In a very rare occassion client.insert_rows function inserts duplicate datapoints

### ISSUE THREAD

**Issue by klaucos** [googleapis/python-bigquery#1585]
#### Environment details

  - Ubuntu `23.04` (Docker/pod in GCP K8S):
  - Python version: `3.10.6`
  - pip version: `23.0.1+dfsg-1`
  - `google-cloud-bigquery` version: `3.10.0`

#### Steps to reproduce

We are running thousands of BigQuery fills per day. (Running in GCP K8S)
This bug occurs randomly and very rarely. Recently we became aware of it and tried to track down the cause. 
It seems that client.insert_rows and its retrying might be the culprit. (AFAIK retrying is not logging anything on retry)
We are running thousands of fills on some day but from checking our tables we found out that the bug occurred since 2019-02-05 and is occurring to this day. (So it's probably not version or OS dependent as that changed during that time) It looks like it occurs during the time of increased fill activity during some random BigQuery insert.

What happened: 

We can see in the logs that the log for inserting of rows is properly logged only once but the inserted rows are duplicated in a table.
We are using client.insert_rows with always defined row_ids for insert. 
From the logs we found out that the problematic inserts take very long time compared to normal inserts. We are logging the time it takes to insert the file and we can see that normal insert over similar data takes ~0.2s but that insert that gets duplicated takes 5-seconds. 
If I had to guess it's caused by retrying where on some rare occasions the insert gets retried but the both inserts get properly written into the BigQuery. (It's possible insert duplicates into BigQuery if I run self._call_api twice manually in insert_rows_json function even with defined row_ids)
Only single insert was logged in python at 2023-05-18T22:38:59.529812335Z however I can not find any logs for streaming insert in that time. Not sure if it's even logged somewhere.

It seems like this is some weird behavior of BigQuery either at python library level or on the BigQuery cloud side.
This problem means that we can not trust BigQuery insert_rows not to duplicate the rows on insert which is terrifying thought.

#### Code example

```python
# example
table = 'table_ref'
new_row_ids=('r8YZNhkG4UBpKRG2jytY', 'e3big1iR8PbgNMwEl0Lp', 'VjLqhhN2FNElFBhmWURa')
# Simplified row insert
new_rows = ({'value': 1427.5296, 'version': '278', 'start_timestamp': 1683309497, 'end_timestamp': 1684346298, 'ingest_timestamp': 1686671183, 'first_seen': 1684449527}, {'value': 1563.4848, 'version': '278', 'start_timestamp': 1683309497, 'end_timestamp': 1684346298, 'ingest_timestamp': 1686671183, 'first_seen': 1684449527}, {'value': 4282.5888, 'version': '278', 'start_timestamp': 1683309497, 'end_timestamp': 1684346298,  'ingest_timestamp': 1686671183})
# Weirdly the insert takes a long time when it creates a duplicate values
errors = client.insert_rows(table, new_rows, row_ids=new_row_ids)
# No errors are returned after filling the duplicate values
if errors:
   raise ValueError('some_error')
log_message = f'Inserted {len(new_rows)} rows into table %s'
```

#### Stack trace
```
No stack trace
```

**Comment by shollyman** [comment]
At best, the tabledata.insertAll API is capable of at-least-once semantics, which appears to be what you're describing here.

If you truly need exactly-once semantics for your insertions then this API (the insert_rows method) isn't the correct choice.  Consider the [write api](https://cloud.google.com/bigquery/docs/write-api) or a transactional ingestion like a load job.

**Comment by klaucos** [comment]
Thank you for the quick reply. 
I was not aware of at-least-once limitation. :/ 
This explains the behavior.
