### ISSUE TITLE
Comparaison between RangePartitioning objects seems to be incorrect.

### ISSUE THREAD

**Issue by francois-baptiste** [googleapis/python-bigquery#159]
Comparaison between RangePartitioning objects seems to be incorrect.

#### Environment details

  - `google-cloud-bigquery` version: `1.25.0`

#### Code example

```python
from google.cloud.bigquery import RangePartitioning

print(RangePartitioning(field='something') ==
      RangePartitioning(field='something'))
```
Code above returns `False`. I was expecting `True`.

**Comment by HemangChothani** [comment]
@francois-baptiste  The magic of the equality operator == happens in the __eq__() class method of the object. This is a magic class method that’s called whenever an instance of this class is compared against another object. If this method is not implemented in the class , then == compares the memory addresses of the two objects by default.

You can compare like: 

    print (repr(RangePartitioning(field='something')) ==  repr(RangePartitioning(field='something')))

**Comment by francois-baptiste** [comment]
Thank you @HemangChothani for the workaround. I think however that the eq() method should be implemented as the other class of the library.
