### ISSUE TITLE
add fetch_pandas_all() to dbapi cursor

### ISSUE THREAD

**Issue by mvashishtha** [googleapis/python-bigquery#1604]
**Is your feature request related to a problem? Please describe.**

The [dbapi Cursor](https://cloud.google.com/python/docs/reference/bigquery/latest/google.cloud.bigquery.dbapi.Cursor) has `fetchall()` to get all the results. To get query results as a pandas dataframe, I have to call [`to_dataframe`](https://cloud.google.com/python/docs/reference/bigquery/latest/google.cloud.bigquery.job.QueryJob#google_cloud_bigquery_job_QueryJob_to_dataframe) on the result of `client.query()`, as documented [here](https://cloud.google.com/bigquery/docs/samples/bigquery-query-results-dataframe), or use `read_sql` or `read_gbq`.

 **Describe the solution you'd like**
I want the dbapi to give me a way to fetch all results of a query as a pandas dataframe. That way, I can get the benefits of the dbapi, in particular having access to [result metadata](https://github.com/googleapis/python-bigquery/blob/130450a3a5d866d2d48ef0c396e9f37d22d0b1d5/google/cloud/bigquery/dbapi/cursor.py#L96), while also getting the result of the same query as a pandas dataframe.

 **Additional context**
Compare to the snowflake python connector, which implements DB API 2.0 and also includes `fetch_pandas_all()`: https://docs.snowflake.com/en/developer-guide/python-connector/python-connector-api#fetch_pandas_all

**Comment by mvashishtha** [comment]
Following the example of the code I linked that [gets metadata](https://github.com/googleapis/python-bigquery/blob/130450a3a5d866d2d48ef0c396e9f37d22d0b1d5/google/cloud/bigquery/dbapi/cursor.py#L219) in the cursor, I'm able to work around the lack of this feature by looking at `client.query()._query_results.schema` and then doing `to_dataframe()` on the query result. However, I think it would be better if the dbapi let me get a pandas dataframe.

**Comment by chalmerlowe** [comment]
@mvashishtha 

I suspect that there must be something I am not understanding.

Based on the [Download query results to DataFrame link](https://cloud.google.com/bigquery/docs/samples/bigquery-query-results-dataframe) you shared, it seems pretty straightforward to produce a dataframe using this method chain:

```
df = client.query(sql).to_dataframe()
```

What specifically are you looking for beyond this?

**Comment by mvashishtha** [comment]
> What specifically are you looking for beyond this?

I want to get a dataframe with the [dbapi cursor](https://cloud.google.com/python/docs/reference/bigquery/latest/google.cloud.bigquery.dbapi.Cursor), not with the bigquery [client object](https://cloud.google.com/python/docs/reference/bigquery/latest/google.cloud.bigquery.client.Client).

I explain my motivation in my [original comment](https://github.com/googleapis/python-bigquery/issues/1604#issue-1790477825).

**Comment by chalmerlowe** [comment]
Ok. I see what you want to achieve. Thanks.

Based on our current workload/available staff and based on the existence of available work arounds to get metadata and still be able to get a dataframe (albeit needing several steps to get there) I am not able to prioritize adding this new feature.

Closing this feature request as will not work.
