### ISSUE TITLE
_PARTITIONTIME is not returned in version 3.11.4 (is returned in 3.11.3)

### ISSUE THREAD

**Issue by SudhirNune** [googleapis/python-bigquery#1655]
_PARTITIONTIME is not returned in 3.11.4 Verion works till 3.11.3

#### Environment details

  - OS type and version: Windows & UNIX
  - Python version: Python 3.8.10
  - pip version: pip 23.2.1
  - `google-cloud-bigquery` version: 
Name: google-cloud-bigquery
Version: 3.11.3
Summary: Google BigQuery API client library
Home-page: https://github.com/googleapis/python-bigquery
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: c:\users\hrq1364\envs\khde\lib\site-packages
Requires: google-api-core, google-cloud-core, google-resumable-media, grpcio, packaging, proto-plus, protobuf, python-dateutil, requests
Required-by: dbt-bigquery, kh-de, pandas-gbq

#### Steps to reproduce

  1. Install Version: 3.11.3 of google-cloud-bigquery
  2. Import the Package
  3. Connect to the BQ with Service Account 
  4. Create Cursor
  5. Run the query (Using the Above) - 
```
SELECT export_time, pricing_as_of_time, product_taxonomy,
billing_account_id, business_entity_name, service, sku, geo_taxonomy,
pricing_unit, pricing_unit_description, account_currency_code,
currency_conversion_rate, list_price, billing_account_price, _PARTITIONTIME,
CAST(TIMESTAMP_TRUNC(export_time, DAY) AS DATE) AS export_date
FROM `billing-us-01.us_billing_data.cloud_pricing_export`
WHERE (_PARTITIONTIME > '2023-09-04 00:00:00')
```
  7. Output has the column "_PARTITIONTIME"
  8. Install Version: 3.11.4 of google-cloud-bigquery
  9. Import the Package
  10. Connect to the BQ with Service Account
  11. Create Cursor
  12. Run the query (Using the Above) - 
```
SELECT export_time, pricing_as_of_time, product_taxonomy,
billing_account_id, business_entity_name, service, sku, geo_taxonomy,
pricing_unit, pricing_unit_description, account_currency_code,
currency_conversion_rate, list_price, billing_account_price, _PARTITIONTIME,
CAST(TIMESTAMP_TRUNC(export_time, DAY) AS DATE) AS export_date
FROM `billing-us-01.us_billing_data.cloud_pricing_export`
WHERE (_PARTITIONTIME > '2023-09-04 00:00:00')
```
  14. Output Missing the column "_PARTITIONTIME"

Thanks!

**Comment by chalmerlowe** [comment]
I have not been able to recreate this error locally.
I ran analogous code on a partitioned table using both 3.11.3 and 3.11.4 and successfully returned results...

**Comment by chalmerlowe** [comment]
NOTE: [this linked issue](https://github.com/googleapis/python-bigquery/issues/1312) also discusses dropping `_PARTITIONTIME`, but does not appear to have any relationship to package version, the way this issue does.

**Comment by chalmerlowe** [comment]
Closing as not reproducible.
