### ISSUE TITLE
Moving data from GCS in account A to BigQuery in account B

### ISSUE THREAD

**Issue by nick-amplify** [googleapis/python-bigquery#1657]
Hello, this is a question and not a bug, but I would be really appreciative of some help since I have not been able to find something online yet. 

I am hoping to move data from an GCS bucket in account A to a Bigquery Table in account B. 

I have the respective creds for account a and account b, but I'm not sure how to get the code to see the separate creds. 

Here is a quick example of the code I'm using:

```python
from google.oauth2 import service_account
credentials = service_account.Credentials.from_service_account_info(
    info=my_creds
)

client = bigquery.Client(
    project="project_id", 
    credentials=credentials
)

job_config = bigquery.LoadJobConfig(
    autodetect=True, 
    write_disposition="WRITE_APPEND", 
)

gcs_path = f"gs://{bucket_name}/{path}"

client.load_table_from_uri(
    gcs_path, 
    f"{bq_project_id}.{pq_dataset}.{bq_table}", 
    job_config=job_config
).result()
```

I was hoping to be able to pass the GCS creds to either `LoadJobConfig` or `load_table_from_uri`, but I don't see those options available. 

Is there another way to do this? 

Thank you for any help!

**Comment by meredithslota** [comment]
This documentation page describes setting up repeatable transfers from GCS to BigQuery using BigQuery Data Transfer Service, so may not be fully applicable to your use case, but it does discuss the required permissions needed: https://cloud.google.com/bigquery/docs/cloud-storage-transfer#required_permissions
