### ISSUE TITLE
RE: issue #1612, advice for users

### ISSUE THREAD

**Issue by cmarkle85** [googleapis/python-bigquery#1660]
Regarding issue #1612, it appears resolved but as a user I don't know how to handle the error. Please advise.

**Comment by cmarkle85** [comment]
To anyone interested, I found defining the timeout argument resolves the issue:
`job.exception()` -> `job.exception(10000)`

**Comment by idan3** [comment]
Wasn't this fixed in version 3.12?

**Comment by chalmerlowe** [comment]
It should be fixed in 3.12.
