### ISSUE TITLE
Multi-statement transactions

### ISSUE THREAD

**Issue by victorviro** [googleapis/python-bigquery#1663]
Does it possible to use [multi-statement transactions in BigQuery](https://cloud.google.com/bigquery/docs/transactions) with this client?

**Comment by Linchin** [comment]
Hi @victorviro, thank you for your question. Yes, the Python BigQuery client supports multi-statement transactions. It is no different from a normal query. For example, you can use the [`client_query.py` sample](https://github.com/googleapis/python-bigquery/blob/54a77694afcd80be4ba469c6ebb7ca8be112b04e/samples/client_query.py), and replace the query string with [transaction query examples in the documentation](https://cloud.google.com/bigquery/docs/transactions).

Feel free to reopen the issue if you have any further question.
