### ISSUE TITLE
How to format date from Firestore in BigQuery

### ISSUE THREAD

**Issue by thawahsaw** [googleapis/python-bigquery#1686]
Im trying to display dates from Firestore Database in BigQuery.

Here is an example of my Firestore Document👇

[![Here is an example of my Firestore Document][1]][1]

I would like to display this timestamp, "f58-sodleDate", in BigQuery as 2023-10-3.

 
In BigQuery Console, I wrote this code 👇
```
json_extract(data, '$.f58-sodleDate'),
```
and I get this 👉 {"_seconds":1691471596,"_nanoseconds":483000000} 

And if I write this code, 👇
```
parse_datetime("%c", JSON_VALUE(DATA, '$.f58-sodleDate')) as dte,

// or this code

JSON_EXTRACT_SCALAR(DATA, '$.f58-sodleDate') AS dte,
```
I get the query result as null, like this👇

[![this query result][2]][2]

And if I write this code👇
```
date(timestamp_seconds(cast(json_extract(data, '$.f58-sodleDate') as int64))) AS dte,
```
I get this error message👇

[![error message][3]][3]

What I want for my query result is something like this👇
[![correct query result][4]][4]

I achieved this by writing this code 👇
```
FORMAT_DATE('%F', timestamp) as dte,
```
Please tell me what I have to do to achieve the result I want..

Thank you, best. - STW

  [1]: https://i.stack.imgur.com/Rp5R0.png
  [2]: https://i.stack.imgur.com/r2Ah4.png
  [3]: https://i.stack.imgur.com/fcFpu.png
  [4]: https://i.stack.imgur.com/ZEKXa.png

**Comment by Linchin** [comment]
Maybe you can go a level deeper to access the `._seconds` field? Like this:
```
select date(timestamp_seconds(cast(json_extract(data, '$.f58-sodleDate._seconds') as int64)))
```
I will close this issue for now, but if you have more questions, feel free to make more comments!
