### ISSUE TITLE
release 1.26.0

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#173]
Any chance we could get a release? I'd like #170 in a released version to support a tool I'm building on my current team.

**Comment by tswast** [comment]
Is https://github.com/googleapis/python-bigquery/pull/130 blocked on CI issues?

**Comment by plamut** [comment]
@tswast Samples checks have been added preemptively and will pass once #149 is done and merged.

I don't know the release schedule, but regularly releasing fixes makes sense to me. Perhaps we are waiting to also include a few PRs that are close to being done. @shollyman ?

**Comment by shollyman** [comment]
It largely comes down to getting those samples moved over, which is still in flight.  Do we want to gate the release on the samples changes?

Given we have clean separation of library and samples testing I'm okay with letting 1.26.0 get out with broken samples, but I don't know if anyone's expecting working sample targets as part of their own consumption.  I have no problem releasing more frequently, so let's not wait on more than we need to.

**Comment by shollyman** [comment]
Went ahead with the release in #130 to unblock the release while we finish sorting out the samples move.
