### ISSUE TITLE
dbapi: Skip storage client fetch when results cached

### ISSUE THREAD

**Issue by r1b** [googleapis/python-bigquery#1745]
**Is your feature request related to a problem? Please describe.**
This is the same problem as https://github.com/googleapis/python-bigquery/issues/589, but when using the DBAPI interface

 **Describe the solution you'd like**
We'd like the DBAPI interface to include the result fetching optimization added in https://github.com/googleapis/python-bigquery/pull/1723

This is mentioned in https://github.com/googleapis/python-bigquery/issues/362:

> Update DB-API to not call BQ Storage API if cached results are the only page

but wanted to be sure it was tracked :)

 **Describe alternatives you've considered**
N/A (we use BigQuery via SQLAlchemy, so we cannot use an alternative interface)

 **Additional context**
N/A

**Comment by tswast** [comment]
I did some benchmarking with my change https://github.com/googleapis/python-bigquery/pull/1747#issuecomment-1852368885 which is currently out for review. The summary is:

Small query results (e.g. SELECT 1) have a (1.18 / 0.319) = 3.7x speedup! For medium-sized results/queries, this optimization has less dramatic results at (1.67 / 1.63) = 1.2x speedup and not statistically significant.

**Comment by nickmarx12345678** [comment]
@tswast thanks for knocking this out!
