### ISSUE TITLE
Support JSON data type in `insert_rows` and as query parameters

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#1756]
We need to make sure the JSON data type is supported for `insert_rows`. I suspect it is broken for query parameters, too.

See: https://github.com/googleapis/python-bigquery/pull/1587#issuecomment-1855617976

**Comment by tswast** [comment]
I think we need to update:

https://github.com/googleapis/python-bigquery/blob/fdd580f2b603ca29f1ef52d094ebb8016d9bdc9d/google/cloud/bigquery/_helpers.py#L442

It should be `json_to_json` and `dumps` rather than `loads`.

**Comment by tswast** [comment]
Also, update our `insert_rows` and `query_parameters` system tests to use the JSON data type in some column.

**Comment by ekampf** [comment]
@tswast `_json_from_json` expects `value` and `field` but the code calling it in `_scalar_field_to_json` calls `converter(value)` which would always fail...

**Comment by tswast** [comment]
@ekampf You are correct. I fix this in https://github.com/googleapis/python-bigquery/pull/1757
