### ISSUE TITLE
Bigquery api authentication fails when using OIDC authentication in circleci

### ISSUE THREAD

**Issue by Kavinkumar07** [googleapis/python-bigquery#1772]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-bigquery/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: circleci
  - Python version: `python --version` 3.11.4
  - pip version: `pip --version`22.2.2
  - `google-cloud-bigquery` version: `pip show google-cloud-bigquery` 3.11.3

#### Steps to reproduce

  1. Use Circle ci orb gcp-cli and authenticate with GCP using OIDC authentication in python:3.11.4-bullseye image
  2. try to create table with bigquery api
  3. Even after the verification, The gcloud commands are running properly but the bigquery python package create table method fails with the message 
 'FileSystem: Failed to initialize fileystem gs://spark_artifacts_dev/.spark-bigquery-local-1705030367510-2bfc4bb9-b783-4516-afa0-c541d3666b45: java.io.IOException: Error reading credential file from environment variable GOOGLE_APPLICATION_CREDENTIALS, value '/root/gcp_cred_config.json': Error reading credentials from stream, 'type' value 'external_account' not recognized. Expecting 'authorized_user' or 'service_account''

#### Code example

```python
def create_table(project_id, dataset_id, table_name, schema):
    client = bigquery.Client()
    table_id = f"{project_id}.{dataset_id}.{table_name}"
    table = bigquery.Table(table_id, schema=schema)
    client.create_table(table)
```

#### Stack trace
```
test/integration/adapters/bigquery_test.py:53:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test/utils.py:85: in clean_up
    execute_query(drop_query)
test/utils.py:73: in execute_query
    client.query(query).result()
../.local/share/virtualenvs/repo-ryNHDDTx/lib/python3.11/site-packages/google/cloud/bigquery/job/query.py:1520: in result
    do_get_result()
../.local/share/virtualenvs/repo-ryNHDDTx/lib/python3.11/site-packages/google/api_core/retry.py:349: in retry_wrapped_func
    return retry_target(
../.local/share/virtualenvs/repo-ryNHDDTx/lib/python3.11/site-packages/google/api_core/retry.py:191: in retry_target
    return target()
../.local/share/virtualenvs/repo-ryNHDDTx/lib/python3.11/site-packages/google/cloud/bigquery/job/query.py:1510: in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
../.local/share/virtualenvs/repo-ryNHDDTx/lib/python3.11/site-packages/google/cloud/bigquery/job/base.py:922: in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by chalmerlowe** [comment]
@Kavinkumar07 
Thanks for generating this Issue.
In looking at the error message, it appears as though we are looking for a credentials file in the location:
`/root/gcp_cred_config.json`

Can you confirm that the credential file is actually stored in that location OR if you have it stored elsewhere, can you modify the environment variable: `GOOGLE_APPLICATION_CREDENTIALS` to point to the correct location?

**Comment by chalmerlowe** [comment]
No response. Gonna close this issue as will not fix. IF you are still having issues, please feel free to create a new issue and we can discuss.

**Comment by Kavinkumar07** [comment]
We have proper credential file. Since we are using OIDC authentication (not the usual service account key authentication) via circle ci, the credential has "type": "external_account". The error message also states the same issue.
