### ISSUE TITLE
Implement new client options

### ISSUE THREAD

**Issue by busunkim96** [googleapis/python-bigquery#178]
Add support for the three new client_options `quota_project_id`, `scopes`, and `credentials_file`.  

https://googleapis.dev/python/google-api-core/latest/client_options.html

**Comment by tseaver** [comment]
I believe this work is blocked on merge / release of googleapis/python-cloud-core#15

**Comment by tseaver** [comment]
PR needs to pin `google-cloud-core >= 1.4.0, < 2.0dev`.
