### ISSUE TITLE
DBAPI does not add tracing spans to additional page fetches

### ISSUE THREAD

**Issue by nickmarx12345678** [googleapis/python-bigquery#1791]
#### Environment details

  - OS type and version: `Darwin M-C02D404FMD6T 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64 x86_64`
  - Python version: `Python 3.11.3`
  - pip version: `pip 22.3.1
  - `google-cloud-bigquery` version: `Version: 3.15.0`

#### Steps to reproduce
I will try to add a self contained repro, but I'm newer to this library/python, so I will summarize in the meantime. 

We have been using the opentelemetry integration along with GCP Cloud Trace to reduce latency of an application using `python-bigquery` and have noticed when there is more than one page worth of results in a DB-API cursor, we will only see trace spans for the initial `bq.query` and `job.reload` calls, but not for the fetching of the additional pages, which leaves an unexplained gap in the trace timeline (see pic)

<img width="1481" alt="image" src="https://github.com/googleapis/python-bigquery/assets/2286257/8dcad8c5-0680-4a10-bbd0-0265b0bb41f3">

To reproduce, run a DB-API query with `array_size` https://github.com/googleapis/python-bigquery/blob/955a4cd99e21cbca1b2f9c1dc6aa3fd8070cd61f/google/cloud/bigquery/dbapi/cursor.py#L76 set to less than the output number of rows of the query, and opentelemetry tracing installed, and observe .

#### Code example

```python
cursor = execute(sql)
results = cursor.all()
```

subset of flame graph from my debugging. this segment of calls appears not to generate any tracing spans (despite using bigquery_storage_client)
![image](https://github.com/googleapis/python-bigquery/assets/2286257/898f9446-4cc2-47e5-8adc-312fb996a2b3)

Thanks!

**Comment by tswast** [comment]
There are two methods in which we download results: REST API (this client library) and BQ Storage Read API.

For REST API, it appears we need to add the span attributes in the following location:

https://github.com/googleapis/python-bigquery/blob/955a4cd99e21cbca1b2f9c1dc6aa3fd8070cd61f/google/cloud/bigquery/client.py#L3943

For the BQ Storage API, please file a feature request for opentelemetry support in our gRPC clients here: https://github.com/googleapis/gapic-generator-python/issues?q=is%3Aissue+is%3Aopen+

**Comment by nickmarx12345678** [comment]
Done! https://github.com/googleapis/gapic-generator-python/issues/1910

Thanks @tswast
