### ISSUE TITLE
Enable to add labels to a destination table with query

### ISSUE THREAD

**Issue by yu-iskw** [googleapis/python-bigquery#1803]
**Is your feature request related to a problem? Please describe.**
Yes, I am experiencing an issue with the Python BigQuery SDK where labels cannot be added to a destination BigQuery table through a query. Currently, while it's possible to declare labels for a destination table, these labels are not being attached when the table is created as part of a query execution. The only workaround seems to be updating the table metadata independently after the table has been created, which is not ideal.

 **Describe the solution you'd like**
I would like the ability to add labels to a destination BigQuery table directly through a query in the Python BigQuery SDK. This enhancement would ideally allow the declaration of labels as part of the Table or QueryJobConfig object, which would then be reflected in the destination table upon the completion of the query.

 **Describe alternatives you've considered**
The current alternative is to manually update the table metadata to add labels after the table has been created. This requires an additional step and makes the process less efficient and more prone to errors or oversight.

 **Additional context**
Here's a snippet of the current code I am using, which does not result in labels being added to the destination table:

```python
table_ref = bigquery.TableReference(
    dataset_ref=dataset_ref,
    table_id='test_table_with_labels'
)
table = bigquery.Table(table_ref=table_ref)
table.labels = {
    "label1": "value1",
    "label2": "value2",
}

# Build job config
job_config = bigquery.QueryJobConfig()
job_config.destination = table
job_config.write_disposition = bigquery.WriteDisposition.WRITE_TRUNCATE
job_config.create_disposition = bigquery.CreateDisposition.CREATE_IF_NEEDED

# Query
query = """
SELECT 1 AS id, 'test' AS name
UNION ALL
SELECT 2 AS id, 'test2' AS name
"""
query_job = client.query(query, job_config=job_config)
query_job.result()
```

After executing this code, the destination table 'test_table_with_labels' is created, but the labels {"label1": "value1", "label2": "value2"} are not present on the table.

![image](https://github.com/googleapis/python-bigquery/assets/1523515/c11d59d0-bd39-497c-8fa6-d223c893e532)

Thank you for considering this enhancement.

**Comment by Linchin** [comment]
Thank you @yu-iskw for requesting this feature. I just checked the [job config message](https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#JobConfigurationQuery), and the field of destination table, `destinationTable` is a [`tableReference`](https://cloud.google.com/bigquery/docs/reference/rest/v2/TableReference) message which only has `projectId`, `datasetId` and `tableId`. To enable labels we would have to update the backend API. As there is a rather straightforward workaround, I will mark this issue as won't fix. If you think this feature is critical to you, feel free to add comments here, or open a new issue.

**Comment by agility-adamp** [comment]
@Linchin what is the simple workaround?
I create many tables and views with the python SDK and it isn't feasible to manually update them.

**Comment by Linchin** [comment]
Hi @agility-adamp, you can create the table with the labels first, and then start the query job with the table as the destination. Make sure you set `write_disposition=bigquery.WriteDisposition.WRITE_APPEND` in the job config, and it should work.
