### ISSUE TITLE
QueryJob class break flow after upgrade to 3.21.0

### ISSUE THREAD

**Issue by DLT1412** [googleapis/python-bigquery#1940]
Affect version: >=3.21.0, <=3.23.1

#### Steps to reproduce

``` python
from google.cloud import bigquery
import uuid

client = bigquery.Client()
from google.cloud.bigquery import QueryJob
QueryJob(job_id=str(uuid.uuid4()), query="select 1", client=client).result() # return 404 error, work with version 3.20.1
```

**Comment by tswast** [comment]
I suspect I broke this in https://github.com/googleapis/python-bigquery/pull/1900

As far as I know we never documented calling the `QueryJob` constructor directly, instead preferring folks call `Client.query()`, `Client.query_and_wait()` or `Client.insert_job()`.

I'm curious why you are calling the constructor directly?
