### ISSUE TITLE
write_disposition parameter has no option to only overwrite partitions and not the whole table

### ISSUE THREAD

**Issue by matthias-fbi** [googleapis/python-bigquery#1960]
Thanks for stopping by to let us know something could be better!

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Databricks 15.2.x-scala2.12
  - Python version: Python 3.11.0rc1
  - pip version: 23.2.1
  - google-cloud-bigquery version: 3.24.0

#### Steps to reproduce

1. create project in BQ
2. create dataset in the project
3. pip install polars
4. pip install google-cloud-bigquery

set the destination parameter in the code below and run it.

Since we partition our table by date, I would expect to only overwrite the partition so that data for each day is in the table.
But we get only the data for the last insert because it overwrites the whole table on each run
-> using the google-cloud-bigquery library with `client.load_table_from_file` does not preserve historical data but purges the whole table each time.

#### Code example

```
import polars as pl
from google.cloud import bigquery
from io import BytesIO
from datetime import date

period_range = pl.date_range(
    start=date(2024, 1, 1), end=date(2024, 1, 4), interval="1d", eager=True
)

df = pl.DataFrame(
    {
        "date": [
            date(2024, 1, 1),
            date(2024, 1, 2),
            date(2024, 1, 3),
            date(2024, 1, 4),
        ],
        "col_a": [1, 2, 3, 4],
        "col_b": ["a", "b", "c", "d"],
    }
)

client = bigquery.Client()

for day in period_range:
    temp = df.filter(pl.col("date").eq(day))
    print(day, temp.shape, temp.dtypes)
    
    with io.BytesIO() as stream:
        temp.write_parquet(stream)
        stream.seek(0)
        job = client.load_table_from_file(
            file_obj=stream,
            destination="project.schema.table",
            location="EU",
            job_config=bigquery.LoadJobConfig(
                source_format=bigquery.SourceFormat.PARQUET,
                time_partitioning=bigquery.TimePartitioning(
                    type_=bigquery.TimePartitioningType.DAY,
                    field="date",
                ),
                write_disposition=bigquery.WriteDisposition.WRITE_TRUNCATE,
            ),
        )
    job.result()  # Waits for the job to complete

print("finished")
```

**Comment by Linchin** [comment]
Hi @matthias-fbi, thanks for raising the issue! There is a way to only apply WriteDisposition to a specific partition. You just need to [add a partition decorator to your table id](https://cloud.google.com/bigquery/docs/partitioned-tables#partition_decorators). I will close the issue, but please let us know if you have any further questions :)
