### ISSUE TITLE
BigQuery: Rich editor features for Jupyter magic

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#20]
- [ ] automatic query validation
- [ ] automatic dryrun with price estimates
- [ ] syntax highlighting
- [ ] auto-complete

**Comment by tswast** [comment]
We might be able to fork https://github.com/GoogleCloudPlatform/jupyter-extensions to work in general JupyterLab environments. I think the `%%bigquery --editor` widget output is the most promising to include.

**Comment by chalmerlowe** [comment]
Closing as "Will not work" due to conflicting priorities at this time.
