### ISSUE TITLE
Select columns with `extract_table`?

### ISSUE THREAD

**Issue by ReubenFrankel** [googleapis/python-bigquery#2021]
Is it possible to select specific columns for export with [`extract_table`](https://cloud.google.com/python/docs/reference/bigquery/latest/google.cloud.bigquery.client.Client#google_cloud_bigquery_client_Client_extract_table) somehow? Or do I need to use [`query`](https://cloud.google.com/python/docs/reference/bigquery/latest/google.cloud.bigquery.client.Client#google_cloud_bigquery_client_Client_query) for that kind of additional functionality?

**Comment by peter-s-martin** [comment]
Try this alternate way to export the specific columns from the table rather than exporting entire table  

EXPORT DATA OPTIONS(
  uri='gs://bucket/folder/*.csv',
  format='CSV',
  overwrite=true,
  header=true,
  field_delimiter=';') AS
SELECT field1, field2 FROM mydataset.table1 ORDER BY field1 LIMIT 10

**Comment by ReubenFrankel** [comment]
> Try this alternate way to export the specific columns from the table rather than exporting entire table
> 
> EXPORT DATA OPTIONS( uri='gs://bucket/folder/*.csv', format='CSV', overwrite=true, header=true, field_delimiter=';') AS SELECT field1, field2 FROM mydataset.table1 ORDER BY field1 LIMIT 10

Thanks, I was aware that this is possible through `query`, but I want to be able to do this with `extract_table` where you can already specify export format, compression and more with the [`job_config`](https://cloud.google.com/python/docs/reference/bigquery/latest/google.cloud.bigquery.job.ExtractJobConfig) kwarg:

```py
# from google.cloud import bigquery
# client = bigquery.Client()
# bucket_name = 'my-bucket'

destination_uri = "gs://{}/{}".format(bucket_name, "shakespeare.csv.gz")
dataset_ref = bigquery.DatasetReference(project, dataset_id)
table_ref = dataset_ref.table("shakespeare")
job_config = bigquery.job.ExtractJobConfig()
job_config.compression = bigquery.Compression.GZIP

extract_job = client.extract_table(
    table_ref,
    destination_uri,
    # Location must match that of the source table.
    location="US",
    job_config=job_config,
)  # API request
extract_job.result()  # Waits for job to complete.
```

https://cloud.google.com/bigquery/docs/exporting-data#extract_compressed_table

**Comment by ReubenFrankel** [comment]
This question was more about whether there is a way to select columns for extract programmatically with `extract_table`, rather than provide the SQL to execute an extract job as a string to `query` (I was already aware of this as an alternative). In terms of DX, I prefer the interface `extract_table` provides and having an `ExtractJob` instance returned. Since you both directed me to the SQL approach, I'm gonna assume it's not possible with `extract_table` currently.

**Comment by Linchin** [comment]
Indeed, I don't think there's an option to specify columns directly in the ExtractJob API. It does feel like a useful feature, though. If you are interested in making it a feature, it would be helpful to file a feature request with customer support here: https://cloud.google.com/bigquery/docs/getting-support.
