### ISSUE TITLE
Add a property to get `allowNonIncrementalDefinition` from a materialized view

### ISSUE THREAD

**Issue by yu-iskw** [googleapis/python-bigquery#2083]
**Is your feature request related to a problem? Please describe.**
Currently, the `google-cloud-bigquery` Python package does not provide a getter and setter for the `allowNonIncrementalDefinition` property in the Materialized View Definition. This limitation makes it difficult to manage materialized views effectively, especially when users need to toggle this setting based on their requirements.

**Describe the solution you'd like**
I would like to see the addition of a getter and setter for the `allowNonIncrementalDefinition` property in the Materialized View Definition class. This would allow users to easily access and modify this property, enhancing the usability of the package.

**Describe alternatives you've considered**
As an alternative, users can manually modify the underlying API request payloads, but this approach is cumbersome and error-prone. Having a dedicated property in the Python client would streamline the process and improve code readability.

**Additional context**
For reference, you can find more information about the `allowNonIncrementalDefinition` property in the [BigQuery documentation](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#MaterializedViewDefinition).

**Comment by chalmerlowe** [comment]
Closed by PR #2084
