### ISSUE TITLE
1.27.2 broke BigQuery python

### ISSUE THREAD

**Issue by McPatate** [googleapis/python-bigquery#254]
Hello everyone,

We recently have been trying to use the newest version of the bigquery package, sadly there is a bug at object initialization.
To solve this issue, we currently have downgraded to `1.26.1`.

Below are the details :

#### Environment details

  - OS type and version:
```bash
$ uname -a
Linux vm-python-cs-02 4.9.0-13-amd64 #1 SMP Debian 4.9.228-1 (2020-07-05) x86_64 GNU/Linux
```
  - Python version: `python --version`
```Python 3.7.8```
  - pip version: `pip --version`
```
pip 20.1.1 from /opt/conda/lib/python3.7/site-packages/pip (python 3.7)
```
  - `google-cloud-bigquery` version: `pip show google-cloud-bigquery`
```
python3 -m pip show google-cloud-bigquery
Name: google-cloud-bigquery
Version: 1.27.2
Summary: Google BigQuery API client library
Home-page: https://github.com/googleapis/python-bigquery
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /opt/conda/lib/python3.7/site-packages
Requires: six, google-resumable-media, google-cloud-core, google-api-core
Required-by: 
```

#### Steps to reproduce

  1. Install `google-cloud-bigquery` with pip
  2. Create a `bigquery.Client()` object

#### Code example

```python
>>> from google.cloud import bigquery
>>> client = bigquery.Client()
```

#### Stack trace
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 183, in __init__
    _http=_http,
TypeError: __init__() got an unexpected keyword argument 'client_options'
```

**Comment by HemangChothani** [comment]
@McPatate Could please share the dependencies and it's version?  run `pip freeze` command for that.

For me it's working fine for my env:

google-cloud-bigquery==1.27.2
google-cloud-core==1.4.1
google-api-core==1.22.0

**Comment by McPatate** [comment]
Hello @HemangChothani, here you go :

```

**Comment by McPatate** [comment]
This is a very strange bug 😅 

I'm having no issue when I use python with an other user in such manner : `sudo -u another_user python3 ...`.

With my current user (the one that is experiencing the issue), I have 3 warnings when I type `pip freeze`:
```
WARNING: Could not generate requirement for distribution -oogle-cloud-datastore 1.12.0 (/opt/conda/lib/python3.7/si
te-packages): Parse error at "'-oogle-c'": Expected W:(abcd...)
WARNING: Could not generate requirement for distribution -oogle-cloud-core 1.3.0 (/opt/conda/lib/python3.7/site-pac
kages): Parse error at "'-oogle-c'": Expected W:(abcd...)
WARNING: Could not generate requirement for distribution -oogle-cloud-bigquery 1.26.1 (/opt/conda/lib/python3.7/sit
e-packages): Parse error at "'-oogle-c'": Expected W:(abcd...)
```

**Comment by HemangChothani** [comment]
@McPatate I think there is typo in somewhere like in requirement.txt file.  `-oogle-cloud-datastore` g is missing in that, actual is `google-cloud-datastore`.

**Comment by plamut** [comment]
Observing two different results when running the code under different users might suggest that different Python environments are used. Just mentioning this as a sanity check before any debugging, we've had a few cases like this in the past where it turned out that the code was actually run by a different Python than initially thought. :slightly_smiling_face:

**Comment by McPatate** [comment]
@HemangChothani there is no requirements.txt, I have no clue how the packages were installed.

@plamut I think this is the issue at hand ; there must be a problem with the python installs. I'm not going to try to replicate this bug as I believe it is a waste of time.

I'm closing the issue, thanks for your replies !
