### ISSUE TITLE
overwrite per partition on a big query table

### ISSUE THREAD

**Issue by Ferdinanddb** [googleapis/python-bigquery#281]
Hello,

Is there a way to perform an overwrite per partition on a bigquery table?

Lets say I have an original table A with 
```
Id, date
1,2010
2,2010
3,2011
4,2011
```

And a table B 
```
5,2011
6,2012
```

I want my final table A to be like 
```
1,2010
2,2010
5,2011
6,2012
```

I have tried several things via the "merge using on" DML query but did not succeed. 
Same with the `bq load --replace 'tableA$partitionID' tableB.csv` because there are multiple partitions in tableB.csv

**Comment by tswast** [comment]
@Ferdinanddb Thank you for your question. This repository (and `google-cloud-python`) is for issues encountered with the Python client libraries, not general issues with the BigQuery service. If you have a support plan, you may wish to contact customer support to answer this question. https://cloud.google.com/support

That said, I think a DML `MERGE` statement is going to be your best bet for combining tables in this way. Alternatively, you could implement this in multiple steps with the [BigQuery scripting interface](https://cloud.google.com/bigquery/docs/reference/standard-sql/scripting) to find which partitions are present in A & B, and select the desired ones for table C.
