### ISSUE TITLE
google-cloud-bigquery not compatible with pandas-gbq error

### ISSUE THREAD

**Issue by avissens** [googleapis/python-bigquery#302]
I have a compatibility issue with the new version of google-cloud-bigquery. When I try to install pandas `pip install --upgrade google-cloud-bigquery[bqstorage,pandas]` I get this error:

`ERROR: pandas-gbq 0.13.3 has requirement google-cloud-bigquery[bqstorage,pandas]<2.0.0dev,>=1.11.1, but you'll have google-cloud-bigquery 2.0.0 which is incompatible.`

As the results I cannot use pandas-gbq's functionalities such as `to_dataframe` etc.

Will appreciate your suggestions.

#### Environment details

  - OS type and version: MAC
  - Python version: Python 3.7.4
  - pip version: pip 19.3.1
  - `google-cloud-bigquery` version: 1.28.0

**Comment by tswast** [comment]
I recently release `pandas-gbq` version 0.14.0, which is compatible with `google-cloud-bigquery` 2.0.

**Comment by avissens** [comment]
I upgraded `pandas-gbq` to version 0.14.0 and it resolved the error I mentioned above when upgrading `google-cloud-bigquery` BUT I still have a problem writing BiqQuery results into a pandas DataFrame. So my assumption that it was caused by `pandas-gbq` is probably wrong.

I also seem to have another problem with PyYAML when upgrading `google-cloud-bigquery`:

`ERROR: awscli 1.16.277 has requirement PyYAML<5.2,>=3.10; python_version != "2.6" and python_version != "3.3", but you'll have pyyaml 5.3.1 which is incompatible.
Installing collected packages: pyyaml, libcst, google-cloud-bigquery-storage, google-cloud-bigquery
  Found existing installation: PyYAML 5.1.2
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

**Comment by tswast** [comment]
It appears that the PyYAML conflict is due to `libscst`. I'll do some investigating as to why that dependency is needed.

**Comment by tswast** [comment]
I checked with the team and `libcst` is only needed for https://github.com/googleapis/python-bigquery/blob/master/scripts/fixup_bigquery_v2_keywords.py I'll follow-up with a PR to remove this dependency as that script isn't even relevant for this library.

**Comment by anujraghuvanshi** [comment]
I am getting while on initial steps on Google Colab - https://colab.research.google.com/github/FirebaseExtended/codelab-contentrecommendation-android/blob/master/Firebase_ML_on_device_recommentations.ipynb#scrollTo=joSTkeEWN01m

![image](https://user-images.githubusercontent.com/22232709/146988232-b2a13ed3-c925-47ea-88c5-3572d48ae5d9.png)

Please suggest what should I do to fix this?

I hope below issue is due to this -
https://github.com/FirebaseExtended/codelab-contentrecommendation-ios/issues/3
