### ISSUE TITLE
use native support for namespace packages

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#313]
Per: https://github.com/googleapis/google-auth-library-python/issues/595#issuecomment-683903062

> It looks like different Google API packages have different approaches to using or not using pkg_resources here; e.g. https://github.com/googleapis/python-cloudbuild uses native NS packages and https://github.com/googleapis/python-bigquery uses pkg_resources with a pkgutil fallback.

Now that Python 2.7 and 3.5 support has been dropped, we may be able to follow the example in python-cloudbuild

**Comment by tseaver** [comment]
Something in my memory is niggling at me about doing this change incrementally:  we need to test that a native namespace `google-cloud-bigquery` can be installed safely alongside our current mixed-mode `google-auth` / `google-resumable-media` / `google-api-core` / `google-cloud-core`.

**Comment by meredithslota** [comment]
The GAPIC libraries dropped pkg_resources in Oct. 2022 here: https://github.com/googleapis/gapic-generator-python/pull/1471 so we should consider doing the same for consistency. I believe @chalmerlowe was interested in working on this across the libraries that still need this done.
