### ISSUE TITLE
Nothing maps to tables.update. update_table calls tables.patch

### ISSUE THREAD

**Issue by gavin-haynes-grow** [googleapis/python-bigquery#33]
With python bigquery client v1.24.0

As noted in https://github.com/googleapis/google-cloud-python/issues/4452

google.cloud.bigquery.client.Client.update_table does a patch (https://cloud.google.com/bigquery/docs/reference/rest/v2/tables/patch)

But nothing does an update (https://cloud.google.com/bigquery/docs/reference/rest/v2/tables/update)

This makes it hard to update a view.

As a workaround, I can do this:

```
table_ref = bq.Table("x.y.z")
table_ref.view_query = "SELECT 42"
table = bq.Table.from_api_repr(client._call_api(
        bq.DEFAULT_RETRY, method="PUT", path=table_ref.path, data=table_ref.to_api_repr()))
```

Can the client have a function like `replace_table` that will call this endpoint?

**Comment by tswast** [comment]
@shollyman I recall there was an issue with updating views via the API in the past? Did that ever get fixed for `table.patch`?

**Comment by meredithslota** [comment]
The current limitations of views are described here: https://cloud.google.com/bigquery/docs/views-intro Here's how to update a view in Python: https://cloud.google.com/bigquery/docs/updating-views#python — do the code samples there help with your use case? Several of them were added since this ticket was filed.

**Comment by meredithslota** [comment]
(Actually, since this issue is pretty old and code samples have been added in this space relatively recently, I'm gonna go ahead and close this _but_ if this doesn't answer your question please reopen.)
