### ISSUE TITLE
docs: index page

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#345]
**Is your feature request related to a problem? Please describe.**

When browsing the [google-cloud-bigquery documentation](https://googleapis.dev/python/bigquery/latest/), it can be difficult to find what is needed. First, you have to know that the [google-cloud-bigquery API reference page](https://googleapis.dev/python/bigquery/latest/reference.html) is the true starting point for API reference. Then you have to have some idea of what you're looking for.

Not everyone knows that the [Client class](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.client.Client.html#google.cloud.bigquery.client.Client) has most of the operations you'd want. Beyond that reference, there are also there are highly useful pages such as the [`%%bigquery` magics documentation](https://googleapis.dev/python/bigquery/latest/magics.html).

 **Describe the solution you'd like**

A reference page with every single module, class, method, and property listed. That way if someone has a clue about the property name (for example, they are browsing the [BigQuery code samples](https://cloud.google.com/bigquery/docs/samples) and see an object doing what they want), they can use their browser's find-in-page to figure out where that class is actually documented.

 **Describe alternatives you've considered**

* Expand the [API reference page](https://googleapis.dev/python/bigquery/latest/reference.html) to include methods and properties.
  * Pros:
    * It might be possible to adjust the templates so that the page requires no additional ongoing work to expand the table to include properties and methods.
    * Continuity -- keep the same "main" landing page.
  * Cons:
    * This page is manually implemented, which has resulted in missing classes. https://github.com/googleapis/python-bigquery/issues/342 If adding methods & properties also requires manual additions, this is infeasible.
   * This page is already quite long. It may become even more difficult to find the desired document if it included everything.
* Make search more prominent.
  * Pros:
    * For some searches it gives very relevant results: https://googleapis.dev/python/bigquery/latest/search.html?q=dataframe
  * Cons:
    * Searching for the commonly used method `query` gives literally everything. I think because it matches with `bigquery` in the package name. https://googleapis.dev/python/bigquery/latest/search.html?q=query

 **Additional context**

* Main Python docs index page: https://docs.python.org/3/genindex-all.html

**Comment by chalmerlowe** [comment]
I like this proposal. However, in light of the current manning and other priorities, I believe this should be closed until such a time as we have more bandwidth to be able to focus on it.
