### ISSUE TITLE
Iterating over table returns repeating records.

### ISSUE THREAD

**Issue by YordanPavlov** [googleapis/python-bigquery#357]
#### Environment details
  - The script is run inside a Docker container created from _python:3.8.6-slim_ image
  - Python version: 3.6.12
  - pip version: 20.2.3
  - `google-cloud-bigquery`: 1.28.0

#### Steps to reproduce

I have a big table consisting of a single column. The table has around 700M records all of them are unique strings. I have verified this by running:

`SELECT COUNT(DISTINCT address) AS uniq_address FROM my_table`

which returns the exact same number as the number of rows in the table details. My goals is to extract all the data through the API, I have a script which runs for more than 24 hours. What I observer is that some records are being repeated.

#### Code example

```python
bq_client = bigquery.Client(credentials=credentials, project=your_project_id,)

table_reference = bigquery.TableReference.from_string(
    BIGQUARY_TABLE_NAME
)
rows = bq_client.list_rows(
        table_reference,
        selected_fields=[
            bigquery.SchemaField("address", "STRING")
        ]
    )
counter_row = 0
for row in rows:
   counter_row += 1
   address = row.values()[0]
   # Store the record along with information for the counter
```

#### What I observer
After some number of records (millions) I receive repeating address. This problem presents itself after hours of iteration, so for now I have been unable to narrow it down further. When the iteration is complete, I have iterated the full number of records (700M) but the number of unique addresses is only around 500M. Upon analyzing the data I have received repeating addresses for different row index. I would be grateful to any tips of how to proceed.

**Comment by YordanPavlov** [comment]
As a further information on the problem, what has lowered the number of repeated records for me is using sort of 'batching' by specifying start_index and max_results like so:

MAX_RECORDS_PER_BIGQUERY_REQUEST = 100000
```
    rows = bq_client.list_rows(
        table_reference,
        selected_fields=[
            bigquery.SchemaField("address", "STRING")
        ],
        start_index = table_row_reached,
        max_results = MAX_RECORDS_PER_BIGQUERY_REQUEST
```

**Comment by tswast** [comment]
Is this table being modified via the streaming buffer?

**Comment by YordanPavlov** [comment]
> Is this table being modified via the streaming buffer?

Through the whole export the table remains constant. I have performed computations on top of it in BigQuery and started the export only after those are completed.

**Comment by tswast** [comment]
If your goal is to export the data, we do have a job that can export data to GCS https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.client.Client.html#google.cloud.bigquery.client.Client.extract_table

Also, this could potentially be a good use for the BigQuery Storage API. https://github.com/googleapis/python-bigquery-storage

I don't see anything in the Python client that would cause this behavior. You might have found a problem with the tabledata.list API, in which case I recommend filing an issue at https://issuetracker.google.com/issues/new?component=187149&template=1162659 or a GCP support ticket.

**Comment by tswast** [comment]
Closing, as I don't believe this is a problem with the Python client.
