### ISSUE TITLE
Support for client-side expansion of parameterized queries

### ISSUE THREAD

**Issue by pgp** [googleapis/python-bigquery#364]
**Is your feature request related to a problem? Please describe.**
AFAIK, when using query_parameters in `QueryJobConfig`, the query is not expanded by the client, but both params and parameterized query are sent to BQ. However, it would be comfortable for debugging, to be able to print the expanded query before sending it to BQ. Don't know if there's already some way to do it within this library. 
 **Describe the solution you'd like**
A method in `bigquery.Client` to expand client-side the query params, e.g.
```python
client = bigquery.Client(location='EU')
job_config = bigquery.QueryJobConfig(query_parameters=query_parameters)
expanded_querystring = client.expand_query(query=query, job_config=job_config) # example of desired method
```

**Comment by tswast** [comment]
This does sound like a useful feature for debugging. As far as I know, we don't yet have a Python wrapper for [ZetaSQL](https://github.com/google/zetasql), the open source implementation of the BigQuery Standard SQL syntax parser. Possible we could do something with regex, but it'd be less reliable than using the official parser.

**Comment by shollyman** [comment]
My worry here is that query params are dependent on parsing, and can only replace expressions, but not other elements like references or identifiers.  Getting false confidence from a naive client side expansion is probably worse than no expansion.  There's some diagnostic assistance available at dryrun, including query statistics such as undeclared query parameters.

**Comment by shollyman** [comment]
Going to close this feature request out.  It's been two years, and there's yet to be a good solution here.  One thing you worth calling out here is that dry run queries have some useful parameter validation behavior. Issuing a dry run query can return query parameter information from the returned statistics such as expected data types, missing query params, etc.
