### ISSUE TITLE
process: use templated noxfile + refactor tests

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#366]
It'd be nice to stay consistent with the other libraries in how we perform tests.

Blocked by:

- https://github.com/googleapis/python-bigquery/pull/203 - move samples to templated subdir(s)
- https://github.com/googleapis/synthtool/issues/838 -- extras in template
- https://github.com/googleapis/synthtool/issues/839 -- constraints in template

**Comment by tswast** [comment]
This issue may be considered to be blocking: https://github.com/googleapis/python-bigquery/pull/336 as the SNIPPETS session is a custom session, which is not present in other libraries.

**Comment by chalmerlowe** [comment]
Closing. A number of tests and such have been relocated to more appropriate locations.
