### ISSUE TITLE
load_table_from_dataframe -- support alternative serialization formats

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#383]
Currently, pandas-gbq doesn't use `load_table_from_dataframe` because it is using CSV for serialization, which has better support for TIME, DATE, DATETIME than Parquet. See: https://github.com/googleapis/python-bigquery/issues/56, https://github.com/googleapis/python-bigquery/issues/382

Struct / Array support could also be improved (though this is partially due to problems in the pyarrow library). https://github.com/googleapis/python-bigquery/issues/19

I propose supporting the CSV serialization type.

**Comment by tswast** [comment]
To go from DataFrame to CSV, we can use the same tempfile logic as we have for parquet, but instead use `to_csv` + a few parameters to ensure proper data types:

https://github.com/pydata/pandas-gbq/blob/ac2d2fe4ac0025109f8df3723e3f03a337face94/pandas_gbq/load.py#L16-L30

**Comment by tswast** [comment]
This would also require adding CSV to the allowed serialization formats here: https://github.com/googleapis/python-bigquery/blob/809e4a27b94ba30c10e0c9a7e89576a9de9fda2b/google/cloud/bigquery/client.py#L2201-L2206

**Comment by cguardia** [comment]
@tswast I have the initial work for this in #399. Looking for comments about which are the best parameters to use in the ``to_csv`` call, and whether this is going in the right direction.
