### ISSUE TITLE
show progress bar in %%bigquery magics

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#389]
**Is your feature request related to a problem? Please describe.**

When running the `%%bigquery` magics, there is no indication of progress.

 **Describe the solution you'd like**

Show a progress bar using `tqdm` or `tqdm_notebook`.

 **Describe alternatives you've considered**

N/A

 **Additional context**

`tqdm_notebook` is ideal, as it uses the ability to embed HTML for a nicer-looking progress bar, but this is not always available. `tqdm` should be the default, but perhaps overridable via the `google.cloud.bigquery.magics.context` settings.

**Comment by tswast** [comment]
This may be as simple as setting `progress_bar_type="tqdm"` here: https://github.com/googleapis/python-bigquery/blob/dc78eddde7a6a312c8fed7bace7d64036837ab1a/google/cloud/bigquery/magics/magics.py#L692 and here: https://github.com/googleapis/python-bigquery/blob/dc78eddde7a6a312c8fed7bace7d64036837ab1a/google/cloud/bigquery/magics/magics.py#L695

but ideally we would want the ability to change to `tqdm_notebook` when explicitly requested or maybe even if we can detect that we are in a supported environment

**Comment by tswast** [comment]
Follow-up to https://github.com/googleapis/python-bigquery/issues/343 which added the progress bar for waiting for the query to finish.

**Comment by HemangChothani** [comment]
- Can we use `get_ipython().__class__` to detect  terminal or any other notebooks and set the progress_bar_type accordingly?

- Can we include  `progress_bar_type` parameter in to the magic_arguments and set default to 'tqdm'?

**Comment by tswast** [comment]
> Can we include progress_bar_type parameter in to the magic_arguments and set default to 'tqdm'?

Let's start with this. Plus, let's add `progress_bar_type` to the global context object so that the default can be changed by the user.

> Can we use get_ipython().__class__ to detect terminal or any other notebooks and set the progress_bar_type accordingly?

Let's file a separate issue for that. I don't want to get __too__ magic in our magics. :-)
