### ISSUE TITLE
Use DataFormatOptions to download timestamps with full precision

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#395]
**Is your feature request related to a problem? Please describe.**

When fetching timestamp values, the [tabledata.list](https://cloud.google.com/bigquery/docs/reference/rest/v2/tabledata/list) and [jobs.getQueryResults](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/getQueryResults) APIs return a floating point value by default. 

This can cause [unexpected floating point issues](https://issuetracker.google.com/issues/147629356) when rounding timestamps in SQL, such as with the `TIMESTAMP_TRUNC(COL_TIMESTAMP, MILLISECOND)` function.

 **Describe the solution you'd like**

The backend API adds a [`formatOptions.useInt64Timestamp`](https://cloud.google.com/bigquery/docs/reference/rest/v2/DataFormatOptions#FIELDS.use_int64_timestamp) option. 

* Wherever `tabledata.list`, `jobs.query`, or `jobs.getQueryResults` are called, set the `formatOptions.useInt64Timestamp` option to `True`.
* Wherever timestamps in rows API responses are handled, update it to use integer math to extract microseconds and seconds.
* Add system tests to verify that timestamps rounded to every digit of supported precision (e.g. 9, 9.9, 9.99, ..., 9.999999) are returned exactly as set in the table/query.

 **Describe alternatives you've considered**

N/A

 **Additional context**

Precision issues for the other direction (to BigQuery) for similar floating-point reasons: https://github.com/googleapis/python-bigquery/issues/392

**Comment by HemangChothani** [comment]
@tswast Do we need anything in `.proto` file here because when i am passing in `query_paramter` it throws an error.

**Comment by tswast** [comment]
Why are you passing this to `query_parameter`? These are API parameters (called `extra_params` in our client code, I believe)

**Comment by HemangChothani** [comment]
Yes , I am passing in extra_params like
extra_parms['formatOptions']=Dataformat options(object)

**Comment by HemangChothani** [comment]
When i pass the `extra_parms['formatOptions']=Dataformatoptions`  (object) as mentioned in [dcument](https://cloud.google.com/bigquery/docs/reference/rest/v2/tabledata/list#query-parameters), it throws an error like  `Invalid JSON payload received. Unknown name "formatOptions": Cannot bind query parameter. 'formatOptions' is a message type. Parameters can only be bound to primitive types.`

https://github.com/googleapis/python-bigquery/blob/a1949ae20ec4f9c771b0cffbcd70792dd6a30dbf/google/cloud/bigquery/client.py#L3154-L3168

**Comment by tswast** [comment]
@HemangChothani  Please try the following:

* Does it work if you first serialize the DataFormatOption dictionary to JSON? e.g. `json.dumps({"useInt64Timestamp": True})`
* Does it work if instead of setting `extra_parms['formatOptions']`, you set `extra_parms['formatOptions.useInt64Timestamp']`?

**Comment by HemangChothani** [comment]
>     * extra_parms['formatOptions.useInt64Timestamp'] = True

This works fine, so opened a drat PR to verify the approach, after that i will add a system test regarding that.
