### ISSUE TITLE
Wait for Query hangs indefinitely for some queries

### ISSUE THREAD

**Issue by willbowditch** [googleapis/python-bigquery#403]
I think this bug has been introduced by the `wait_for_query` `tqdm` helper in https://github.com/googleapis/python-bigquery/pull/352

Dropping the previous version resolves `pipenv install google-cloud-bigquery==2.3.1`.

Some queries now hang indefinitely at "query is running" or "complete": 

```py
    query_job = client.query(query, job_config=job_config)
    df = query_job.to_dataframe(progress_bar_type='tqdm')
```

![image](https://user-images.githubusercontent.com/14288042/100255357-4c067680-2f3b-11eb-8003-fdc97589fab8.png)

However running **the same without the progress bar** returns the dataframe

```py
    query_job = client.query(query, job_config=job_config)
    df = query_job.to_dataframe(progress_bar_type=None)
```

The following also returns the dataframe:

```py
    query_job = client.query(query, job_config=job_config)
    df = query_job.to_dataframe(progress_bar_type=None)
    df = query_job.to_dataframe(progress_bar_type='tqdm')
```

![image](https://user-images.githubusercontent.com/14288042/100255582-92f46c00-2f3b-11eb-9cb9-dab513e4ba7b.png)

#### Environment details

  - OS type and version: OS X 10.15.7
  - Python version: `python --version` 3.6.10
  - pip version: `pip --version` pip 20.2.4 
  - `google-cloud-bigquery` version: `pip show google-cloud-bigquery` Version: 2.4.0

**Comment by willbowditch** [comment]
Playing around with the internals of `wait_for_query`, it looks as though a timeout of .5 will always return an timeout error for me, even when the query has completed:

```
ReadTimeoutError: HTTPSConnectionPool(host='bigquery.googleapis.com', port=443): Read timed out. (read timeout=0.5)
```

Setting the timeout to 1 works.

**Comment by HemangChothani** [comment]
@willbowditch Could please share the query or amount of data you are retrieving, it might happen with the big queries or when download large number of rows, i have tried with around 16,000 rows but not able to reproduce it.
   
![Screenshot from 2020-11-26 17-41-28](https://user-images.githubusercontent.com/50404902/100349787-fdc2a780-300e-11eb-993b-ea80741bf14e.png)

**Comment by willbowditch** [comment]
@HemangChothani Sure, here's some details.

The data is not that large, resulting data frame using the previous version:

```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12460 entries, 0 to 12459
Data columns (total 9 columns):
***                  12460 non-null object
***                  12460 non-null object
***                  2460 non-null float64
***                  12460 non-null float64
***                  12460 non-null object
***                  12460 non-null float64
***                  12460 non-null int64
***                  12460 non-null float64
***                  12460 non-null float64
dtypes: float64(5), int64(1), object(3)
memory usage: 876.2+ KB
```

The query is not super complex. Roughly it's three `WITH` statements and an `inner join`,  the query plan has 6 stages:
![image](https://user-images.githubusercontent.com/14288042/100351261-15843680-2fe3-11eb-9e03-6de944ef7c79.png)

Couple of observations:

- If I change the query slightly, to prevent the cached version being returned, the progress bar works as intended but never moves past completed (It does not return the dataframe):
![image](https://user-images.githubusercontent.com/14288042/100351941-284b3b00-2fe4-11eb-9710-7abb6610ceb4.png)
- If I rerun, using the cahce, it hangs at 
![image](https://user-images.githubusercontent.com/14288042/100352002-3d27ce80-2fe4-11eb-96b4-fc6965b26afd.png)

**Comment by HemangChothani** [comment]
>     * If I rerun, using the cache, it hangs
![Screenshot from 2020-11-27 16-39-51](https://user-images.githubusercontent.com/50404902/100443348-8b65cc00-30cf-11eb-8394-239456722bf3.png)

This is when query hit the cache and it just show that query is running and when query ends it shows the 100% and the time it takes, it doesn’t hang there.  The only difference is when you didn't pass `tqdm`,  in console it shows nothing and when you pass `tqdm` it just prints that Query is running.



>     * If I change the query slightly, to prevent the cached version being returned 

If the progress bar show the last stage and completed and still time increments  on progress bar means some operation is going on after that(completion of stages), once the time increment stopped you will get the `Downloading` progress bar

Yes, right now `timeout=0.5` will take more time then `timeout=1` in some queries, i will discuss about to make default time or do public for users.

**Comment by willbowditch** [comment]
@HemangChothani 

> If the progress bar show the last stage and completed and still time increments on progress bar means some operation is going on after that(completion of stages), once the time increment stopped you will get the Downloading progress bar

The downloading progress bar never starts and a data frame is never returned. The same query in the web GUI takes: `1.9 sec elapsed, 18.8 MB processed`

See screen grab of the following test program for the last two versions of `python-bigquery`:

[![asciicast](https://asciinema.org/a/lRCxS4kD7D9qcys033yI6YnQA.svg)](https://asciinema.org/a/lRCxS4kD7D9qcys033yI6YnQA)

```
from pathlib import Path
from google.cloud import bigquery

print(f"BigQuery version: {bigquery.__version__}")

query = Path("test.sql").read_text()

bq = bigquery.Client()
query_job = bq.query(query)
df = query_job.to_dataframe(progress_bar_type="tqdm")
print(df.shape)
```

**Comment by HemangChothani** [comment]
@willbowditch Sorry for the extra noise, i am able to reproduce and it's because of  caching changes done in the [PR](https://github.com/googleapis/python-bigquery/pull/384)   which is now reverted, Could please try with the master branch of `google-cloud-bigquery`?

**Comment by willbowditch** [comment]
@HemangChothani Can confirm it's now fixed on master, thanks 👍 

```
❯ python test.py
BigQuery version: 2.4.0
Query complete after 0.49s: 100%|███████████| 1/1 [00:00<00:00,  2.04query/s]
Downloading: 100%|█████████████████| 12460/12460 [00:02<00:00, 4819.29rows/s]
(12460, 9)
Time: 0h:00m:05s
```
