### ISSUE TITLE
Jobs should be able to restrict target datasets

### ISSUE THREAD

**Issue by micimize** [googleapis/python-bigquery#42]
This is similar to the proposal in googleapis/google-cloud-python#6042, but relates to specific jobs rather than client bindings. Simply managing multiple keys isn't really a viable solution for some use cases, such as superset (https://github.com/apache/incubator-superset/issues/9182)

Even for less security-sensitive usecases, I think this would be a valuable affordance for developers to more clearly define code contracts.

**Comment by shollyman** [comment]
This feels like something better solved by using the bigquery service's access control and governance features, not a weak enforcement in the client library.  If that set of features is insufficient, I'd file a request on the BQ issue tracker:

https://b.corp.google.com/issues/new?component=187149&template=0

**Comment by micimize** [comment]
That makes sense – a [conditional IAM policy](https://cloud.google.com/bigquery/docs/reference/rest/v2/Policy) based solution would make sense for this use-case, and there is [an issue for it in the public issue tracker](https://issuetracker.google.com/issues/143959429). Will continue discussion there.
