### ISSUE TITLE
Table Access Level: table.AccessEntry? 

### ISSUE THREAD

**Issue by jf-marquis-Adeo** [googleapis/python-bigquery#440]
Hi there,
With table permission arrival I need to be able to access something like a table.AccessEntry(role, entity_type, entity_id) which is not existing (correct me if I'm wrong)
Can you implement that please ?

**Comment by HemangChothani** [comment]
@jf-marquis-Adeo 
Hi,
If you are asking about table level access control then here is the [docuement](https://cloud.google.com/bigquery/docs/table-access-controls-intro).

We have method in client class to set policy for the table `client.set_iam_policy().`

**Comment by jf-marquis-Adeo** [comment]
ok but how can i get iam_policy from python sdk ?

**Comment by HemangChothani** [comment]
There is also method to get policy of the table  `client.get_iam_policy(table)`.

**Comment by jf-marquis-Adeo** [comment]
great
sorry for disturbing
