### ISSUE TITLE
How to get the size of query that would be processed without running it?

### ISSUE THREAD

**Issue by imshetu** [googleapis/python-bigquery#450]
Thanks for stopping by to let us know something could be better!

 **Is your feature request related to a problem? Please describe.**

I would like to know what is the size of the query that would be processed by a query.

**Describe the solution you'd like**

For example, let's say I have a query called
```
select * from table_a;
```
In the Bigquery console, I can see the amount of query size that would be processed.
<img width="980" alt="Screen Shot 2020-12-24 at 11 53 03 AM" src="https://user-images.githubusercontent.com/66333803/103064605-97658080-45de-11eb-9534-d66380f156fe.png">

I want to have an API in the client that would give me the query size return `0.37 MB` when called.

**Describe alternatives you've considered**
If already the existing URL is there which would return a JSON response, I can use that too in my python script. 

 **Additional context**

**Comment by imshetu** [comment]
Looks like it can be done by this.. 
https://github.com/googleapis/python-bigquery/blob/35627d145a41d57768f19d4392ef235928e00f72/samples/client_query_dry_run.py

**Comment by HemangChothani** [comment]
@imshetu Yes it is perfect example to get `total_bytes_processed` without running the query.

> https://github.com/googleapis/python-bigquery/blob/35627d145a41d57768f19d4392ef235928e00f72/samples/client_query_dry_run.py
