### ISSUE TITLE
`google.cloud.bigquery.job.QueryJob.exception` has wrong behavior

### ISSUE THREAD

**Issue by alexandreyc** [googleapis/python-bigquery#451]
Hello,

According to the [documentation](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.job.QueryJob.html#google.cloud.bigquery.job.QueryJob.exception) of `google.cloud.bigquery.job.QueryJob.exception`, this method should returns an exception (and not raises) if something went wrong. But according to my tests this is not always the case:

```python
from google.cloud import bigquery

client = bigquery.Client()

# Correct behavior: returns an exception and does not raise.
query = 'WRONG QUERY'
job = client.query(query)
exc = job.exception()

# Wrong behavior: raises an exception instead of returning it.
query = 'ASSERT (SELECT 2 > 3) AS "Error !!!"'
job = client.query(query)
try:
    job.exception()
except:
    print('raised!')
```

Am I misunderstanding the documentation or is this the correct behavior?

I'm using `google-cloud-bigquery==2.6.1` with Python 3.8.6. Let me know if you need more informations.

Thanks for your help,

**Comment by HemangChothani** [comment]
@tswast @busunkim96  Please suggest.
I think something is missing for the scenario when `query.state` is `RUNNING` and library wants retry it, it internally call the `client._get_query_results` method which throws an error of `BadRequest`.
 
I am not sure about handle this in `bigquery` library and set the `google.api_core.future.polling.PollingFuture.set_exception` from the query.py file.

**Comment by alexandreyc** [comment]
Working on something related, I discovered that the problem does not exist when doing a double assertion:

```python
# Correct behavior: returns an exception and does not raise.
query = 'ASSERT (SELECT 2 > 3) AS "Error !!!"; ASSERT (SELECT 2 > 3) AS "Error again !!!";'
job = client.query(query)
exc = job.exception()
```

Hope it can help...

Thanks,

**Comment by HemangChothani** [comment]
@tswast It

**Comment by tswast** [comment]
I believe this is a difference in API behavior of `getQueryResults` between scripting jobs and non-scripting query jobs.

CC @shollyman

**Comment by tswast** [comment]
Regarding this issue, it appears that this library may be using the `google-api-core` library slightly incorrectly. The base class (where `exception()` is defined) assumes that `_blocking_poll` doesn't raise any exception

https://github.com/googleapis/python-api-core/blob/b51b7f587042fe9340371c1b5c8e9adf8001c43a/google/api_core/future/polling.py#L129-L134

Instead, it is expected that [set_exception()](https://github.com/googleapis/python-api-core/blob/b51b7f587042fe9340371c1b5c8e9adf8001c43a/google/api_core/future/polling.py#L129-L134) is called.

We do this here:

https://github.com/googleapis/python-bigquery/blob/2849e569d0423e6e40bda953b0e9d38157aaf2df/google/cloud/bigquery/job/base.py#L582

But we are missing the case when the `getQueryResults` backend API throws an error.

We probably need a try-catch block in `QueryJob.done()` as it is not expected (or documented) to raise an exception.

https://github.com/googleapis/python-bigquery/blob/2849e569d0423e6e40bda953b0e9d38157aaf2df/google/cloud/bigquery/job/query.py#L1023

If `_get_query_results` does raise an exception, we might have to inspect it a bit to determine if the job is complete (failed) or it was just a transient issue.

**Comment by plamut** [comment]
@tswast Has this proposal been confirmed? If yes, I can start implementing it (as there's no assignee yet).

**Comment by tswast** [comment]
Yes. Let's make sure that `exception()` (and also `done()`) does not throw.

**Comment by tswast** [comment]
`result()` should continue to throw
