### ISSUE TITLE
WRITE_APPEND not working!

### ISSUE THREAD

**Issue by xuanzee** [googleapis/python-bigquery#455]
#### Environment details

  - OS type and version: Windows 10 Enterprise
  - Python version: 3.7.7
  - pip version: 20.3.3
  - conda version: 4.9.2
  - `google-cloud-bigquery` version: 2.6.1
#### Steps to reproduce

  1. Create a table in Bigquery from a CVS file, either in the Console or via the client library, doesn't matter here.
  2. Attempt to append new data to the existing table via the client library (where the code is not working). Please note that the new data file contains exactly the same columns as the original CVS file, so there is no issue of schema not matching.

#### Code example

```python
# Attempting to append new data, after the original table has already been successfully created.

from google.cloud import bigquery as bq

client = bq.Client()

table_id = 'my-project.my-dataset.my-table'

job_config = bq.LoadJobConfig(source_format=bq.SourceFormat.CSV, skip_leading_rows=1,
	write_disposition='WRITE_APPEND')

with open(file_path, 'rb') as source_file:
	job = client.load_table_from_file(source_file, table_id, job_config=job_config)

# file_path is a certain local path. No problem there since creating or replacing table both saw no issues.
# If setting the write_disposition to WRITE_TRUNCATE', it can successfully overwrite the old table. But WRITE_APPEND
# just doesn't work -- the original table remains intact/unchanged after running the code.
```

#### Stack trace
(No error was ever raised, which was the most frustrating part...)

Thanks!

**Comment by HemangChothani** [comment]
@xuanzee  `WRITE_APPEND` is working fine for me.
```python
from google.cloud import bigquery

client = bigquery.Client()
table_id = "your-project.your_dataset.your_table_name"

job_config = bigquery.LoadJobConfig(
        source_format=bigquery.SourceFormat.CSV, skip_leading_rows=1, autodetect=True,
    )

# First to create a table.
with open(file_path, "rb") as source_file:
        job = client.load_table_from_file(source_file, table_id, job_config=job_config)

job.result()  # Waits for the job to complete.
table = client.get_table(table_id)  # Make an API request.
print  (table.num_rows, len(table.schema), table_id)  #num_rows =  2 

# Now use `WRITE_APPEND`
job_config = bigquery.LoadJobConfig(source_format=bigquery.SourceFormat.CSV, skip_leading_rows=1,write_disposition='WRITE_APPEND')
with open(file_path, 'rb') as source_file: 
     job = client.load_table_from_file(source_file, table_id, job_config=job_config)


job.result()  # Waits for the job to complete.
table = client.get_table(table_id)  # Make an API request.
print  (table.num_rows, len(table.schema), table_id)  ##num_rows =  4
```

CSV file is:

full_name,age
Phred Phlyntstone,32
Wylma Phlyntstone,29

**Comment by xuanzee** [comment]
@HemangChothani
Thank you very much for the quick response. I was trying to re-run the code again but encountered a new error message --
When trying to run
```python
from google.cloud import bigquery
```
I got the error message as below:
AttributeError: type object 'StandardSqlDataType' has no attribute 'STRING'

What may be causing this? This wasn't encountered before, and my packages should be all up to date. Once that is resolved, hopefully I can validate the WRITE_APPEND as well.

Thanks,
Xuan

**Comment by HemangChothani** [comment]
@xuanzee Please reinstall google-cloud-bigquery `python3 -m pip install -U google-cloud-bigquery` and try it or try with fresh environment. Please share dependency list, for that you can use  `pip3 freeze` command.

**Comment by plamut** [comment]
@xuanzee Did upgrading the library and the dependencies as suggested help? Can the issue be closed now?

Thanks!

**Comment by xuanzee** [comment]
@plamut Hi Peter, thanks for following up. I have just got a chance to pick this back up. I updated some libraries but still got the following error, when executing this line:
![116](https://user-images.githubusercontent.com/22087831/108562455-ddcd1800-72cd-11eb-8a75-ff8bb0a04a8e.PNG)

Here are the dependency list pertaining to google: (What are the specific dependencies that we need to check on? The whole list seems fairly long.)
![115](https://user-images.githubusercontent.com/22087831/108562691-41574580-72ce-11eb-970c-0de21829c54d.PNG)

As always, thank you very much for your help.

**Comment by plamut** [comment]
@xuanzee Good, the previous error is gone and the posted package versions seem up to date.

However, it seems that these are not the actual packages used by the notebook. The `timeout` parameter was [added](https://github.com/googleapis/google-resumable-media-python/commit/5310921dacf5232ad58a5d6e324f3df6b320eca7#diff-54457d44fea6e337b00fdd20548f2ab330969fff5a93c3fc075cfca753e06188) to the `ResumableUpload` class  in Q2/2020 and [released](https://github.com/googleapis/google-resumable-media-python/releases/tag/v0.6.0) in version `0.6.0`.

What's the output of the following when run from inside the notebook?
```
!{sys.executable} -m pip freeze | grep google
```

**Comment by xuanzee** [comment]
@plamut Got an error message as below:
![116](https://user-images.githubusercontent.com/22087831/108946936-74326e00-762d-11eb-9873-93b917525e62.PNG)

**Comment by plamut** [comment]
@xuanzee Ah, I overlooked that you use Windows that doesn seem to have "grep" installed by default - just run the pip freeze command without piping it through grep:

```
!{sys.executable} -m pip freeze
```

The output will be longer, but it's easy to spot `google*` dependencies.

**Comment by xuanzee** [comment]
Hi @plamut : Below is the whole list of the output for reference.. The google* dependencies look the same as what were in the list before, though. After the list, I attached the codes again for reference also. The last line is the one that yielded the "timeout" error.

alabaster==0.7.12
anaconda-client==1.7.2
anaconda-navigator==1.9.12
anaconda-project==0.8.3
appdirs==1.4.4
argh==0.26.2
argon2-cffi @ file:///C:/ci/argon2-cffi_1596828549974/work
asn1crypto @ file:///tmp/build/80754af9/asn1crypto_1596577642040/work
astroid @ file:///C:/ci/astroid_1592481955828/work
astropy @ file:///C:/ci/astropy_1606919052914/work
async-generator==1.10
atomicwrites==1.4.0
attrs @ file:///tmp/build/80754af9/attrs_1604765588209/work
autopep8 @ file:///tmp/build/80754af9/autopep8_1596578164842/work
Babel @ file:///tmp/build/80754af9/babel_1607110387436/work
backcall==0.2.0
backports-abc==0.5
backports.shutil-get-terminal-size @ file:///tmp/build/80754af9/backports.shutil_get_terminal_size_1608222128777/work
bcrypt @ file:///C:/ci/bcrypt_1597918112552/work
beautifulsoup4 @ file:///tmp/build/80754af9/beautifulsoup4_1601924105527/work
bitarray @ file:///C:/ci/bitarray_1605065253308/work
bkcharts==0.2
black==19.10b0
bleach @ file:///tmp/build/80754af9/bleach_1600439572647/work
bokeh @ file:///C:/ci/bokeh_1603297932359/work
boto==2.49.0
Bottleneck==1.3.2
brotlipy==0.7.0
cachetools @ file:///tmp/build/80754af9/cachetools_1607706694405/work
certifi==2020.12.5
cffi @ file:///C:/ci/cffi_1606255207413/work
chardet @ file:///C:/ci/chardet_1607706910910/work
click==7.1.2
cloudpickle @ file:///tmp/build/80754af9/cloudpickle_1598884132938/work
clyent==1.2.2
colorama @ file:///tmp/build/80754af9/colorama_1607707115595/work
comtypes==1.1.8
conda==4.9.2
conda-build==3.15.1
conda-package-handling @ file:///C:/ci/conda-package-handling_1603018162806/work
configparser==5.0.0
contextlib2==0.6.0.post1
cryptography @ file:///C:/ci/cryptography_1607639129468/work
cycler==0.10.0
Cython @ file:///C:/ci/cython_1605457674480/work
cytoolz==0.11.0
dask @ file:///tmp/build/80754af9/dask-core_1607706933335/work
decorator==4.4.2
defusedxml==0.6.0
diff-match-patch @ file:///tmp/build/80754af9/diff-match-patch_1594828741838/work
distributed @ file:///C:/ci/distributed_1607708294596/work
docopt==0.6.2
docutils==0.16
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.1.0
filelock==3.0.12
flake8 @ file:///tmp/build/80754af9/flake8_1601911421857/work
Flask==1.1.2
fsspec @ file:///tmp/build/80754af9/fsspec_1602684995936/work
future==0.18.2
genson==1.2.1
gevent @ file:///C:/ci/gevent_1609093187077/work
glob2==0.7
gmpy2==2.0.8
google-api-core==1.26.0
google-api-python-client==1.12.8
google-auth==1.27.0
google-auth-httplib2==0.0.4
google-auth-oauthlib==0.4.2
google-cloud-bigquery==2.9.0
google-cloud-core==1.6.0
google-cloud-storage==1.36.0
google-crc32c==1.1.2
google-resumable-media==1.2.0
googleapis-common-protos @ file:///C:/ci/googleapis-common-protos-feedstock_1600455733359/work
greenlet @ file:///C:/ci/greenlet_1600874076725/work
grep==0.3.2
grpcio==1.34.0
h5py==2.10.0
HeapDict==1.0.1
html5lib @ file:///tmp/build/80754af9/html5lib_1593446221756/work
httplib2==0.19.0
idna @ file:///tmp/build/80754af9/idna_1593446292537/work
imageio @ file:///tmp/build/80754af9/imageio_1594161405741/work
imagesize==1.2.0
importlib-metadata @ file:///tmp/build/80754af9/importlib-metadata_1602276842396/work
iniconfig @ file:///tmp/build/80754af9/iniconfig_1602780191262/work
intervaltree @ file:///tmp/build/80754af9/intervaltree_1598376443606/work
ipykernel @ file:///C:/ci/ipykernel_1596208728219/work/dist/ipykernel-5.3.4-py3-none-any.whl
ipython @ file:///C:/ci/ipython_1604101327119/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
ipywidgets @ file:///tmp/build/80754af9/ipywidgets_1608834360725/work
isort @ file:///tmp/build/80754af9/isort_1602603989581/work
itsdangerous==1.1.0
jdcal==1.4.1
jedi @ file:///C:/ci/jedi_1606932641827/work
Jinja2==2.11.2
joblib @ file:///tmp/build/80754af9/joblib_1607970656719/work
json5==0.9.5
jsonschema @ file:///tmp/build/80754af9/jsonschema_1602607155483/work
jupyter==1.0.0
jupyter-client @ file:///tmp/build/80754af9/jupyter_client_1601311786391/work
jupyter-console @ file:///tmp/build/80754af9/jupyter_console_1598884538475/work
jupyter-core @ file:///C:/ci/jupyter_core_1606130908768/work
jupyterlab==2.2.6
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
jupyterlab-server @ file:///tmp/build/80754af9/jupyterlab_server_1594164409481/work
keyring @ file:///C:/ci/keyring_1608756141086/work
kiwisolver @ file:///C:/ci/kiwisolver_1603996595157/work
lazy-object-proxy @ file:///C:/b/work
libarchive-c==2.9
llvmlite==0.34.0
locket==0.2.0
lxml @ file:///C:/ci/lxml_1606516935960/work
MarkupSafe @ file:///C:/ci/markupsafe_1594405949945/work
matplotlib @ file:///C:/ci/matplotlib-base_1603356257853/work
mccabe==0.6.1
menuinst==1.4.16
mistune @ file:///C:/ci/mistune_1594373272338/work
mkl-fft==1.2.0
mkl-random==1.1.1
mkl-service==2.3.0
mock @ file:///tmp/build/80754af9/mock_1607622725907/work
more-itertools @ file:///tmp/build/80754af9/more-itertools_1605111547926/work
mpmath==1.1.0
msgpack @ file:///C:/ci/msgpack-python_1607960780714/work
multipledispatch==0.6.0
mypy-extensions==0.4.3
navigator-updater==0.2.1
nbclient @ file:///tmp/build/80754af9/nbclient_1602783176460/work
nbconvert @ file:///C:/ci/nbconvert_1601914921407/work
nbformat @ file:///tmp/build/80754af9/nbformat_1602783287752/work
nest-asyncio @ file:///tmp/build/80754af9/nest-asyncio_1606153767164/work
networkx @ file:///tmp/build/80754af9/networkx_1598376031484/work
nltk @ file:///tmp/build/80754af9/nltk_1592496090529/work
nose @ file:///tmp/build/80754af9/nose_1606773131901/work
notebook @ file:///C:/ci/notebook_1608829952595/work
numba==0.51.2
numexpr @ file:///C:/ci/numexpr_1607678904271/work
numpy @ file:///C:/ci/numpy_and_numpy_base_1603468620949/work
numpydoc @ file:///tmp/build/80754af9/numpydoc_1605117425582/work
oauthlib==3.1.0
olefile==0.46
openpyxl @ file:///tmp/build/80754af9/openpyxl_1598113097404/work
packaging @ file:///tmp/build/80754af9/packaging_1607971725249/work
pandas @ file:///C:/ci/pandas_1608063532995/work
pandocfilters @ file:///C:/ci/pandocfilters_1605102427207/work
paramiko @ file:///tmp/build/80754af9/paramiko_1598886428689/work
parso==0.7.0
partd==1.1.0
path @ file:///C:/ci/path_1607537303146/work
pathlib2 @ file:///C:/ci/pathlib2_1607025068091/work
pathspec==0.7.0
pathtools==0.1.2
patsy==0.5.1
pep8==1.7.1
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
Pillow @ file:///C:/ci/pillow_1603821929285/work
pkginfo==1.6.1
pluggy==0.13.1
ply==3.11
prometheus-client @ file:///tmp/build/80754af9/prometheus_client_1606344362066/work
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1602688806899/work
proto-plus==1.13.0
protobuf==3.14.0
psutil @ file:///C:/ci/psutil_1598352273540/work
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1605560620615/work/dist/ptyprocess-0.6.0-py2.py3-none-any.whl
py @ file:///tmp/build/80754af9/py_1607971587848/work
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.6.0
pycosat==0.6.3
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
pycrypto==2.6.1
pycurl==7.43.0.6
pydocstyle @ file:///tmp/build/80754af9/pydocstyle_1598885001695/work
pyerfa @ file:///C:/ci/pyerfa_1606860310830/work
pyflakes==2.2.0
Pygments @ file:///tmp/build/80754af9/pygments_1607368905949/work
pylint @ file:///C:/ci/pylint_1598605958085/work
pyls-black @ file:///tmp/build/80754af9/pyls-black_1607553132291/work
pyls-spyder @ file:///tmp/build/80754af9/pyls-spyder_1608134179673/work
PyNaCl @ file:///C:/ci/pynacl_1595009241355/work
pyodbc===4.0.0-unsupported
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1608057966937/work
pyparsing==2.4.7
pyreadline==2.1
pyrsistent @ file:///C:/ci/pyrsistent_1600123688363/work
PySocks @ file:///C:/ci/pysocks_1594394709107/work
pytest==0.0.0
python-dateutil==2.8.1
python-jsonrpc-server @ file:///tmp/build/80754af9/python-jsonrpc-server_1600278539111/work
python-language-server @ file:///tmp/build/80754af9/python-language-server_1607972495879/work
pytz @ file:///tmp/build/80754af9/pytz_1608922264688/work
PyWavelets @ file:///C:/ci/pywavelets_1601658407053/work
pywin32==227
pywin32-ctypes @ file:///C:/ci/pywin32-ctypes_1594392691209/work
pywinpty==0.5.7
PyYAML==5.3.1
pyzmq==20.0.0
QDarkStyle==2.8.1
QtAwesome @ file:///tmp/build/80754af9/qtawesome_1602272867890/work
qtconsole @ file:///tmp/build/80754af9/qtconsole_1600870028330/work
QtPy==1.9.0
regex @ file:///C:/ci/regex_1606691216163/work
requests @ file:///tmp/build/80754af9/requests_1608241421344/work
requests-oauthlib==1.2.0
rope @ file:///tmp/build/80754af9/rope_1602264064449/work
rsa @ file:///tmp/build/80754af9/rsa_1596998415516/work
Rtree==0.9.4
ruamel-yaml==0.15.87
scikit-image==0.17.2
scikit-learn @ file:///C:/ci/scikit-learn_1598376983131/work
scipy @ file:///C:/ci/scipy_1597686737426/work
seaborn @ file:///tmp/build/80754af9/seaborn_1608578541026/work
selenium==3.141.0
Send2Trash @ file:///tmp/build/80754af9/send2trash_1607525499227/work
simple-salesforce==0.74.2
simplegeneric==0.8.1
simplejson==3.17.0
singledispatch @ file:///tmp/build/80754af9/singledispatch_1602523705405/work
six @ file:///C:/ci/six_1605205426665/work
sklearn==0.0
snowballstemmer==2.0.0
sortedcollections==1.2.1
sortedcontainers @ file:///tmp/build/80754af9/sortedcontainers_1606865132123/work
soupsieve @ file:///tmp/build/80754af9/soupsieve_1607965878077/work
Sphinx @ file:///tmp/build/80754af9/sphinx_1608836605859/work
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
sphinxcontrib-websupport @ file:///tmp/build/80754af9/sphinxcontrib-websupport_1597081412696/work
spyder @ file:///C:/b/work
spyder-kernels @ file:///C:/ci/spyder-kernels_1608560839696/work
SQLAlchemy @ file:///C:/ci/sqlalchemy_1608243783929/work
statsmodels==0.12.1
sympy @ file:///C:/ci/sympy_1608137734695/work
tables==3.6.1
tabpy==1.1.0
tblib @ file:///tmp/build/80754af9/tblib_1597928476713/work
terminado==0.9.1
testpath==0.4.4
textblob==0.15.3
threadpoolctl @ file:///tmp/tmp9twdgx9k/threadpoolctl-2.1.0-py3-none-any.whl
three-merge @ file:///tmp/build/80754af9/three-merge_1607553261110/work
tifffile==2020.10.1
toml @ file:///tmp/build/80754af9/toml_1592853716807/work
toolz @ file:///tmp/build/80754af9/toolz_1601054250827/work
tornado @ file:///C:/ci/tornado_1606935947090/work
tqdm @ file:///tmp/build/80754af9/tqdm_1608922753628/work
traitlets @ file:///tmp/build/80754af9/traitlets_1602787416690/work
typed-ast==1.4.1
typing-extensions @ file:///tmp/build/80754af9/typing_extensions_1598376058250/work
ujson @ file:///C:/ci/ujson_1602523369547/work
unicodecsv==0.14.1
uritemplate==3.0.0
urllib3 @ file:///tmp/build/80754af9/urllib3_1606938623459/work
watchdog @ file:///C:/ci/watchdog_1606939375616/work
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
webencodings==0.5.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
win-inet-pton @ file:///C:/ci/win_inet_pton_1605306165655/work
win-unicode-console==0.5
wincertstore==0.2
wrapt==1.11.2
xlrd @ file:///tmp/build/80754af9/xlrd_1608072521494/work
XlsxWriter @ file:///tmp/build/80754af9/xlsxwriter_1602692860603/work
xlwings==0.21.4
xlwt==1.3.0
xmltodict==0.12.0
yapf @ file:///tmp/build/80754af9/yapf_1593528177422/work
zict==2.0.0
zipp @ file:///tmp/build/80754af9/zipp_1604001098328/work
zope.event==4.5.0
zope.interface @ file:///C:/ci/zope.interface_1606922318101/work

![116](https://user-images.githubusercontent.com/22087831/109324064-30ed2080-7822-11eb-813a-1c3d27dbb640.PNG)

**Comment by plamut** [comment]
@xuanzee Thanks for all the details.

Running the same code, I could still not reproduce the issue using the package versions from the `pip` output. However, reproduction was successful after forcefully installing `google-resumable-media==0.5.1` and restarting the Jupyter kernel.

I then installed `google-resumable-media==1.2.0` _without_ restarting the kernel. The "unexpected argument" error was still reproducible, even though `pip freeze` now reported the version `1.2.0`.

It appears that the Jupyter kernel needs to be restarted, as it's most likely using a different `google-resumable-media` version than the version reported by `pip`.

**Comment by tswast** [comment]
Closing, as I believe @plamut 's advice to restart the kernel after installing the package should resolve the version issue.
