### ISSUE TITLE
get_job location parameter 'us-east1' error

### ISSUE THREAD

**Issue by julianofranco** [googleapis/python-bigquery#499]
When I try to execute the method get_job passing as argument location='us-east1' in the BigQuery via Python API, it gives me 

`can only concatenate str (not "int") to str`

location='US' works, but my job is in another location.

**Example:**

```
client = bigquery.Client(project=project_id)
job = client.get_job(ak, location='us-east1')
```
Response:

```
can only concatenate str (not "int") to str
127.0.0.1 - - [28/Jan/2021 18:37:46] "GET /getStatus/7542379a-926d-4b95-a827-391be2fa3c20 HTTP/1.1" 200 -
```

I've tryed location='us-east' and "works" but gives me a response that the location doesn't exists

`400 GET https://bigquery.googleapis.com/bigquery/v2/projects/my-project/jobs/7542379a-926d-4b95-a827-391be2fa3c20?projection=full&location=us-east&prettyPrint=false: Invalid value for location: us-east is not a valid value`

this is my code

```
def select_and_update_message_bq(ak):
    try:
        client = bigquery.Client(project=project_id)
        job = client.get_job(ak, location='us-east1')  # API request

        now_datetime = str(datetime.datetime.now())

        if job.state in ["PENDING", "RUNNING", "DONE"]:

            query = f"UPDATE `" + project_id + "." + requisition_dataset + "." + requisition_table + "` "\
            "SET STATUS = \'" + job.state + "\' , " \
            "LAST_UPDATE = \'" + now_datetime + "\', " \
            "REQUEST_COST = \'" + job.total_bytes_processed + "\', " \
            "SOURCE_TARGET = \'" + job.destination_uris + "\', " \
            "WHERE AK = " \
            + "\'" + ak + "\';"

            query_job = client.query(query, location="us-east1")

            if query_job.done():
                return job.state, job.destination_uris

        query = f"SELECT STATUS, SOURCE_TARGET FROM `" + project_id + "." + requisition_dataset + "." + requisition_table + "` "\
            " WHERE AK = " \
            + "\'" + ak + "\';"

        query_job = client.query(query)

        if query_job.done():
            for row in query_job:
            # Row values can be accessed by field name or index.
                return row[0], row[1]
        
    except HttpError as e:
        return json.loads(e.content).get('error').get('errors')[0].get('reason'), ""
    except Exception as e:
        print (e)
        return "NOT FOUND", ""
        
    return "NOT INSERTED", ""

```

**Environment details**

Flask
google-cloud-bigquery
google-cloud-logging
gunicorn
google-api-python-client

Linux julianofranco 5.8.0-40-generic #45~20.04.1-Ubuntu SMP Fri Jan 15 11:35:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
pip 20.3.3 from /home/julianofranco/.local/lib/python3.8/site-packages/pip (python 3.8)

**Comment by julianofranco** [comment]
Sorry guys, I think I found the problem, is not in client.get_job is in the query = f"UPDATE ...

Sorry for incovenience

**Comment by plamut** [comment]
@julianofranco No worries, I'm glad you managed to find the problem.

I would advise, however, to not construct a query by directly concatenating dynamic values, but instead use [query parameters](https://cloud.google.com/bigquery/docs/parameterized-queries#python) for that.

**Comment by plamut** [comment]
Closing, as the solution has been found.

**Comment by julianofranco** [comment]
> @julianofranco No worries, I'm glad you managed to find the problem.
> 
> I would advise, however, to not construct a query by directly concatenating dynamic values, but instead use [query parameters](https://cloud.google.com/bigquery/docs/parameterized-queries#python) for that.

Thank you again. Will work on that.
