### ISSUE TITLE
TypeError: to_pandas() got an unexpected keyword argument 'timestamp_as_object'

### ISSUE THREAD

**Issue by sdbeuf** [googleapis/python-bigquery#519]
## Environment details

  - OS type and version: 1.5.29-debian10
  - Python version: 3.7
  - `google-cloud-bigquery` version: 2.8.0

I'm provisioning a dataproc cluster which gets the data from BigQuery into a pandas dataframe. 
As my data is growing I was looking to boost the performance and heard about using the BigQuery storage client. 

I had the same problem in the past and this was solved by setting the google-cloud-bigquery to version 1.26.1. 
If I use that version I get the following message. 
 ```
/opt/conda/default/lib/python3.7/site-packages/google/cloud/bigquery/client.py:407: UserWarning: Cannot create BigQuery Storage client, the dependency google-cloud-bigquery-storage is not installed.
  "Cannot create BigQuery Storage client, the dependency " 
```
The code snippet executes but at a way slower rate. If I do not specify the pip version, I encounter the following error. 

## Steps to reproduce

  1. Cluster creation on dataproc
 ```
gcloud dataproc clusters create testing-cluster  --region=europe-west1  --zone=europe-west1-b  --master-machine-type n1-standard-16  --single-node  --image-version 1.5-debian10  --initialization-actions gs://dataproc-initialization-actions/python/pip-install.sh  --metadata 'PIP_PACKAGES=elasticsearch google-cloud-bigquery google-cloud-bigquery-storage pandas pandas_gbq'
```
  2. Execute the Following script on the cluster
```
bqclient = bigquery.Client(project=project)
    job_config = bigquery.QueryJobConfig(
        query_parameters=[
            bigquery.ScalarQueryParameter("query_start", "STRING", str('2021-02-09 00:00:00')),
            bigquery.ScalarQueryParameter("query_end", "STRING", str('2021-02-09 23:59:59.99')),
        ]
    )
    df = bqclient.query(query, job_config=job_config).to_dataframe(create_bqstorage_client=True)
```
```
2021-02-11 10:10:14,069 - preprocessing logger initialized
2021-02-11 10:10:14,069 - arguments = [file, arg1, arg2, arg3, arg4, project_id, arg5, arg6]
Traceback (most recent call last):
  File "/tmp/782503bcc80246258560a07d2179891f/immo_preprocessing-pageviews_kyero.py", line 104, in <module>
    df = bqclient.query(base_query, job_config=job_config).to_dataframe(create_bqstorage_client=True)
  File "/opt/conda/default/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1333, in to_dataframe
    date_as_object=date_as_object,
  File "/opt/conda/default/lib/python3.7/site-packages/google/cloud/bigquery/table.py", line 1793, in to_dataframe
    df = record_batch.to_pandas(date_as_object=date_as_object, **extra_kwargs)
  File "pyarrow/array.pxi", line 414, in pyarrow.lib._PandasConvertible.to_pandas
TypeError: to_pandas() got an unexpected keyword argument 'timestamp_as_object'
```

Using the pandas-gbq version gives exaclty the same error

```
    query_config = {
        'query': {
            'parameterMode': 'NAMED',
            'queryParameters': [
                {
                    'name': 'query_start',
                    'parameterType': {'type': 'STRING'},
                    'parameterValue': {'value': str('2021-02-09 00:00:00')}
                },
                {
                    'name': 'query_end',
                    'parameterType': {'type': 'STRING'},
                    'parameterValue': {'value': str('2021-02-09 23:59:59.99')}
                },
            ]
        }
    }
df = pd.read_gbq(base_query, configuration=query_config, progress_bar_type='tqdm',
                             use_bqstorage_api=True)
```

```
2021-02-11 09:21:19,532 - preprocessing logger initialized
2021-02-11 09:21:19,532 - arguments = [file, arg1, arg2, arg3, arg4, project_id, arg5, arg6]
started
Downloading: 100%|██████████| 3107858/3107858 [00:14<00:00, 207656.33rows/s]
Traceback (most recent call last):
  File "/tmp/1830d5bcf198440e9e030c8e42a1b870/immo_preprocessing-pageviews.py", line 98, in <module>
    use_bqstorage_api=True)
  File "/opt/conda/default/lib/python3.7/site-packages/pandas/io/gbq.py", line 193, in read_gbq
    **kwargs,
  File "/opt/conda/default/lib/python3.7/site-packages/pandas_gbq/gbq.py", line 977, in read_gbq
    dtypes=dtypes,
  File "/opt/conda/default/lib/python3.7/site-packages/pandas_gbq/gbq.py", line 536, in run_query
    user_dtypes=dtypes,
  File "/opt/conda/default/lib/python3.7/site-packages/pandas_gbq/gbq.py", line 590, in _download_results
    **to_dataframe_kwargs
  File "/opt/conda/default/lib/python3.7/site-packages/google/cloud/bigquery/table.py", line 1793, in to_dataframe
    df = record_batch.to_pandas(date_as_object=date_as_object, **extra_kwargs)
  File "pyarrow/array.pxi", line 414, in pyarrow.lib._PandasConvertible.to_pandas
TypeError: to_pandas() got an unexpected keyword argument 'timestamp_as_object'

```

**Comment by plamut** [comment]
> TypeError: to_pandas() got an unexpected keyword argument 'timestamp_as_object'

I remember this, `timestamp_as_object` argument was [added](https://github.com/googleapis/python-bigquery/commit/8209203e967f0624ad306166c0af6f6f1027c550) to fix the issue with converting timestamp values to nanosecond precision, but it requires `pyarrow>=1.0`.

What's the `pyarrow` version installed and can you first try upgrading it?

Regarding the warning:
> /opt/conda/default/lib/python3.7/site-packages/google/cloud/bigquery/client.py:407: UserWarning: Cannot create BigQuery Storage client, the dependency google-cloud-bigquery-storage is not installed.
 "Cannot create BigQuery Storage client, the dependency " 


If `google-cloud-bigquery-storage` extra is not installed, the client cannot use the faster BQ Storage API, and falls back to the slower REST API. This can be solved by installing the bigquery client with the `bqstorage` extra, e.g.:
```
google-cloud-bigquery[bqstorage] == 2.8.0
```

@SamColibry Does that solve the issue you are facing?

**Comment by emkornfield** [comment]
If the dataproc version is using the pyspark with pyarrow, the version is quite old, you will likely also need to set the compatibility environment variable: https://spark.apache.org/docs/3.0.0-preview/sql-pyspark-pandas-with-arrow.html#compatibiliy-setting-for-pyarrow--0150-and-spark-23x-24x

**Comment by sdbeuf** [comment]
> If the dataproc version is using the pyspark with pyarrow, the version is quite old, you will likely also need to set the compatibility environment variable: https://spark.apache.org/docs/3.0.0-preview/sql-pyspark-pandas-with-arrow.html#compatibiliy-setting-for-pyarrow--0150-and-spark-23x-24x

I created the cluster once again and by default it had (freshly installed) pyarrow 0.15.0. I manually set it to the latest (3.0.0) and took a look at the environment variable. 
In the release notes of dataproc they had put the environment variable by default. 
https://cloud.google.com/dataproc/docs/release-notes
This solved the issue.
