### ISSUE TITLE
Schema API should return partitioning and clustering information.

### ISSUE THREAD

**Issue by yantrikskaran** [googleapis/python-bigquery#531]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
 **Describe the solution you'd like**
 **Describe alternatives you've considered**
 **Additional context**

What I want to do using big query API.
1 - Want to create a backup of a table
2 - Get table schema, partitioning and clustering information.
3 - Drop the table.
4 - Create the table using table info captured in step 2.

Problem is when I am using below code I just get column information.
table_ref = bigquery.TableReference.from_string(table_name)
print(client.get_table(table_ref).schema)

Is there any way to achieve this using any exiting table information.

**Comment by yantrikskaran** [comment]
@plamut looking for some urgent help here.

**Comment by plamut** [comment]
@yantrikskaran Sorry, I only saw your message today, the first work day after it was posted.

A successful call to [tables.get](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables/get) returns a [Table](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#resource-table) which among other things contains schema, partitioning, and clustering information (check e.g. the `clustering_fields`  and `partition*` attributes). However, you might also want to look at the [copy jobs](https://cloud.google.com/bigquery/docs/managing-tables#copying_a_single_source_table) that can achieve the same with much less hassle.

Does that help with your use case?

**Comment by yantrikskaran** [comment]
@plamut Let have a look at tables.get api. Will confirm if that helps.

Can a copy job create an empty table? My primary objective is to create a empty table.

**Comment by yantrikskaran** [comment]
@plamut I am able to achieve my objective.
1. - I created a copy using copy_table.
2. - Then using query and writing output to same table.
source_table ='XYZ'
_table_id = f"{project_id}.{_dataset}.{source_table}"
query = f"SELECT * FROM {_table_id} LIMIT 0"
 job_config = bigquery.QueryJobConfig(destination=_table_id, write_disposition='WRITE_TRUNCATE')

**Comment by yantrikskaran** [comment]
As I got the workaround. Hence closing the issue.

**Comment by plamut** [comment]
I'm glad that it worked for you!

**Comment by yantrikskaran** [comment]
I would still like to have a feature like copy table with or without data. @plamut See if this can be done.

**Comment by plamut** [comment]
@yantrikskaran If I understood correctly, you mean copying the table (i.e. replicate its schema), but also having an option to control whether or not to migrate the table data, too?

**Comment by yantrikskaran** [comment]
> @yantrikskaran If I understood correctly, you mean copying the table (i.e. replicate its schema), but also having an option to control whether or not to migrate the table data, too?

Yes. Indeed.

**Comment by plamut** [comment]
Understood. Will ask what the canonical advice is here, and come back when get new info.

**Comment by plamut** [comment]
@yantrikskaran Update: To avoid copying the entire table and then truncating its data, the most sensible approach is actually your initial approach - fetch the table information, determine its schema, partitioning, clustering, etc., and create a new table using this info.

Copy jobs cannot create an empty table, unfortunately, the copy the table and its data.

**Comment by yantrikskaran** [comment]
> @yantrikskaran Update: To avoid copying the entire table and then truncating its data, the most sensible approach is actually your initial approach - fetch the table information, determine its schema, partitioning, clustering, etc., and create a new table using this info.
> 
> Copy jobs cannot create an empty table, unfortunately, the copy the table and its data.
> 
> Copying the table schema without its data is also not something that's on the feature roadmap, at least not at the time of writing this.

@plamut Can the direct response of tables.get can be used to create a table instead of checking what schema, partitioning, clustering, labels etc. As each table will have different set of attributes. 
It will be great where we can directly create table using the response of tables.get.

**Comment by plamut** [comment]
>  Can the direct response of tables.get can be used to create a table instead of checking what schema, partitioning, clustering, labels etc.

@yantrikskaran Unfortunately no, at the moment there is no such feature neither in the client library not on the backend (in terms of some API endpoint). A custom user code would be needed here to automate such task.

> It will be great where we can directly create table using the response of tables.get.

Noted, I will forward it as a feature request to consider.

**Comment by yantrikskaran** [comment]
> > Can the direct response of tables.get can be used to create a table instead of checking what schema, partitioning, clustering, labels etc.
> 
> @yantrikskaran Unfortunately no, at the moment there is no such feature neither in the client library not on the backend (in terms of some API endpoint). A custom user code would be needed here to automate such task.
> 
> > It will be great where we can directly create table using the response of tables.get.
> 
> Noted, I will forward it as a feature request to consider.

@plamut Have you created a feature request for this issue?

**Comment by plamut** [comment]
@yantrikskaran I brought that topic up at the meeting last week, but I don't have direct insight into the internal roadmap (I'm merely an external maintainer). The response, however,  was that such a feature is currently not on the roadmap and is not planned.
