### ISSUE TITLE
Big Query not using query cache when the same query is executed again. 

### ISSUE THREAD

**Issue by yantrikskaran** [googleapis/python-bigquery#537]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-bigquery/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version:
  - Python version: `python --version`
  - pip version: `pip --version`
  - `google-cloud-bigquery` version: `pip show google-cloud-bigquery`

#### Steps to reproduce

  1. ?
  2. ?

#### Code example

I have a query which read about 25GB of data and produce around 1 TB of data. So as suggested by Big Query I am writing the result to a permanent table as below.

_table_id = f"TEST_XXX"
bq = bigquery.Client()
job_config = bigquery.QueryJobConfig(destination=_table_id, write_disposition='WRITE_TRUNCATE')
query_job = bq.query(query, job_config=job_config)
result = query_job.result()

When I re-run the same query, It is not getting result from query cache (destination table), instead it is re-executing the query.

As per the documents big query cache result for 24hrs.
#### Stack trace
```
# example
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by yantrikskaran** [comment]
@plamut I am missing something here?

**Comment by plamut** [comment]
@yantrikskaran Since `destination` is explicitly given, the temporary (cached) results table is not used. Quoting the [docs](https://cloud.google.com/bigquery/docs/cached-results):

> BigQuery writes all query results to a table. The table is either explicitly identified by the user (a destination table), or it is a temporary, cached results table.

Moreover, using the cache is subject to a few [limitations](https://cloud.google.com/bigquery/docs/cached-results#limitations). One of the limitations is the result size:
> For query results to persist in a cached results table, the result set must be smaller than the maximum response size

The maximum response size is 10 GB (compressed) ([quotas and limitations](https://cloud.google.com/bigquery/quotas#query_jobs)) - it appears that your query's result exceed that?
(presumably there's enough variety in the data so that it can't be compressed to < 10 GB)

**Comment by yantrikskaran** [comment]
@plamut I was thinking the same.

**Comment by plamut** [comment]
@yantrikskaran I suppose the issue can be closed now, as the observed behavior is consistent with the docs? Or is there anything else you would like us to to look at?

**Comment by yantrikskaran** [comment]
Closing this Issue
