### ISSUE TITLE
Support for with statement for Client class

### ISSUE THREAD

**Issue by nnaka2992** [googleapis/python-bigquery#538]
**Is your feature request related to a problem? Please describe.**
Currently, the Client class does not support with statement. Supporting with statement would make programmers easy to write and maintenance their code.

 **Describe the solution you'd like**
Add `__enter__` and `__exit__` methods to enable with statement. Works as following would be perfect.
```
with bigquery.Client(location='Asia/Tokyo') as client:
    query_job = client.query("SELECT CURRENT_DATE('Asia/Tokyo');")
```

**Comment by plamut** [comment]
@nnaka2992 What would be the expected behavior here?

Presumably, `__enter__()` would simply return the client instance, i.e. `self`, and `__exit__()` would invoke the client's `close()` method?

This could be added, yes, thanks for the suggestion.

**Comment by nnaka2992** [comment]
Yes, that is what i meant. just return self and close is good enough.
thanks

**Comment by plamut** [comment]
OK great, this is exactly what I did in the PR, thanks for confirming!
