### ISSUE TITLE
Is there any way to convert a BigQuery client query result to a DASK dataframe instead of pandas dataframe?

### ISSUE THREAD

**Issue by AyhmRB** [googleapis/python-bigquery#555]
-Title-
[I've asked this question on kaggle](https://www.kaggle.com/questions-and-answers/226512), but haven't gotten any replies.
Any help is appreciated, thanks in advance :)

**Comment by tswast** [comment]
There's some discussion here: https://github.com/dask/dask/issues/3121

The backend has made some changes to make data more evenly distributed across streams since I last commented on that issue, but I haven't tried it out yet.

**Comment by AyhmRB** [comment]
Thanks @tswast, I'll try it out sooner or later, will re-open this issue if it doesn't work :)
