### ISSUE TITLE
add ability to unset policy tags (and description?) in schema fields

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#558]
**Is your feature request related to a problem? Please describe.**

I noticed in https://github.com/googleapis/python-bigquery/pull/557 that we don't send the policy tags property if none are set in SchemaField. I believe this tells the backend not to make any updates to the policy tags property. This means it's not possible to _unset_ policy tags from Python.

(Note: I haven't verified this, so some system tests / samples should be written for this use case)

 **Describe the solution you'd like**

Similar to what I did for `description` in https://github.com/googleapis/python-bigquery/pull/557, we should disambiguate between unset policy tags and empty / none for policy tags.

 **Describe alternatives you've considered**

We could make the update fields property more fine-grained, such as `schema.policytags` in order to force a sub-property to be included. This feels overly complicated, though.

 **Additional context**

N/A

**Comment by tswast** [comment]
Since SchemaField is read-only, we could also make the change to use `_properties` for all properties without making breaking changes, which would align it with our other resource classes.

**Comment by plamut** [comment]
> I noticed in #557 that we don't send the policy tags property if none are set in SchemaField. I believe this tells the backend not to make any updates to the policy tags property. This means it's not possible to unset policy tags from Python.
>
> (Note: I haven't verified this, so some system tests / samples should be written for this use case)

I tried it and if `schema_field.policy_tags` is set from "something" to `None`, it is simply omitted from the API representation, meaning that policy tags indeed **not** get unset.
