### ISSUE TITLE
Job ID Mismatch: Leading to 404 job not found when running on AI platform

### ISSUE THREAD

**Issue by ayushmi** [googleapis/python-bigquery#567]
I have written a python job for executing a query to fetch the data form BigQuery. 

When I run the job from my local system it works and finishes with success fetching me all the required data. 

But when I run it on the AI platform I see that job_id published in the job logs of AI platform is different from the job_id as seen on the project queries on BigQuery UI. The difference between the id's is the region. AI platform job_id is like: '{project_id}:{value}' whereas BigQuery UI shows it as '{project_id}:{region}.{value}

Here is the AI platform submit command that I am using: 

`
gcloud --project "project_name" --no-user-output-enabled ai-platform jobs submit training "job_name"
    --config config.yaml 
    --packages "dist/..." 
    --module-name trainer.task 
    --region asia-south1 
    --job-dir "..."
`

Here is my job code: 
`from google.cloud import bigquery`
`bq_client = bigquery.Client(project="")`
`job_config = bigquery.QueryJobConfig()`
`query="select ..."`
`query_job = bq_client.query(query, job_config=job_config)`
`query_job.result()`
`

**Comment by tswast** [comment]
Note: When you say "region", the job class refers to this as `location`, as there are multi-region locations such as US and EU. It is exposed on the job objects in the [location property](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.job.QueryJob.html#google.cloud.bigquery.job.QueryJob.location). This can also be passed to the [query method](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.client.Client.html#google.cloud.bigquery.client.Client.query) via the location parameter.

> But when I run it on the AI platform I see that job_id published in the job logs of AI platform is different from the job_id as seen on the project queries on BigQuery UI. 

@ayushmi Can you be more specific? I don't recall any logging that occurs with the job ID in this library.

**Comment by ayushmi** [comment]
Yes I went through the docs and tried `location` property in query method. 

this way: `query_job = bq_client.query(query, job_config=job_config, location="asia-south1")` 
but got the following error: `TypeError: query() got an unexpected keyword argument 'location'` 

I guess maybe because of version issue. Here are the versions I am using for google.cloud:
`google==3.0.0
google-api-core==1.26.0
google-auth==1.27.0
google-cloud==0.34.0
google-cloud-bigquery==2.9.0
google-cloud-core==1.6.0
google-cloud-storage==1.36.0
google-crc32c==1.1.2
google-resumable-media==1.2.0
googleapis-common-protos==1.52.0`

logs I see is python StackTrace which gives url of google api being hit for fetching the job when I execute query method. URL has job_id which I presume is the one that should be generated when job is created.

**Comment by ayushmi** [comment]
Here is stacktrace for reference

   `File "/root/.local/lib/python3.5/site-packages/trainer/get_data.py", line 64, in run_query`
    `query_job.result()`
  `File "/usr/local/lib/python3.5/dist-packages/google/cloud/bigquery/job.py", line 1945, in result`
    `super(QueryJob, self).result(timeout=timeout)`
  `File "/usr/local/lib/python3.5/dist-packages/google/cloud/bigquery/job.py", line 528, in result`
    `return super(_AsyncJob, self).result(timeout=timeout)`
  `File "/usr/local/lib/python3.5/dist-packages/google/api_core/future/polling.py", line 106, in result`
    `self._blocking_poll(timeout=timeout)`
  `File "/usr/local/lib/python3.5/dist-packages/google/cloud/bigquery/job.py", line 1919, in _blocking_poll`
    `super(QueryJob, self)._blocking_poll(timeout=timeout)`
  `File "/usr/local/lib/python3.5/dist-packages/google/api_core/future/polling.py", line 85, in _blocking_poll`
    `retry_(self._done_or_raise)()`
  `File "/usr/local/lib/python3.5/dist-packages/google/api_core/retry.py", line 260, in retry_wrapped_func`
    `on_error=on_error,`
  `File "/usr/local/lib/python3.5/dist-packages/google/api_core/retry.py", line 177, in retry_target`
    `return target()`
  `File "/usr/local/lib/python3.5/dist-packages/google/api_core/future/polling.py", line 62, in _done_or_raise`
    `if not self.done():`
  `File "/usr/local/lib/python3.5/dist-packages/google/cloud/bigquery/job.py", line 1907, in done`
    `project=self.project, timeout_ms=timeout_ms)`
  `File "/usr/local/lib/python3.5/dist-packages/google/cloud/bigquery/client.py", line 499, in _get_query_results`
    `retry, method='GET', path=path, query_params=extra_params)`
  `File "/usr/local/lib/python3.5/dist-packages/google/cloud/bigquery/client.py", line 271, in _call_api`
    `return call()`
  `File "/usr/local/lib/python3.5/dist-packages/google/api_core/retry.py", line 260, in retry_wrapped_func`
    `on_error=on_error,`
  `File "/usr/local/lib/python3.5/dist-packages/google/api_core/retry.py", line 177, in retry_target`
    `return target()`
  `File "/usr/local/lib/python3.5/dist-packages/google/cloud/_http.py", line 293, in api_request`
    `raise exceptions.from_http_response(response)`
`google.api_core.exceptions.NotFound: 404 GET`
`https://www.googleapis.com/bigquery/v2/projects/{project_id}/queries/{some_uuid}?maxResults=0: Not found: Job {project-id}:{job_id_hash}`

**Comment by tswast** [comment]
@ayushmi Can you share the value of `google.cloud.bigquery.__version__`? I agree that this sounds like a version mismatch issue.

**Comment by ayushmi** [comment]
`google.cloud.bigquery.__version__` is 2.13.0 on my local system from which this code works. 

I am not sure on AI platform how to check the bigquery version.

**Comment by morgandu** [comment]
For package version mismatch, have you tried include the bigquery version you need as part of the requirement.txt when launching the ai-platform job?
