### ISSUE TITLE
strange behavior of bigquery.Client with joblib multiprocessing 

### ISSUE THREAD

**Issue by tiborsekera** [googleapis/python-bigquery#577]
#### Environment details

  - OS type and version: Debian 4.9 x86_64 GNU/Linux
  - Python version: Python 3.7.6
  - pip version: `pip --version`
  - `google-cloud-bigquery` version: 1.26.1

#### Steps to reproduce

  1. Execute the code as is -> receiving an error:
```
  requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
  2. Execute the code either with commenting out the ".get_table" line or with with n_jobs=1 -> no error.

#### Code example

```python
import google.auth
from google.cloud import bigquery
from joblib import Parallel, delayed, parallel_backend

credentials, _ = google.auth.default(
    scopes=["https://www.googleapis.com/auth/cloud-platform"]
)
bq_client = bigquery.Client(
    location="US", credentials=credentials
)

# if this is commented out -> no problem
table = bq_client.get_table(
    "bigquery-public-data.austin_311.311_service_requests"
)

def do_something():
    query = f"""
    SELECT unique_key FROM `bigquery-public-data.austin_311.311_service_requests`
    LIMIT 3
    """
    query_job = bq_client.query(query)
    df = query_job.to_dataframe()
    print(df)


n_jobs = 2

with parallel_backend("multiprocessing", n_jobs=n_jobs):
    Parallel()(delayed(do_something)() for i in [0, 1])
```

This is a strange behaviour, why is this error happening? Is it a desired behavior or a bug?

Thank you!

**Comment by plamut** [comment]
@tiborsekera This is a very old version of BigQuery client, could you upgrade it to the latest version (`2.13.1` at the time of writing) and see if it fixes the issue?

If that fails, I would also try with creating the client instance inside the `do_something()` function instead of sharing it, perhaps there's some weird quirk related to multiprocessing that hasn't surfaced yet.

Looking forward to the update!

**Comment by tiborsekera** [comment]
Right, with bigquery.__version__  == '2.13.1' I cannot reproduce the error. No issue anymore -> closing
