### ISSUE TITLE
feat: make use of LZ4 in `to_arrow` / `to_dataframe`

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#579]
https://github.com/googleapis/python-bigquery-storage/pull/166 adds a compression option to Arrow streams. This can greatly speed-up some workloads.

Requires `pyarrow >=1.0.0`.

**Comment by tswast** [comment]
Note: since we don't want to bump the minimum `google-cloud-bigquery-storage` just yet, we should do a `hasattr` check or package version check.

**Comment by plamut** [comment]
BTW, this is currently blocked on the BQ Stroage [release](https://github.com/googleapis/python-bigquery-storage/pull/170), we can't use the happy path just yet, except with a pre-release install.

**Comment by plamut** [comment]
Release [done](https://github.com/googleapis/python-bigquery-storage/pull/170), not blocked anymore.
