### ISSUE TITLE
BigQuery: BadRequest exception (Invalid project ID) -- 2021-03-31

### ISSUE THREAD

**Issue by philippefutureboy** [googleapis/python-bigquery#582]
Links to https://github.com/googleapis/nodejs-bigquery/issues/348 , https://github.com/googleapis/google-cloud-python/issues/9194.

The following code

```
    table_name = f'`{project}`.clinic_data_{clinic_id}.marketing_budget'
    create_sql = f"""
        CREATE OR REPLACE TABLE {table_name} (
            clinic_key STRING NOT NULL,
            referrer_key STRING NOT NULL,
            date_key DATE NOT NULL,
            budget_amount FLOAT64
        )
    """
    print("Creating table")
    BigQueryOperator(task_id="create_table_marketing_budget",
                                    sql=create_sql,
                                    use_legacy_sql=False,
                                    ).execute(context=context
```

executed from an Airflow 2.x image (apache/airflow:2.0.1-python3.8) on GKE produces the following logs (and SQL):

```
[2021-03-31 21:13:50,105] {logging_mixin.py:104} INFO - Creating table
[2021-03-31 21:13:50,108] {logging_mixin.py:104} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py:636 DeprecationWarning: This operator is deprecated. Please use `BigQueryInsertJobOperator`.
[2021-03-31 21:13:50,108] {bigquery.py:667} INFO - Executing: 
        CREATE OR REPLACE TABLE `pinkdolphin-prod-4541`.clinic_data_cli1111111111111111111111.marketing_budget (
            clinic_key STRING NOT NULL,
            referrer_key STRING NOT NULL,
            date_key DATE NOT NULL,
            budget_amount FLOAT64
        )
```

Following the DeprecationWarning, I refactored the code to directly use the bigquery client, like so:

```
    client = bigquery.client.Client()

    table_name = f'`{project}`.clinic_data_{clinic_id}.marketing_budget'
    create_sql = f"""
        CREATE OR REPLACE TABLE {table_name} (
            clinic_key STRING NOT NULL,
            referrer_key STRING NOT NULL,
            date_key DATE NOT NULL,
            budget_amount FLOAT64
        )
    """
    print("Creating table")
    create_job = client.query(query=create_sql)
    # await result
    create_job.result()

```
.

Both result in the following error:

```
[2021-03-31 21:38:55,022] {logging_mixin.py:104} INFO - Creating table
[2021-03-31 21:38:55,838] {taskinstance.py:1455} ERROR - 400 GET https://bigquery.googleapis.com/bigquery/v2/projects/%60pinkdolphin-prod-4541%60/datasets/clinic_data_cli1111111111111111111111/tables/marketing_budget?prettyPrint=false: Invalid project ID '`pinkdolphin-prod-4541`'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/integrate.py", line 260, in load_marketing_budget_to_bq
    table = client.get_table(table_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 860, in get_table
    api_response = self._call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 640, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http.py", line 483, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 GET https://bigquery.googleapis.com/bigquery/v2/projects/%60pinkdolphin-prod-4541%60/datasets/clinic_data_cli1111111111111111111111/tables/marketing_budget?prettyPrint=false: Invalid project ID '`pinkdolphin-prod-4541`'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.
```

Note that:

1. The `pinkdolphin-prod-4541` project exists
2. The `clinic_data_cli1111111111111111111111` dataset exists (even though the id here is obfuscated with 1s for security reasons)

#### Environment details

  - OS type and version: docker image: apache/airflow:2.0.1-python3.8
  - Python version: Python 3.8.7
  - pip version:  pip 20.2.3 
  - `google-cloud-bigquery` version: `pip show google-cloud-bigquery`: 
  
```
Name: google-cloud-bigquery
Version: 2.3.1
Summary: Google BigQuery API client library
Home-page: https://github.com/googleapis/python-bigquery
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: <redacted>
Requires: google-cloud-core, google-api-core, protobuf, six, proto-plus, google-resumable-media
Required-by: pandas-gbq
```

#### Other notes

* Following the above error stack I feel like this is not on the client side, but rather on the backend side
* I'm on the clock to deliver our current feature for clients by tomorrow 12:00AM EDT; I know the drill and you guys also have deadlines; this being said a quick response time would be really appreciated ❤️  ❤️

**Comment by philippefutureboy** [comment]
Further info:

**Environment:**

Important environment variables, printed just above the call:

```
GOOGLE_APPLICATION_CREDENTIALS: "/secrets/auth.json",
PROJECT: "pinkdolphin-prod-4541"
```

**Backticks in URL**

The url called, 

```
https://bigquery.googleapis.com/bigquery/v2/projects/%60pinkdolphin-prod-4541%60/datasets/clinic_data_cli1111111111111111111111/tables/marketing_budget?prettyPrint=false
```

Clearly shows the presence of backticks around the project param in the route (`%60` in `%60pinkdolphin-prod-4541%60`). It's most likely the cause of the issue; however it's unclear where that backtick-ed project value is taken from.

**Comment by philippefutureboy** [comment]
Found it!
I completely missed it, but the source wasn't the create table itself, but rather the `table = client.get_table(table_name)` line right after. Turns out `biquery.client.Client().get_table`, does not seem to like the backticks. The[ implementation that parses the str](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.table.TableReference.html#google.cloud.bigquery.table.TableReference.from_string) passed as first argument does not strip backticks when parsing. 

The fix for me was to remove the backtick out of the table_name before passing it to `get_table`.

**Comment by plamut** [comment]
@philippefutureboy The name contains backticks, indeed. Great that you managed to solve that yourself!

Re: unclear traceback - could you elaborate on what part do you think would need improvement? The error message returned from the server is quite detailed (IMHO), and explains how a valid project ID should look like:

> google.api_core.exceptions.BadRequest: 400 GET https://bigquery.googleapis.com/bigquery/v2/projects/%60pinkdolphin-prod-4541%60/datasets/clinic_data_cli1111111111111111111111/tables/marketing_budget?prettyPrint=false: Invalid project ID '`pinkdolphin-prod-4541`'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.

And the key line `table = client.get_table(table_name)` is also present in the traceback?

> Turns out biquery.client.Client().get_table, does not seem to like the backticks. The implementation that parses the str passed as first argument does not strip backticks when parsing.

True, since it's ultimately the backend that decides what a valid name is. Even if the client stripped the backticks, that would only cover one specific subcase, thus the client does not try to duplicate the backend logic, it merely passes the resource names to it as given by the user code.

**Comment by philippefutureboy** [comment]
Hey @plamut!

Thanks for your detailed answer!

Yeah, I guess after rereading the error it seems to be really straightforward -

```
  File "/opt/airflow/dags/integrate.py", line 260, in load_marketing_budget_to_bq
    table = client.get_table(table_name)
```

is pretty clear on the source of the error, and the error itself specifically shows the inclusion of the backtick.
I guess my eyes were tired!

Also agreed with you wrt the design choice not to replicate the behaviour of the backend and let the backend handle the issue. This being said, I think it's confusing to know that when executing SQL, I absolutely need to wrap the project ID in backticks, whereas when using the client I should not use the backticks in the name of the table 🤷‍♂️ 
Maybe update the backend behaviour to also support the syntax used in the SQL?

**Comment by plamut** [comment]
@philippefutureboy 
No worries, things like that happen, especially when rushing to meet a deadline.

> Maybe update the backend behaviour so that valid SQL identifiers are also valid identifiers for the API?

I'll check with the backend team about the proposal. It's probably a long shot (IMO), but I'll see what the response it.

**Comment by philippefutureboy** [comment]
@plamut Thanks a lot! No worries 🤞

**Comment by shollyman** [comment]
Took a look at this as well.

I don't think we want to have the library implementing the checks related to the literals, so passing quoted literals to the get_table method for example isn't going to be the way to handle this.

One thing that might make sense is to have a convenience function that takes a structured TableReference and can emit a valid quoting.  The rules for identifiers are documented here: https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#identifiers 

With this, you could define a TableRefence and invoke the conversion function to get a valid identifier for SQL, but that remains in the user purview and the library doesn't try to interpret anything..
