### ISSUE TITLE
Unable to Set Connection Pool Size

### ISSUE THREAD

**Issue by smills17** [googleapis/python-bigquery#59]
Cloning [this issue](https://github.com/googleapis/google-cloud-python/issues/8449) over from `google-cloud-python` repo per the instructions at the end of the comment chain.

This issue still exists as far as I can tell - I may be wrong and simply am not doing it right, in which case would love some insight as to how this is done - comment chain was unresolved and there appear to be plenty of questions regarding the proper use of these params and how to set them - would love to at least to see an update to some documentation if this does actually work.

A quick recap and example of the issue, [quoting a comment from previous thread](https://github.com/googleapis/google-cloud-python/issues/8449#issuecomment-504397120):

> Now I understand the difference, however I've tried all of these with no change in behavior.

```python
bq._http.adapters['https://']._pool_connections = 200
bq._http.adapters['https://']._pool_maxsize = 200
bq._http.adapters['http://']._pool_maxsize = 200
bq._http.adapters['http://']._pool_connections = 200
bq._http_internal.adapters['https://']._pool_maxsize=100
bq._http_internal.adapters['https://']._pool_connections = 100
bq._http_internal.adapters['http://']._pool_maxsize = 100
bq._http_internal.adapters['http://']._pool_connections = 100
```
>For example if I use 16 threads, I encounter the same warnings. Is there a different syntax I should be using here other than directly modifying these?

Thanks!

**Comment by plamut** [comment]
I was not able to reproduce this issue as reported in the original issue [description](https://github.com/googleapis/google-cloud-python/issues/8449). I started 16 load jobs in parallel, each in its own thread, with each job loading a ~30MB CSV file from Cloud Storage to the target table.

The behavior was the same regardless whether each thread created its own BigQuery client (version 1.24.0), or if a common client instance was shared among them.

@smills17 Can you still reproduce the issue with the latest client library, and if yes, would it be possible to provide a reproducible example? Thanks!

**Comment by plamut** [comment]
@smills17 Friendly ping. Does the issue still persist?

**Comment by pietrodn** [comment]
I was able to change the connection pool size this way:

```python
import requests.adapter
bq = bigquery.Client(project=config.GOOGLE_CLOUD_PROJECT)

# Increase the HTTP pool size to avoid the "Connection pool is full, discarding connection: bigquery.googleapis.com"
adapter = requests.adapters.HTTPAdapter(pool_connections=100, pool_maxsize=100)
bq._http.mount("https://", adapter)
```

**Comment by MCMcCallum** [comment]
Note that both the client requests and the auth requests can cause these errors. To avoid both in the client you must mount 2 adapters:

(example using google cloud storage api, yet to test with bigquery):

```
from google.cloud import storage
import requests

GCS_CLIENT = storage.Client()
adapter = requests.adapters.HTTPAdapter(pool_connections=128, pool_maxsize=128, max_retries=3)
GCS_CLIENT._http.mount("https://", adapter)
GCS_CLIENT._http._auth_request.session.mount("https://", adapter)
```
