### ISSUE TITLE
google.auth.exceptions.TransportError is not being retried

### ISSUE THREAD

**Issue by nitishxp** [googleapis/python-bigquery#620]
Hi, 

Recently i faced an error can you please consider using this exception as a retry one also. Since i have faced this error in one of our production system

https://github.com/googleapis/python-storage/issues/414

**Comment by tswast** [comment]
Based on the context from @busunkim96 in the linked issue, this is a reasonable request. We'll need a PR similar to https://github.com/googleapis/python-bigquery/pull/571 (retry ConnectionError by default)
