### ISSUE TITLE
feat: add DECIMAL and BIGDECIMAL as aliases for NUMERIC and BIGNUMERIC to scalar types enums

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#633]
https://github.com/googleapis/python-bigquery/pull/626#discussion_r621631084

**Comment by tswast** [comment]
On second-thought, these are actually called `NUMERIC` and `BIGNUMERIC` in BigQuery. I don't know if we want to be adding aliases outside of those we already have for Legacy SQL support.

🤔

**Comment by jimfulton** [comment]
But these are defined as valid standard sql aliases here: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#decimal_types

**Comment by jimfulton** [comment]
IMO, this is a bug not a feature. :)

**Comment by jimfulton** [comment]
@tswast shall I address this?

**Comment by tswast** [comment]
Gotcha. I didn't realize the backend had these as aliases. Yes, let's go for it.

**Comment by jimfulton** [comment]
I can't find any use of `SqlParameterScalarTypes`.

I searched:

- the `google` and `test` source directories.
- the internet using google. :)

Is there a reason we think we need this?

**Comment by tswast** [comment]
I'd like to use those in code samples where folks have STRUCT type query parameters with sub-fields

Honestly, it'd be much more useful if we supplemented the class to allow a builder-style construction where we add a `with_name(...)` function that makes a copy of the parameter type but adds a name.

**Comment by tswast** [comment]
Closed by https://github.com/googleapis/python-bigquery/pull/638

**Comment by tswast** [comment]
> "those"

I mean the ScalarQueryParameter type. I've filed https://github.com/googleapis/python-bigquery/issues/642 we can continue the discussion of the feature there.

> "code samples"

Yes, I mean the `samples/` directory. Usually we aim to publish those samples on cloud.google.com/bigquery/docs as well.

> "STRUCT type query parameters with sub-fields" My head just exploded a little. :) I guess this is going to be something like: "select %(foo:STRUCT<INT64,STRING>)s"

That's right! See: https://github.com/googleapis/python-bigquery/issues/463

In addition to what you've written with anonymous sub-fields, it's also possible to give those names.
