### ISSUE TITLE
add support for ParquetOptions for load/external tables

### ISSUE THREAD

**Issue by shollyman** [googleapis/python-bigquery#661]
This FR is to add support for some advanced Parquet options (list inference and enums) when loading data or defining an external table.

Additional information has been shared out of band with library maintainers.

**Comment by curiouserrr** [comment]
In particular, the enumAsString option doesn't appear to be supported in bigquery.LoadJobConfig, though it is available in the BQ CLI and in the dynamic API access library.  It would be very helpful to expose the option in this library too.
