### ISSUE TITLE
Loading BigQuery table with TIME field from Dataframe produces incorrect result

### ISSUE THREAD

**Issue by jimfulton** [googleapis/python-bigquery#667]
See: https://issuetracker.google.com/issues/169230812

**Comment by jimfulton** [comment]
This is blocked by: https://issuetracker.google.com/issues/188699171

I'm 99% sure this is an issue with loading time data from parquet on the server and I can't look at that code. :)

A work around is use CSV to send the data.

**Comment by jimfulton** [comment]
FTR, this is the same as: https://github.com/googleapis/python-bigquery/issues/56

**Comment by tswast** [comment]
Backend bug with TIME support in Parquet loading (178746141)  is reported to be fix in the development server. We should be able remove our client-side workarounds once it rolls out to production.

**Comment by jimfulton** [comment]
Cool. Can I test against the development server?

**Comment by jimfulton** [comment]
The fix has been deployed to prod.
