### ISSUE TITLE
Revert the temporarily adjustment of a failing system test

### ISSUE THREAD

**Issue by plamut** [googleapis/python-bigquery#68]
Once #61 is fixed, the changes from #67 **must** be reverted.

**Comment by meredithslota** [comment]
#61 was closed as a duplicate of https://github.com/googleapis/python-bigquery/issues/56 which was closed with a fix in https://github.com/googleapis/python-bigquery/pull/895 — I think this is no longer blocked.

**Comment by shollyman** [comment]
This was addressed by previous refactors.  Closing.
