### ISSUE TITLE
Not able to use ScriptOptions

### ISSUE THREAD

**Issue by AdityaMaddula** [googleapis/python-bigquery#684]
#### Environment details

  - OS type and version: MacOs
  - Python version: Python 3.6.6
  - pip version: 20.2
  - `google-cloud-bigquery` version: 2.18.0

#### Code example

```python
bigquery.QueryJobConfig(scriptOptions={"statementTimeoutMs": 10})
```

I am looking for a way to set timeouts for SQL statements(if a query takes more than a min we want to abort it. We can cancel it by calling cancel API though, But I am looking for config which aborts it on bigquery side itself. Something like session timeout for snowflake). After searching the documentation, I found https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#ScriptOptions. But looks like it's not supported in 2.18.0.  Is there a way to make this work ?

**Comment by plamut** [comment]
@AdityaMaddula I don't see that in the source code, but it's indeed described in the API docs. At a quick glance it seems that we could add this, yes.
