### ISSUE TITLE
make export statement a configurable option

### ISSUE THREAD

**Issue by NI1993** [googleapis/python-bigquery#692]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
An dedicated option of a job/query would be using the [export statement](https://cloud.google.com/bigquery/docs/reference/standard-sql/other-statements#export_data_statement).
I find this cleaner & prettier compared to the alternative described below. Moreover, it distinguishes nicely the actual querying & the export logic.
 **Describe the solution you'd like**
Perhaps something like:
```
client = bigquery.Client(...)            
raw_sql = "SELECT field1, field2 FROM mydataset.table1 ORDER BY field1 LIMIT 10"
export_option = bigquery.ExportOption(uri='gs://bucket/folder/*.csv', format='CSV', overwrite=true, header=true, field_delimiter=';')
results = client.query(raw_sql, export_options=export_option)
```
 **Describe alternatives you've considered**
Prefix the sql with export statement:
```
client = bigquery.Client(...)            
raw_sql = "SELECT field1, field2 FROM mydataset.table1 ORDER BY field1 LIMIT 10"
raw_sql = "EXPORT DATA OPTIONS(uri='gs://bucket/folder/*.csv', format='CSV', overwrite=true, header=true, field_delimiter=';') AS\n" + raw_sql
results = client.query(raw_sql)
```
 **Additional context**
The goal is processing very large query results using pandas dataframe API (or similar).
Most tools can read from GCS files into a dataframe instance.

**Comment by shollyman** [comment]
SQL mangling like this is something I prefer we avoid in the absence of a proper validator.  Consider what this would do if the raw sql were actually multiple sql statements, for example.

**Comment by plamut** [comment]
@NI1993 Update - as it stands, such feature is currently not planned, I'm afraid. One problem was already mentioned by @shollyman, i.e. what if the SQL text consists of multiple statements. Potential benefits do not outweigh all the problems and edge cases an implementation would encounter, thus closing this.
