### ISSUE TITLE
free(): invalid pointer Aborted error when importing from google.cloud import bigquery  in python

### ISSUE THREAD

**Issue by rituraj17** [googleapis/python-bigquery#695]
I started facing this peculiar issue  while import importing BigQuery in python scripts as well as in the terminal. 
Can anyone help me out here?
I even tried to downgrade the bigquery package from 2.20 to 2.1 its still give me the same error

```
root@f6968ce75f9d:~# python 
Python 3.7.10 (default, May 28 2021, 10:36:10) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import bigquery
free(): invalid pointer
Aborted
```

<img width="858" alt="Screenshot 2021-06-07 at 10 31 45 PM" src="https://user-images.githubusercontent.com/20011105/121060374-2c9cb000-c7e0-11eb-8819-8153137ac41a.png">

**Comment by plamut** [comment]
@rituraj17 This sounds a lot like an [issue](https://github.com/googleapis/python-pubsub/issues/414) opened in the Pub/Sub repo. It's an issue in `grpcio` that has now been [fixed](https://github.com/googleapis/python-pubsub/issues/414#issuecomment-856452925), just not released yet.

Until it's released, does the [workaround](https://github.com/googleapis/python-pubsub/issues/414#issuecomment-844068391) posted in the related issue work for you?
(essentially, `grpc` should be imported before `proto.message`)
```py
import grpc
import proto.message
from google.cloud import bigquery
```

**Comment by plamut** [comment]
This [has been fixed](https://github.com/googleapis/python-pubsub/issues/414#issuecomment-856452925) and release in `grpcio` [1.38.1](https://pypi.org/project/grpcio/1.38.1/). Will update the version pin.
