### ISSUE TITLE
Building the docs breaks (duplicate object description)

### ISSUE THREAD

**Issue by plamut** [googleapis/python-bigquery#75]
I noticed that building the docs locally on `master` fails due to the following error:
> sphinx.errors.SphinxWarning: <workspace_dir>/python-bigquery/google/cloud/bigquery_v2/types.py:docstring of google.cloud.bigquery_v2.types.DeleteModelRequest.dataset_id:1:duplicate object description of google.cloud.bigquery_v2.types.DeleteModelRequest.dataset_id, other instance in gapic/v2/types, use :noindex: for one of them

Checking what gets injected into the `types` module does not reveal anything, the `DeleteModelRequest` type is **not** duplicated.

It turns out that the issue does not occur with the older version of Sphinx (< 3.x), ~~thus it appears as a bug in the Sphinx package itself.~~ A workaround is to pin that dependency to an older version.

Preferably, though, the new warnings emitted in Sphinx 3 should be addressed at their root causes.

**Comment by HemangChothani** [comment]
@plamut  To slove this issue need to add `:noindex:` in one of the `.rst` file which mentioned in the comment. I have tried and it works for me.
This issue is just because they found class from two paths and they don't create a duplicate index for single class.

**Comment by plamut** [comment]
I will see if I can fix everything relatively quickly (fixing one warning reveals other warnings), and at least [one of them](https://github.com/sphinx-doc/sphinx/issues/4447) has not been fixed yet (happens when including the CHANGELOG).

**Comment by HemangChothani** [comment]
Add ` "recommonmark"`  in extensions  in conf.py file, which surely help to resolve CHANGELOG title related warning.

**Comment by plamut** [comment]
Indeed, that was it, thanks. :+1:  I saw that a different parser has already been specified for `.md` files, but the extension itself was not listed under `extensions`, go figure.
