### ISSUE TITLE
Unify the way how unit tests are conditionally skipped

### ISSUE THREAD

**Issue by plamut** [googleapis/python-bigquery#752]
Following the [comment](https://github.com/googleapis/python-bigquery/pull/750#discussion_r667878253), we currently use two different ways of conditionally skipping unit tests that require particular minimum dependency version.

One approach parses the installed version manually:
```py
PANDAS_MINIUM_VERSION = pkg_resources.parse_version("1.0.0")

if pandas is not None:
    PANDAS_INSTALLED_VERSION = pkg_resources.get_distribution("pandas").parsed_version
else:
    # Set to less than MIN version.
    PANDAS_INSTALLED_VERSION = pkg_resources.parse_version("0.0.0")

...

@unittest.skipIf( 
    pandas is None or PANDAS_INSTALLED_VERSION < PANDAS_MINIUM_VERSION, 
    "Only `pandas version >=1.0.0` supported", 
) 
```

The alternative approach is using `pytest.importorskip`, which is more concise:
```py
pytest.importorskip(
        "pandas",
        minversion="1.0.0",
        reason="Requires `pandas version >= 1.0.0` which introduces pandas.NA",
)
```

We should use `pytest.importorskip` combined with the `minversion` argument. That feature relies on the imported module's `__version__` attribute, but all our major dependencies support it, so we should be fine.

**Comment by plamut** [comment]
Hmm, this issue might already be obsolete, since we are promoting some of the extras to required dependencies in #757. After that is done, there might not be much left to unify in the first place. :slightly_smiling_face:

**Comment by tswast** [comment]
:-)

Pandas is still gonna be optional. But yeah, `importorskip` is so much nicer.

**Comment by Linchin** [comment]
@tswast Just went through the code base, and I don't see any `@unittest.skipIf(...)` with a version check in it. I do see a lot of `@unittest.skipIf(pandas is None, "Requires `pandas`")` though. Can we mark this issue as resolved, or we should replace all `@unittest.skipIf(...)` with `importorskip` here?

**Comment by tswast** [comment]
> Can we mark this issue as resolved, or we should replace all @unittest.skipIf(...) with importorskip here?

Using `importorskip` everywhere would be my preference.

**Comment by shollyman** [comment]
Moving this to @chalmerlowe as he's been cleaning this up, but I'm not sure if its fully completed.

**Comment by chalmerlowe** [comment]
There are no more references to `@unittest.skipif`.
We have solidified on an approach that uses `pytest.importorskip()`

Similarly, we removed references to the package versions as constants (ie *_INSTALLED_VERSION).

Closing.
