### ISSUE TITLE
[Discussion/FR] run performance metrics on key use cases

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#763]
Specifically, downloading query results to a pandas DataFrame is one I'm especially keen to make sure we detect and avoid performance regressions on.

I see that pandas and several other tools make use of Airspeed Velocity (ASV) https://asv.readthedocs.io/en/stable/ to measure performance.

**Comment by plamut** [comment]
Presumably this is something that could benefit all libraries, not just BigQuery. There have been discussions about introducing long running tests, and detecting performance regression would be a part of that, but I don't know how far those discussions are. Do you?

Every now and then the same idea comes up at Pub/Sub meetings, might be worth poking some internal folks for any news to not duplicate the effort.

**Comment by tswast** [comment]
I recall some conversations years ago. Some quite complex infrastructure was even built to reduce the network effects on performance by creating a generic gRPC emulator.

I don't think that work is funded anymore, though. I like the idea of using a community-standard tool, as it has less of a risk of becoming unsupported.

**Comment by Linchin** [comment]
I really love this idea, but due to current team priorities, especially cross-team planning, I will mark this issue as won't fix for now. Whenever this changes, feel free to reopen it.
