### ISSUE TITLE
PATCH Precondition check failed

### ISSUE THREAD

**Issue by hzitoun** [googleapis/python-bigquery#772]
I'm using BigQuery Python Client version google-cloud-bigquery==2.15.0 and sometimes when I update (PATCH) a table via:

#### Code example

```python

client.update_table(table, ["labels", "description"])
```

I got the following error:

#### Stack trace
```
PreconditionFailed('PATCH 
https://bigquery.googleapis.com/bigquery/v2/projects/my-proj/datasets/my-ds/tables/my-table?prettyPrint=false
: Precondition check failed.')
```

#### Environment details

  - OS type and version: Google Cloud Function
  - Python version: `3.8`
  - pip version: `unknown`
  - `google-cloud-bigquery` version: `2.15.0 `

**Comment by tswast** [comment]
I suspect that's due to `etags` not matching because of concurrent edits to the table. Do you have a full stacktrace you can share?

**Comment by hzitoun** [comment]
@tswast Sorry for the delay. I don't have more logs, unfortunately. However, it is indeed probably because of concurrent edits since many users are working with my metadata update job hosted in the cloud function.

**Comment by tswast** [comment]
In the case of concurrent edits, it's best to catch this error, get a fresh copy of table metadata, and try your edit again.
