### ISSUE TITLE
increase the default chunk size for uploads

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#775]
See: https://github.com/googleapis/google-resumable-media-python/issues/238

The BigQuery client library currently defaults to 1MB chunks. https://github.com/googleapis/python-bigquery/blob/36fe86f41c1a8f46167284f752a6d6bbf886a04b/google/cloud/bigquery/client.py#L98

The `bq` CLI currently defaults to 100MB chunks (via googleapiclient). https://github.com/googleapis/google-api-python-client/blob/11d78e0fe9290d1a8c516a0e2f2e019dbd1877f9/googleapiclient/http.py#L69

Perhaps this could be the cause of the 10x performance difference for file uploads?

CC @KevinTydlacka

**Comment by tswast** [comment]
Looks like they Python GCS client defaults to 40MB, so this might not be the whole story. https://github.com/googleapis/python-storage/blob/c027ccf4279fb05e041754294f10744b7d81beea/google/cloud/storage/fileio.py#L27

**Comment by tseaver** [comment]
That is the default for the `BlobReader` / `BlobWriter` wrappers:  the [default for the underlying blob methods](https://github.com/googleapis/python-storage/blob/c027ccf4279fb05e041754294f10744b7d81beea/google/cloud/storage/blob.py#L139) is 100 Mb:

```python
_DEFAULT_CHUNKSIZE = 104857600  # 1024 * 1024 B * 100 = 100 MB
```

**Comment by tswast** [comment]
fixed by https://github.com/googleapis/python-bigquery/pull/799
