### ISSUE TITLE
Streaming inserts are not retried when a timeout occurs

### ISSUE THREAD

**Issue by quentin-sommer** [googleapis/python-bigquery#779]
Expected behaviour: streaming inserts are retried on timeout

**Comment by tswast** [comment]
@quentin-sommer Can you share some more context? A stack trace and a code sample reproducing this issue would be very helpful in determining if modifying the retry behavior is the right approach.

**Comment by quentin-sommer** [comment]
Hi,
Unfortunately since the error is a timeout returned by the BQ service I can't really reproduce it. I've seen it happen once in production in June but I don't have access to the logs anymore.
I'm basing the PR on this [documentation](https://cloud.google.com/bigquery/docs/error-messages). What do you think about it?

**Comment by tswast** [comment]
I noticed in the implementation of https://github.com/googleapis/python-bigquery/pull/896 that we currently aren't retrying client-side timeouts, but unless you explicitly set a timeout I don't think this 100% solves the situation.

I also recently learned about the [X-Server-Timeout header](https://cloud.google.com/apis/docs/system-parameters#definitions). It might be possible to set this header value to something small enough that we're able to reproduce the server-side error you saw.

**Comment by tswast** [comment]
If this timeout was actually a client-side timeout, this was fixed in #896. I'll close this for now, but if you do see the issue again and have more information so we can better identify the circumstances (or better yet reproduce it), please let us know.
