### ISSUE TITLE
use pandas Int64 type by default to avoid precision loss

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#793]
The Int64 dtype has been around long enough now that I'd be comfortable with using it by default. In https://github.com/googleapis/python-bigquery/pull/786 I notice that `float64` dtype is used for nullable integers even when this would cause loss-of-precision.

**Comment by jimfulton** [comment]
FTR, as someone who's tried to cram lots of data into pandas, int64 sounds brutal. :)  It's certainly better than float.

Integer data with small range are pretty common.  If I had to guess, I'd say most common.

I'm not sure what could be done.  I guess some ideas:

- use limit to avoid loading too much data,
- Provide hints like, use int16 for integers by default.
- Provide an option to convert numeric with 0 scale to integers based on precision. 
- Provide an option to scan data to determine ranges that inform types.
- Give up and use dask(?) or spark to work with the data.

**Comment by tswast** [comment]
They can already manually specify smaller dtypes if they'd like, which hopefully is a good middle ground. Folks that know they are working with smaller ranges can specify as such, but by default we support the full range as BigQuery does.

**Comment by tswast** [comment]
Maybe we also want to use the new "string" dtype by default if the pandas version supports it? https://pythonspeed.com/articles/pandas-string-dtype-memory/

**Comment by tswast** [comment]
Fixed by https://github.com/googleapis/python-bigquery/pull/786, will be present in V3.
