### ISSUE TITLE
ChunkedEncodingError is not retried when fetching data with list_rows()

### ISSUE THREAD

**Issue by plamut** [googleapis/python-bigquery#801]
Original issue: https://github.com/googleapis/python-bigquery-storage/issues/242

A user reported that they saw an error in production when fetching table data with `Client.list_rows()`. That method uses the [default retry object](https://github.com/googleapis/python-bigquery/blob/7e0e2bafc4c3f98a4246100f504fd78a01a28e7d/google/cloud/bigquery/retry.py#L49), which currently does not consider `requests.exceptions.ChunkedEncodingError` retryable.

(it does retry `requests.exceptions.ConnectionError`, but `ChunkedEncodingError` is not a subclass of that.

**Comment by andrewsg** [comment]
I think this may actually be due to https://github.com/googleapis/google-resumable-media-python/issues/240 - PR for this is in the works.
