### ISSUE TITLE
[Breaking Change] Remove `google.cloud.bigquery_v2` directory and related code generation

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#814]
The `google.cloud.bigquery_v2` modules are frequently out-of-date. This primarily affect the usability of BigQuery ML.

Since BigQuery is a REST API, protobuf changes must be synced manually in internal code repo before they can be published to https://github.com/googleapis/googleapis

In the years since we first introduced `google.cloud.bigquery_v2`, we've seen that BigQuery ML adds model stats and model types much more frequently than the protobuf changes are actually published.

We've worked around this by:

* I and @shollyman (mostly @shollyman lately) republish the protos when a customer has a problem, such as in https://github.com/googleapis/python-bigquery/issues/293
* Avoiding the worst exceptions when an enum or property isn't present, such as in https://github.com/googleapis/python-bigquery/issues/334

**Solution**

* [x] Remove `google.cloud.bigquery_v2` modules
* [x] Update owlbot config to stop generating "client"
* [x] In the BigQuery ML classes, whereever we were returning protobuf object, return the JSON-parsed API response, instead.
  * [x] Complex types become dictionaries.
  * [x] Enums become strings.
* [x] In the routines logic, create manual wrappers and enums where needed.

Supersedes https://github.com/googleapis/python-bigquery/issues/319

**Comment by plamut** [comment]
Done in #855. The issue was probably not closed automatically, because the PR was merged into the `v3` branch.
