### ISSUE TITLE
Expand pyarrow to support 5.x releases

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#831]
Changelog: https://raw.githubusercontent.com/apache/arrow/4591d76fce2846a29dac33bf01e9ba0337b118e9/CHANGELOG.md

**Comment by tswast** [comment]
Looks like there've been a few improvements for Apple silicon and Segfault/crash fixes. I'm not seeing anything that should give us trouble from the changelog.

**Comment by plamut** [comment]
Where are the changes from 4.0.0? They seem to be missing from the changelog. :)

It appears the mark breaking changes with the `[BREAKING]`, but there's nothing like that in the 5.0.0 release notes, thus it indeed seems fine.
