### ISSUE TITLE
Creating a View without explicit dataset name fails

### ISSUE THREAD

**Issue by thedamnedrhino** [googleapis/python-bigquery#841]
#### Environment details

  - OS type and version: `MacOS 10.15`
  - Python version: `3.7.7`
  - pip version: `19.2.3`
  - `google-cloud-bigquery` version: `2.6.1`
  - 
#### Steps to reproduce

  1. Set the default dataset on the client: 
```
default_job_config = bigquery.QueryJobConfig(default_dataset='{}.{}'.format(project_name, dataset_name))
client = bigquery.Client(project=project_name, default_query_job_config=default_job_config)
```
  2. Create a view using the client: `client.query('CREATE VIEW test AS SELECT * FROM test_table').result()`  
  3. Query the created view `test` using the client/web interface gives the error:
> Table name "test_table" cannot be resolved: dataset name is missing.

**Comment by plamut** [comment]
I was able to reproduce the issue, thanks for reporting it.

> Running the same code and replacing my VIEWs with TABLEs relieves the issue.

Just curious, why not explicitly specifying the dataset name in the view query? Seems easier than switching from VIEWs to TABLEs?

**Comment by thedamnedrhino** [comment]
@plamut thanks - we need to change the dataset at runtime. I want to keep the table names dataset agnostic.

**Comment by chalmerlowe** [comment]
NOTE: This is not an issue with the `python-bigquery` client directly.

Per this internal Google buganizer issue (`195382760`), which replicates this issue using the `bq` CLI interface.

> we don't currently support views that use default dataset.

Gonna close this issue as "will not work" in relationship to `python-bigquery` and allow the internal bug tracker to follow the underlying `bq` issue to completion.

In the interim, it seems like a possible solution is to incorporate code that merges the table names and dataset at runtime.
