### ISSUE TITLE
remove `date_as_object` argument from `to_dataframe`

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#861]
I believe this was added to support https://github.com/googleapis/python-bigquery/issues/11 and https://github.com/googleapis/python-bigquery/issues/136, but I'm not convinced that this was the right approach. Instead, what we do for `TIMESTAMP` columns seems more appropriate -- try to cast to the right data type. If it fails due to out-of-range, then fallback to objects.

**Comment by tswast** [comment]
Per https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#generating-ranges-of-timestamps

`datetime64[ns]` is the expected dtype for dates. This is the dtype that is the result of the [pandas.date_range](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.date_range.html?highlight=date_range#pandas.date_range) function.

**Comment by plamut** [comment]
OK, will remove it.

**Comment by jimfulton** [comment]
@plamut have you started on this yet?

I'm running into this as part of my pandas date type.  I'd just as soon take this.

**Comment by plamut** [comment]
@jimfulton Kind of started, but had to switch to other things. If it's a semi-blocker for you that needs to be resolved now-ish, feel free to take it.

**Comment by jimfulton** [comment]
Mine! :)

Thanks.

**Comment by tswast** [comment]
Fixed by #972 (to be released in v3)
