### ISSUE TITLE
feat: ensure Arrow type metadata is consistent between REST and BQ Storage APIs

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#894]
The BQ Storage API annotates certain types with additional information so that they can be disambiguated. For example, to tell GEOGRAPHY from STRING columns.

We don't currently annotate the types we create when data is initially downloaded from the REST API.

If we make these consistent, the user could register Arrow extension types, which can hook into the default pyarrow -> pandas conversions. See discussion on: https://github.com/googleapis/python-bigquery/pull/848#issuecomment-904025863

**Comment by jimfulton** [comment]
I have questions. 

- Confirming, this needs to be done on the client, right?
- Do we know what extension metadata are added by the BigQuery storage API?

  Is this documented somewhere? Or do we need to determine it empirically?

**Comment by jimfulton** [comment]
It would be cool if you could attach application-specific metadata to BigQuery columns. :)  You could, for example mark a struct as defining a `timedelta`. :)

**Comment by jimfulton** [comment]
I know folks are busy, so I'm going to **assume**:

>     * Confirming, this needs to be done on the client, right?

yes.
 
>     * Do we know what extension metadata are added by the BigQuery storage API?
>       Is this documented somewhere? Or do we need to determine it empirically?

empirical.

**Comment by tswast** [comment]
There are some docs here: https://cloud.google.com/bigquery/docs/reference/storage#arrow_schema_details

But I think empirical will best help us make sure the specific values.

I consider the metadata from the BQ Storage API to be the canonical version. We should update the "arrow from REST API" logic to match.
