### ISSUE TITLE
Add optional `metadata` argument to allow per API request custom HTTP headers

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#897]
I notice that the generated client methods have an optional `metadata` argument, which takes an iterable of tuples. These tuples indicate additional headers that can be sent with a request.

Currently to set custom HTTP headers, it requires use of the private _http attribute and applies across the whole client. We should allow extra headers to be set in a more public manner.

This would apply to any method that makes an HTTP request, so basically anywhere that currently takes a `retry` object.

Where this would most be useful short term is anywhere that calls `jobs.insert` (copy, extract, load, query) as that would allow us to try https://github.com/googleapis/python-cloud-core/issues/134 without changing the behavior of timeout.

**Comment by tswast** [comment]
@plamut @jimfulton This might be a good one for one of you to pick up. It is a feature request, but a higher priority since it's being requested by a customer and backend engineering.

I'm thinking something along the lines of these `metadata` arguments in the generated clients:

https://github.com/googleapis/python-bigquery-storage/blob/29436141e128b172e9bd42ac12f3ca06fc1947be/google/cloud/bigquery_storage_v1/services/big_query_read/client.py#L399

It may require some changes to [`google-cloud-core`](https://github.com/googleapis/python-cloud-core/blob/master/google/cloud/_http.py), but since we're already able to pass in extra headers, probably not. (Unless we want to address the fact that technically it's possible to have more than one header with the same name, so really a dictionary or sequence of tuples should be allowed)

**Comment by jimfulton** [comment]
Blocked for @tswast action item: "investigate what other languages do"

**Comment by chalmerlowe** [comment]
Closing as will not work.
