### ISSUE TITLE
list_rows ignore big page_sizes

### ISSUE THREAD

**Issue by cnarvaezmeli** [googleapis/python-bigquery#915]
Hey,
I was trying to find an answer to this problem. I have a query that must download 30 GB of data on average. If I try to use the `to_dataframe` function the instance dies since it gets out of memory.

My approach is to list_rows and then write multiple parquets into my pc, then read one by one and process what I need.

The problem is that even if I set page_size the chunk value is fixed after a concrete value, I can see [in this documentation](https://cloud.google.com/bigquery/docs/paging-results#paging) that there is a 100MB of data limit. And if that's the case, do you have any idea?

Maybe the fastest approach is doing multiple queries.

#### Environment details

  - OS type and version:
  - Python version: `python 3.7.4`
  - pip version: `pip 21.2`
  - `google-cloud-bigquery` version: `2.25.0`

#### Steps to reproduce

  1. Create table with millions of rows
  2. Query table using `list_rows` with a big page size
  3.  try to save the results into pandas with `to_dataframe_iterable`
  3. the number of rows per page is inferior to what you expect from the config
 

#### Code example

```python
from google.cloud import bigquery
query = """SUPER QUERY"""
query_job = bigquery.query(query)
destination = query_job.destination
destination = bigquery.get_table(destination)
page_size = int(destination.num_rows // 30)
rows = bigquery.list_rows(destination, page_size= page_size)
print(f"total rows: {rows.total_rows}, rows per page {page_size}, n_pages {rows.total_rows/page_size}")
# total rows: 169372268, rows per page 5645742, n_pages 30.000001416997094
df_generator = rows.to_dataframe_iterable()
for df in df_generator:
    print(df.shape)
# (35898, 67)
# (35898, 67)
# ...
# (35898, 67)

```

Thanks!

**Comment by jimfulton** [comment]
Note that you can simplify the code above along the lines of:

```
client = bigquery.Client()
df_iterator = client.query(query).result().pages
```

**Comment by jimfulton** [comment]
Another option is to use [`extract_table`](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.client.Client.html#google.cloud.bigquery.client.Client.extract_table) to extract the destination table to cloud storage and then download the resulting file.

**Comment by jimfulton** [comment]
@cnarvaezmeli have we addressed your question/concern?

FTR, `list_rows` doesn't ignore `page_size`, but the back end doesn't let you increase it beyond the default. (The Python client is passing the value, but the server isn't honoring it.) Arguably, it's a bit of a decoy.

**Comment by cnarvaezmeli** [comment]
Hey, thanks for your help.
In the end, I decided to make multiple queries using date ranges. I made the pagination test (almost 2k pages) but the download process was really slow.

I can confirm this behavior is due to the transfer limits we have in paginations. And since I can download more data with multiple queries I used that option.

Maybe this is not the use case for pagination.

**Comment by jimfulton** [comment]
> Maybe this is not the use case for pagination.

Assuming that "this" refers to downloading large tables or query results :), I think `extract_table` would be a better fit.

**Comment by tswast** [comment]
I believe `to_dataframe_iterable()` is limiting you to a single stream / thread of processing. You have a few options here, one would be to use the lower-level google-cloud-bigquery-storage client directly.

For curiosity sake, is Dask something you've considered? There has been some work in the community to build a Dask / BigQuery connector based on parallel BQ Storage API streams: https://github.com/dask/dask/issues/3121

**Comment by cnarvaezmeli** [comment]
Hey all, thanks for your comments, I will be reviewing all the possibilities you mentioned here.

@plamut We already have partitions by date, the data I'm downloading is part of a range for those dates, that's why we have the rows number I already commented. We are going to implement a cluster to see how it goes.

@tswast I used Dask before, I will check this topic, thanks!
