### ISSUE TITLE
Remove deprecated features

### ISSUE THREAD

**Issue by plamut** [googleapis/python-bigquery#920]
Several library features have been marked as deprecated awhile ago. A major version bump represents a good opportunity to remove them.

Of course, removed features need to be mentioned in the future 3.x upgrade guide - a note about their removal and a possible alternative, if it exists.

**Comment by tswast** [comment]
So long as we've been loud enough in our deprecation (logging warnings, etc.), this sounds good to me.

**Comment by plamut** [comment]
Some users will always argue that they did not see/hear the warnings, no matter how loud we make them. :grin:

**Comment by tswast** [comment]
closing as obsolete / fixed. We removed some features, though perhaps not all, and now the 3.x ship has sailed. ⛵
