### ISSUE TITLE
Integration test with pyarrow nightly builds?

### ISSUE THREAD

**Issue by emkornfield** [googleapis/python-bigquery#95]
I'm not sure how difficult it would be to add, but it might be useful to regularly test the library against pyarrow nightly build's to catch regressions before they make their way into releases.

**Comment by plamut** [comment]
@emkornfield That is something that is actually being discussed recently in a wider scope - the goal is to prevent regressions (not just in BigQuery) when a new version of a dependency (either Google's or from a 3rd party) breaks a client library that depends on it. It has already happened several times, and _will_ happen again.

If/when such testing is in place, it would probably not be difficult to also include testing pre-release versions of a few selected 3rd-party dependencies, and `pyarrow` is probably a good candidate for that, considering its complexity.

I will keep this open for visibility, and thanks for suggesting it!

**Comment by tswast** [comment]
@crwilcox This seems like it'd fit with the pre-release tests infrastructure you mentioned in the Python Client Libs meeting today.
