### ISSUE TITLE
Support policy tags when loading avro files with `load_table_from_uri`

### ISSUE THREAD

**Issue by shotarok** [googleapis/python-bigquery#955]
**Is your feature request related to a problem? Please describe.**

When loading Avro files on a GCS bucket, I couldn't specify the policy tags with `LoadJobConfig.schema`. Please take a look at the below example code. My request is to enable to specify the policy tags with `load_table_from_uri` and Avro files.

```python
from pprint import pprint

from google.cloud import bigquery
from google.cloud.bigquery.schema import PolicyTagList

# Construct a BigQuery client object.
client = bigquery.Client()

# TODO(developer): Set table_id to the ID of the table to create.
# table_id = "your-project.your_dataset.your_table_name"
client.delete_table(table_id, not_found_ok=True)

# TODO(developer) Set policy_tag_name to an policy tag to attach with the name column
# policy_tag_name = "projects/your-project/locations/us/taxonomies/xxxx/policyTags/yyyy"
policy_1 = PolicyTagList(names=[policy_tag_name])

job_config = bigquery.LoadJobConfig(
    source_format=bigquery.SourceFormat.AVRO,
    schema=[
        bigquery.SchemaField("name", "STRING", policy_tags=policy_1),
        bigquery.SchemaField("post_abbr", "STRING"),
    ],
)
uri = "gs://cloud-samples-data/bigquery/us-states/us-states.avro"

load_job = client.load_table_from_uri(
    uri, table_id, job_config=job_config
)  # Make an API request.

load_job.result()  # Waits for the job to complete.

destination_table = client.get_table(table_id)
pprint(destination_table.schema)
```

```console
$ python test.py
[SchemaField('name', 'STRING', 'NULLABLE', None, (), ()),
 SchemaField('post_abbr', 'STRING', 'NULLABLE', None, (), ())]
```

 **Describe the solution you'd like**

Create an option to prioritize the LoadJobConfig.schema rather than the schema in the Avro file's header.

 **Describe alternatives you've considered**

N/A

 **Additional context**

I could specify the policy tags when loading CSV files like https://github.com/googleapis/python-bigquery/issues/397#issuecomment-746741812. However, that didn't work for Avro files. It was hard to figure out the behavior from code. We may want to have a warning when `LoadJobConfig.schema` is ignored.

**Comment by plamut** [comment]
@shotarok Thank you for the useful report and research. So if I understand correctly, you created your own schema (with policy tags), but that was ignored and Avro schema was used instead?

The load job config [docs](https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#JobConfigurationLoad.FIELDS.schema) say the following:
```
The schema can be omitted if the destination table already exists, or if you're loading data from Google Cloud Datastore.
```
So if schema is available elsewhere, for example when a table already exists, the load job config schema is optional. This makes me think that the backend only uses the schema as some sort of fallback. I'll check whether this is a bug or a feature (@tswast ?).

FWIW, the client itself does not do anything special ([source](https://github.com/googleapis/python-bigquery/blob/76c06168451b5eb37ca87dd4004deda8b9088c4b/google/cloud/bigquery/client.py#L2320-L2342)), it just starts the job and returns it. It might be a challenge to detect when the provided schema was **not** used (and manually comparing the provided schema with the actual is not really appealing).

**Comment by shotarok** [comment]
@plamut Thank you for your quick follow-up! I understand the client itself doesn't do anything special. 

> if schema is available elsewhere, for example when a table already exists, the load job config schema is optional.

I should ask this question a GCP support but I have an additional question about this specification. When we use `load_table_from_uri` in the `WRITE_TRUNCATE` mode, the existing table's schema is ignored. I put the example code below. Do you think if this is an intentional behavior?

<details>
<summary>example code</summary>

```python
from pprint import pprint

from google.cloud import bigquery
from google.cloud.bigquery.schema import PolicyTagList


# Construct a BigQuery client object.
uri = "gs://cloud-samples-data/bigquery/us-states/us-states.avro"
client = bigquery.Client()

# TODO(developer): Set table_id to the ID of the table to create.
table_id = "kouzoh-p-kohama.test.us-states"


# Make sure there is no table
client.delete_table(table_id, not_found_ok=True)


# Make an API request
client.load_table_from_uri(
    uri, table_id, job_config=bigquery.LoadJobConfig(
        source_format=bigquery.SourceFormat.AVRO,
    )
).result()
print("# Schema after loading initial data")
pprint(client.get_table(table_id).schema)


# TODO(developer) Set policy_tag_name to an policy tag to attach with the name column
# policy_tag_name = "projects/your-project-id/locations/us/taxonomies/xxxx/policyTags/yyyy"
policy_tag_name = "projects/kouzoh-p-kohama/locations/us/taxonomies/1717079334944938374/policyTags/5314007805783364641"
policy_1 = PolicyTagList(names=[policy_tag_name])
table = client.get_table(table_id)
table.schema=[
    bigquery.SchemaField("name", "STRING", policy_tags=policy_1),
    bigquery.SchemaField("post_abbr", "STRING"),
]
client.update_table(table, ["schema"])
print("# Schema after updating policy tags with update_table")
pprint(client.get_table(table_id).schema)


# Make an API request to load data in the WRITE_TRUNCATE mode
client.load_table_from_uri(
    uri, table_id, job_config=bigquery.LoadJobConfig(
        source_format=bigquery.SourceFormat.AVRO,
        write_disposition=bigquery.WriteDisposition.WRITE_TRUNCATE,
    )
).result()
print("# Schema after loading data into the same table in the WRITE_TRUNCATE mode")
pprint(client.get_table(table_id).schema)
```

```console
# Schema after loading initial data
[SchemaField('name', 'STRING', 'REQUIRED', 'The common name of the state.', (), ()),
 SchemaField('post_abbr', 'STRING', 'REQUIRED', 'The postal code abbreviation of the state.', (), ())]
# Schema after updating policy tags with update_table
[SchemaField('name', 'STRING', 'NULLABLE', None, (), ('projects/your-project-id/locations/us/taxonomies/xxxx/policyTags/yyyy',)),
 SchemaField('post_abbr', 'STRING', 'NULLABLE', None, (), ())]
# Schema after loading data into the same table in the WRITE_TRUNCATE mode
[SchemaField('name', 'STRING', 'REQUIRED', 'The common name of the state.', (), ()),
 SchemaField('post_abbr', 'STRING', 'REQUIRED', 'The postal code abbreviation of the state.', (), ())]
```
</details>

**Comment by plamut** [comment]
> When we use load_table_from_uri in the WRITE_TRUNCATE mode, the existing table's schema is ignored. ... Do you think if this is an intentional behavior? 

@shotarok  Yes, according to the [docs](https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#JobConfigurationLoad.FIELDS.write_disposition) this is expected:

> WRITE_TRUNCATE: If the table already exists, BigQuery overwrites the table data and uses the schema from the load.

Does this answer your question?

**Comment by shotarok** [comment]
@plamut Yes, thank you The same behavior happening in my first and second examples makes sense to me now. 

I know updating the schema with policy tags after loading Avro files is a workaround, and I understand It'd be hard to support policy tags by client changes. However, I initially didn't expect that `LoadJobConfig.schema` works for CSV but it didn't work for Avro with `load_table_from_uri `. So I'm concern that this could be a pitfall for other developers.

**Comment by chalmerlowe** [comment]
Closing as will not work.
