### ISSUE TITLE
Schedule parameter not available (big query)

### ISSUE THREAD

**Issue by Iuiu1234** [googleapis/python-bigquery#96]
Using bq from bash (google cloud sdk) there is the parameter 'shedule' to schedule the query.

But I can't see that argument as any of the function in the package (quey, job_configuration)

**Comment by plamut** [comment]
@Iuiu1234 There is work going on that will make scheduling the queries easier, thus the BigQuery client methods will likely not get the new `schedule` parameter. However, one can use the [BigQuery Data Transfer Service]( https://cloud.google.com/bigquery-transfer/docs/transfer-service-overview) to schedule queries.

**Comment by meredithslota** [comment]
More information about scheduling queries can be found here: https://cloud.google.com/bigquery/docs/scheduling-queries including code samples on how to do it in Python using DTS. :)
