### ISSUE TITLE
Test TestBigQuery.test_transaction_info is flaky.

### ISSUE THREAD

**Issue by jimfulton** [googleapis/python-bigquery#975]
https://source.cloud.google.com/results/invocations/2ca6ab31-ba0f-4a6b-ab53-55943a5bac42/targets/cloud-devrel%2Fclient-libraries%2Fpython%2Fgoogleapis%2Fpython-bigquery%2Fpresubmit%2Fsystem-3.8/log

This test fails pretty regularly for me.

**Comment by tswast** [comment]
I checked the job state for a recent failure:

```json
{
  "kind": "bigquery#job",
  "etag": "NSFsBEFD1+My1joEvfuzGQ==",
  "id": "precise-truck-742:US.a9a56a2e-836e-4679-add5-941543bfbf8f",
  "selfLink": "https://content-bigquery.googleapis.com/bigquery/v2/projects/precise-truck-742/jobs/a9a56a2e-836e-4679-add5-941543bfbf8f?location=US",
  "user_email": "REDACTED",
  "configuration": {
    "query": {
      "query": "\n            BEGIN TRANSACTION;\n              INSERT INTO `precise-truck-742.python_bigquery_tests_system_bq_system_test_1632082968448.test_dml_statistics`\n              VALUES (\"one\", 1), (\"two\", 2), (\"three\", 3), (\"four\", 4);\n\n              UPDATE `precise-truck-742.python_bigquery_tests_system_bq_system_test_1632082968448.test_dml_statistics`\n              SET bar = bar + 1\n              WHERE bar \u003e 2;\n            COMMIT TRANSACTION;\n        ",
      "priority": "INTERACTIVE",
      "useLegacySql": false
    },
    "jobType": "QUERY"
  },
  "jobReference": {
    "projectId": "precise-truck-742",
    "jobId": "a9a56a2e-836e-4679-add5-941543bfbf8f",
    "location": "US"
  },
  "statistics": {
    "creationTime": "1632082969228",
    "startTime": "1632082969269",
    "endTime": "1632082974219",
    "totalBytesProcessed": "55",
    "query": {
      "totalBytesProcessed": "55",
      "totalBytesBilled": "10485760",
      "totalSlotMs": "19050",
      "statementType": "SCRIPT"
    },
    "totalSlotMs": "19050",
    "numChildJobs": "4"
  },
  "status": {
    "state": "DONE"
  }
}
```

Looks like no `transactionInfo` key was ever added. I've filed internal issue 200542305 to have the backend team investigate further.

**Comment by tswast** [comment]
According to the backend folks, since a query job can contain multiple transactions, this key is not intended to be present on the parent job. Instead, we need to iterate through the child jobs to find the one that began the transaction.

They are investigating why `transactionInfo` appears on the parent job at all (more often than not).

**Comment by jimfulton** [comment]
Still flaking for me.  Was the fix applied to the V3 branch?

https://source.cloud.google.com/results/invocations/9cbcc219-744b-4309-bdde-86aee021f703/targets/cloud-devrel%2Fclient-libraries%2Fpython%2Fgoogleapis%2Fpython-bigquery%2Fpresubmit%2Fprerelease-deps-3.8/log

**Comment by plamut** [comment]
@jimfulton IIRC not yet, I'm waiting on https://github.com/googleapis/python-bigquery/pull/855 (pretty large!) to get in before syncing `v3` with `main`.

**Comment by tswast** [comment]
Fixed by https://github.com/googleapis/python-bigquery/pull/996
