### ISSUE TITLE
Bigquery: import error with v1.24.0

### ISSUE THREAD

**Issue by sagydr** [googleapis/python-bigquery#99]
bug googleapis/google-cloud-python#9965 is still happening in v1.24.0 and six v1.14.0

`File "/root/.local/share/virtualenvs/code-788z9T0p/lib/python3.6/site-packages/google/cloud/bigquery/schema.py", line 17, in <module>

from six.moves import collections_abc
ImportError: cannot import name 'collections_abc'
`

why did you close the googleapis/google-cloud-python#9965  issue if it still reproduces for many people?

![image](https://user-images.githubusercontent.com/9664064/81319446-58f37380-9098-11ea-9cd3-73d37ae7e2f7.png)

**Comment by plamut** [comment]
@sagydr The issue was closed, when the `six` dependency was pinned to `>=1.13.0`. I also tried installing `bigquery` into a fresh Python 3.6 environment and it worked fine.

```
$ python3.6 -m venv venv-3.6
$ . venv-3.6/bin/activate
$ pip install google-cloud-bigquery
$ python
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import bigquery  # no error
>>> exit()
$ pip freeze
cachetools==4.1.0
certifi==2020.4.5.1
chardet==3.0.4
google-api-core==1.17.0
google-auth==1.14.2
google-cloud-bigquery==1.24.0
google-cloud-core==1.3.0
google-resumable-media==0.5.0
googleapis-common-protos==1.51.0
idna==2.9
pkg-resources==0.0.0
protobuf==3.11.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pytz==2020.1
requests==2.23.0
rsa==4.0
six==1.14.0
urllib3==1.25.9
```
Since the installed package versions (`six`, specifically) are correct, it appears that there's something in your environment that is not what it seems to be.

Could you please double check that `six== 1.13.0+` is indeed installed? What is the output of the following?
```
$ pip freeze
````

Additionally, If you add the following to your application code (before importing `bigquery`), what does it print out?
```py
import six
print(six.__version__)
```

It might be that the environment used to actually run the application is different from the one `pip freeze` check was run on, which would explain the difference in behavior.

**Comment by plamut** [comment]
@sagydr Any luck with solving the issue? Is there anything else we can help you with?

**Comment by ZIYUNCHEN** [comment]
I have tried bigquery 1.23 and 1.24 with six 1.14. Both still showing the same error

google-cloud-bigquery==1.23.0
six==1.14.0 

google-api-core==1.17.0
google-auth==1.14.3
google-cloud-core==1.3.0

**Comment by plamut** [comment]
@ZIYUNCHEN Just to be sure, what does `print(six.__version__)` say if you put it right before the line where `bigquery` is imported? Is the version actually used by the code indeed 1.13.0+`?

I tried quite a few combinations multiple times, but did not manage to reproduce the reported import error with an updated version of `six`.

**Comment by gosselinmarcantoine** [comment]
I am also facing this issue. I did a pip install --upgrade six==1.13.0 but the print(six.__version__) still shows 1.12.0. What would be the way to fix this?

**Comment by plamut** [comment]
@gosselinmarcantoine The most likely reason is that the upgraded `six` was installed in a different Python environment than the Python that actually runs the application.

You can try with determining which `pip` was used to upgrade `six` from the command line:
```
$ which pip
```
and printing out the `six` module path used in the code:
```py
print(six.__file__)
```
This could give a clue whether indeed different Python environments are used.

**Comment by juanroesel** [comment]
> I am also facing this issue. I did a pip install --upgrade six==1.13.0 but the `print(six.__version__)` still shows 1.12.0. What would be the way to fix this?

I was having the same issue, and when followed @plamut instructions I indeed realized that the 'six' package that was being loaded into my Python Environment was version 1.11, while the one I had installed in my virtual environment was version 1.14. 

I'm using PyCharm, and was able to manually upgrade the 'six' package to the latest version (1.15) by going to Preferences, clicking on the 'six' package and executing an update in the Project Interpreter window. Don't forget to select the version you would like to get.

After this update BigQuery (v.1.24.0) now runs smoothly in my Python Environment.

**Comment by anistark** [comment]
Still facing this issue. My jenkins deployment pipeline broke with the same message.

Packages on my server:
```
google-cloud-bigquery==2.0.0
six==1.15.0
```

Also, checked:

```
>>> print(six.__file__)
/<local_path>/venv/lib/python3.8/site-packages/six.py
>>> print(six.__version__)
1.15.0
```

Please advice.

**Comment by HemangChothani** [comment]
@anistark Could you please share the stack trace or it's same as mentioned above.

**Comment by anistark** [comment]
@HemangChothani It's the same as mentioned:

```
"    from google.cloud import bigquery", 
"  File \"/home/deploy/src/lib/python3.6/site-packages/google/cloud/bigquery/__init__.py\", line 35, in <module>", 
"    from google.cloud.bigquery.client import Client", 
"  File \"/home/deploy/src/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 57, in <module>", 
"    from google.cloud.bigquery import _pandas_helpers", 
"  File \"/home/deploy/src/lib/python3.6/site-packages/google/cloud/bigquery/_pandas_helpers.py\", line 36, in <module>", 
"    from google.cloud.bigquery import schema", 
"  File \"/home/deploy/src/lib/python3.6/site-packages/google/cloud/bigquery/schema.py\", line 17, in <module>", 
"    from six.moves import collections_abc", 
"ImportError: cannot import name 'collections_abc'", 
```

**Comment by HemangChothani** [comment]
@anistark I think you need to verify again of you `six` library path and `google-cloud-bigquery` path, because `google-cloud-bigquery ` installed in python3.6/site-package where `six` is installed for venv/python3.8/site-package.

**Comment by anistark** [comment]
@HemangChothani 

The 3.8 one was from my local and 3.6 one was from my server.

**Comment by HemangChothani** [comment]
@anistark Could you please try with the fresh environment locally , i am not able to reproduce this error.
$ python3.6 -m venv venv-3.6
$ . venv-3.6/bin/activate
$ pip install google-cloud-bigquery or pip3 install google-cloud-bigquery

if still error occurs then please share the stack trace, six.__file__ path and list of dependencies which you can get through `pip freeze` command

**Comment by anistark** [comment]
Now, I'm getting a new error. I uninstalled and installed again google-cloud-bigquery with six 1.15.0

```
File "/.../venv/lib/python3.8/site-packages/google/protobuf/internal/python_message.py", line 570, in _GetFieldByName
    return message_descriptor.fields_by_name[field_name]
KeyError: 'proto3_optional'
```

Any ideas?


```
    from google.cloud import bigquery
  File "/.../venv/lib/python3.8/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
    from google.cloud.bigquery.client import Client
  File "/.../venv/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 57, in <module>
    from google.cloud.bigquery import _pandas_helpers
  File "/.../venv/lib/python3.8/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 36, in <module>
    from google.cloud.bigquery import schema
  File "/.../venv/lib/python3.8/site-packages/google/cloud/bigquery/schema.py", line 19, in <module>
    from google.cloud.bigquery_v2 import types
  File "/.../venv/lib/python3.8/site-packages/google/cloud/bigquery_v2/__init__.py", line 19, in <module>
    from .types.encryption_config import EncryptionConfiguration
  File "/.../venv/lib/python3.8/site-packages/google/cloud/bigquery_v2/types/__init__.py", line 18, in <module>
    from .encryption_config import EncryptionConfiguration
  File "/.../venv/lib/python3.8/site-packages/google/cloud/bigquery_v2/types/encryption_config.py", line 29, in <module>
    class EncryptionConfiguration(proto.Message):
  File "/.../venv/lib/python3.8/site-packages/proto/message.py", line 215, in __new__
    field=[i.descriptor for i in fields],
  File "/.../venv/lib/python3.8/site-packages/proto/message.py", line 215, in <listcomp>
    field=[i.descriptor for i in fields],
  File "/.../venv/lib/python3.8/site-packages/proto/fields.py", line 104, in descriptor
    self._descriptor = descriptor_pb2.FieldDescriptorProto(
  File "/.../venv/lib/python3.8/site-packages/google/protobuf/internal/python_message.py", line 509, in init
    field = _GetFieldByName(message_descriptor, field_name)
  File "/.../venv/lib/python3.8/site-packages/google/protobuf/internal/python_message.py", line 572, in _GetFieldByName
    raise ValueError('Protocol message %s has no "%s" field.' %
ValueError: Protocol message FieldDescriptorProto has no "proto3_optional" field.
```

**Comment by HemangChothani** [comment]
@anistark please share `pip freeze` list

**Comment by anistark** [comment]
Here's the partial pip freeze output:

```
gcloud==0.17.0
geographiclib==1.50
geopy==1.21.0
google-api-core==1.22.2
google-api-python-client==1.12.3
google-auth==1.22.0
google-auth-httplib2==0.0.4
google-cloud-bigquery==2.0.0
google-cloud-core==1.4.1
google-cloud-firestore==1.9.0
google-cloud-logging==1.15.1
google-cloud-storage==1.31.2
google-cloud-translate==3.0.1
google-crc32c==1.0.0
google-resumable-media==1.0.0
googleapis-common-protos==1.52.0
googlemaps==4.4.2
graphviz==0.12
grpcio==1.32.0

proto-plus==1.10.0
protobuf==3.8.0

six==1.15.0
```

**Comment by HemangChothani** [comment]
Update protobuf  to `protobuf==3.11.3` and try it again.

**Comment by HemangChothani** [comment]
@anistark Is your issue resolved?

**Comment by anistark** [comment]
Not really @HemangChothani. Still coming even with `protobuf==3.11.3` on local.

**Comment by tswast** [comment]
The generator is using protobuf 3.12.0, so that is the minimum version needed. See: https://github.com/googleapis/python-api-core/issues/48

**Comment by anistark** [comment]
Finally. Thanks @tswast for that info. Thanks @HemangChothani for staying with me through that. Will try deploying on server now. 🤞🏼

**Comment by anistark** [comment]
Creating an issue for this for future references: #305

**Comment by formigone** [comment]
I'm still getting this error even after installing `protobuf==3.12.0`


```bash
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/models/dagbag.py", line 204, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/opt/bitnami/airflow/venv/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/my-dag.py", line 16, in <module>
    from google.cloud import bigquery
  File "/opt/bitnami/python/lib/python3.6/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
    from google.cloud.bigquery.client import Client
  File "/opt/bitnami/python/lib/python3.6/site-packages/google/cloud/bigquery/client.py", line 57, in <module>
    from google.cloud.bigquery import _pandas_helpers
  File "/opt/bitnami/python/lib/python3.6/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 36, in <module>
    from google.cloud.bigquery import schema
  File "/opt/bitnami/python/lib/python3.6/site-packages/google/cloud/bigquery/schema.py", line 19, in <module>
    from google.cloud.bigquery_v2 import types
  File "/opt/bitnami/python/lib/python3.6/site-packages/google/cloud/bigquery_v2/__init__.py", line 19, in <module>
    from .types.encryption_config import EncryptionConfiguration
  File "/opt/bitnami/python/lib/python3.6/site-packages/google/cloud/bigquery_v2/types/__init__.py", line 18, in <module>
    from .encryption_config import EncryptionConfiguration
  File "/opt/bitnami/python/lib/python3.6/site-packages/google/cloud/bigquery_v2/types/encryption_config.py", line 29, in <module>
    class EncryptionConfiguration(proto.Message):
  File "/opt/bitnami/python/lib/python3.6/site-packages/proto/message.py", line 215, in __new__
    field=[i.descriptor for i in fields],
  File "/opt/bitnami/python/lib/python3.6/site-packages/proto/message.py", line 215, in <listcomp>
    field=[i.descriptor for i in fields],
  File "/opt/bitnami/python/lib/python3.6/site-packages/proto/fields.py", line 111, in descriptor
    proto3_optional=self.optional,
ValueError: Protocol message FieldDescriptorProto has no "proto3_optional" field.
```

Pip freeze:

```bash
pip freeze       
WARNING: The directory '/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
appdirs==1.4.4
attrs==20.2.0
Authlib==0.15
authorizenet==1.1.3
boto3==1.15.16
botocore==1.18.16
cached-property==1.5.2
cachetools==4.1.1
certifi==2020.6.20
cffi==1.14.3
chardet==3.0.4
cryptography==3.1.1
dataclasses==0.7
defusedxml==0.6.0
docopt==0.4.0
docutils==0.15.2
ecdsa==0.14.1
enum-compat==0.0.3
future==0.18.2
google-api-core==1.22.4
google-auth==1.22.1
google-auth-oauthlib==0.4.1
google-cloud-bigquery==2.1.0
google-cloud-bigquery-storage==2.0.0
google-cloud-core==1.4.3
google-cloud-storage==1.31.2
google-crc32c==1.0.0
google-resumable-media==1.1.0
googleads==22.0.0
googleapis-common-protos==1.52.0
grpcio==1.32.0
idna==2.10
intuit-oauth==1.2.2
isodate==0.6.0
jmespath==0.10.0
libcst==0.3.12
lxml==4.5.2
mandrill==1.0.57
mypy-extensions==0.4.3
numpy==1.19.2
oauthlib==3.1.0
pandas==0.25.3
pandas-gbq==0.14.0
proto-plus==1.10.1
protobuf==3.12.0
pyarrow==1.0.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.18
pydata-google-auth==1.1.0
pymongo==3.7.2
python-bsonstream==0.1.3
python-dateutil==2.8.1
python-jose==3.2.0
python-quickbooks==0.8.1
pytz==2020.1
PyXB==1.2.5
PyYAML==5.3.1
rauth==0.7.3
requests==2.24.0
requests-file==1.5.1
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
rsa==4.6
s3transfer==0.3.3
simple-salesforce==1.0.0
simplejson==3.17.0
six==1.15.0
stripe==2.38.0
typing-extensions==3.7.4.3
typing-inspect==0.6.0
urllib3==1.25.10
virtualenv==16.7.6
xmltodict==0.12.0
zeep==4.0.0
```

**Comment by shska** [comment]
I got this issue and fixed it by run this command "pip install protobuf==3.14.0".

**Comment by parnell** [comment]
I also had the same error and but protobuf version 3.14.0 didn't solve it. Version 3.15.0 and above seem to have worked, 3.15.5 in my case.
`pip install -U protobuf`

**Comment by YohanObadia** [comment]
Same error with protobuf 3.6

**Comment by plamut** [comment]
Sorry for missing the last few comments, it's an old closed issue.

Import errors like these often indicate that not all dependencies are up to date, and upgrading them usually resolves the problem. If that's not the case, then yes, please do open a new issue with all the details, and we'll have a look.

**Comment by bhajesh2** [comment]
When you see the error like this, it also says that the bigquery version is not the right version for the OS where you installed it.

I had similar issue in my OS version (Ubuntu 16.0) and when I degraded my bigquery version from 2.4.0 to 1.10.1. The issue resolved.

**Comment by Bapi-Reddy** [comment]
> When you see the error like this, it also says that the bigquery version is not the right version for the OS where you installed it.
> 
> I had similar issue in my OS version (Ubuntu 16.0) and when I degraded my bigquery version from 2.4.0 to 1.10.1. The issue resolved.

This worked thanks

**Comment by TheMightyRaider** [comment]
Upgrading protobuf to version 3.20.3 worked for me
